### ISSUE TITLE
stratified and grouped K-fold CV

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#101]
(suggested by @avehtari) 

Now that we have basic k-fold cross-validation in **rstanarm** we should implement stratified and grouped K-fold-CV.

**Comment by avehtari** [comment]
Would it be possible to do the groupd k-fold-cv automatically based on *lmer formula?

**Comment by jgabry** [comment]
We can use the formula to detect which variables split the data into
groups, so yeah we probably could do that.
