### ISSUE TITLE
codecov not working with rstanarm anymore

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#102]
#### Summary:

The `rstanarm --> travis --> codecov` chain is broken. The last update on codecov is from two months ago. This does not appear to be a problem in general (i.e., it's working with other packages). 

#### Description:

This is what happens in the `travis --> codecov` step:

```
5.46s$ Rscript -e 'covr::codecov()'
Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> -> package_coverage -> add_hooks -> readLines -> file
In addition: Warning messages:
1: In utils::install.packages(repos = NULL, lib = tmp_lib, pkg$path,  :
  installation of package ‘/home/travis/build/stan-dev/rstanarm’ had non-zero exit status
2: In file(con, "r") :
  cannot open file '/tmp/RtmptRhDXz/R_LIBS27241855aa44/rstanarm/R/rstanarm': No such file or directory
Execution halted
```

#### Reproducible Steps:

Trigger a (successful) travis build and look at the  `after_success` section of the log. Also check https://codecov.io/gh/stan-dev/rstanarm, which shows no updates in the past two months.

**Comment by tjmahr** [comment]
Would the modification of `after_success` as in this related issue https://github.com/jimhester/covr/issues/178 help?

**Comment by jgabry** [comment]
Yeah I think that's what we needed. Thanks for the tip!
