### ISSUE TITLE
Offset sometimes doesn't work with posterior_predict

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#109]
(Reported by Seth via email)

```r
library(rstanarm)
x1 = rnorm(100,0,.1)
x2 = rnorm(100,2,.1)
y = rnbinom(200,1,exp(c(x1,x2))/20)
data = data.frame(group=c(rep(1,100),rep(2,100)),x=c(x1,x2),y=y)

M2 <-stan_glmer.nb(y ~ x + (1|group),data=data,iter=40,warmup=20,chains=1,offset=rep(0,200))
print(M2$stanfit)
predictions0 = posterior_predict(M2) # ok 
predictions1 = posterior_predict(M2,data) #ok 

predictions2 = posterior_predict(M2,data[1:50,]) 
Warning message:
In sweep(eta, 2L, offset, `+`) :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
```

@bgoodri What seems to be the case is that `posterior_predict` tries to use the original offset used to fit the model. But not only does this not really make sense if `newdata` is specified, even 
if `newdata` is the same dataset as the original, if it's not the exact same size then we don't know which `offset` values to drop. 

Should add an `offset` argument to `posterior_predict` that is required if `newdata` is specified?

**Comment by bgoodri** [comment]
Can `offset` default to 0 in `posterior_predict` and have it recycle?

**Comment by jgabry** [comment]
Just to be clear, do you mean can we add a new `offset` argument and have it default to 0 and recycle? If so, then I think so.

**Comment by jgabry** [comment]
Although shouldn't it only default to 0 if `newdata` is specified? Without `newdata` it should default to the offset specified when fitting the model, right?

**Comment by bgoodri** [comment]
Without `newdata`, yes it should use the old offset

**Comment by jgabry** [comment]
Ok I'll see if I can make that work. I guess we need to do this for `log_lik` too if `newdata` is specified, right?

**Comment by bgoodri** [comment]
Yeah

**Comment by flaxter** [comment]
What behavior are you intending when newdata is specified? Presumably there has to be a way of specifying a new offset to go with newdata, right?

**Comment by jgabry** [comment]
Yeah I added an offset argument to the functions that take a newdata
argument so you'll be able to specify that when calling posterior_predict.
