### ISSUE TITLE
have option to draw from the prior of any model

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#11]
We should just be able to pass `N = 0` and skip over the likelihood contribution to the posterior, but it may take a bit of fiddling. People like to see how much the data contributes to the posterior distribution relative to the prior.

**Comment by jgabry** [comment]
Could we avoid most of the fiddling using an if statement and passing in an
indicator?

**Comment by bgoodri** [comment]
That is what I mean by fiddling. Maybe N = 0 is the indicator.

**Comment by jgabry** [comment]
Ah, I thought you meant fiddling beyond that. Relatedly, even if running
the full model including the likelihood should we also store the
accumulated log-prior? That would take some code modification but could be
useful.

**Comment by bgoodri** [comment]
Maybe. I'm kind of hesitant to put things that only have relative meanings
in front of our users. In this case, relative to the total log-likelihood.

**Comment by bgoodri** [comment]
implemented in 9f8e0bb
