### ISSUE TITLE
posterior_linpred() does not use newdata for stann_gamm4 models

### ISSUE THREAD

**Issue by noamross** [stan-dev/rstanarm#132]
#### Summary:
`posterior_linpred()` does not seem to use `newdata` for `stann_gamm4` models

#### Description:
When I pass a new data frame to `posterior_linpred()` along with a model fit with `stan_gamm4`, the result is identical to the case where I don't pass any new data at all. 

#### Reproducible Steps:
```
library(rstanarm)
library(tidyverse)
gtemp <- read.delim("http://www.metoffice.gov.uk/hadobs/hadcrut4/data/current/time_series/HadCRUT.4.5.0.0.annual_ns_avg.txt",
                    sep="", header = FALSE) %>%
  select(1,2) %>%
  set_names(c("Year", "Temperature")) %>%
  mutate(Year = as.double(Year))

st_mod2 <- stan_gamm4(Temperature ~ s(Year), data = gtemp)
preds2 <- posterior_linpred(st_mod2)
preds2_d <- posterior_linpred(st_mod2, newdata=data.frame(Year=(1850:2016) + 0.1))
identical(preds2, preds2_d)
```
This results in TRUE

#### RStanARM Version:
2.13.1 (installed from github)

#### R Version:
3.3.1

#### Operating System:
OS X 10.12.1

**Comment by bgoodri** [comment]
I believe the issue here has to do with the fact that you are adding a constant (0.1). If you add `runif(nrow(gtemp))`, then the linear predictors are not identical. I'm not sure that we have the right behavior here, but when mgcv constructs `s(Year)` it is centered.

**Comment by bgoodri** [comment]
So, I guess we should tack on the original mean(s) multiplied by the coefficients.

**Comment by noamross** [comment]
Yeah, I think you need to correct for mgcv's centering if you're reconstructing the gam object when doing this.  For my particular application, I need to add a constant in order to estimate the derivatives of the smooths, but in any case we'll want to be able to get predictions on an absolute scale.

**Comment by bgoodri** [comment]
This should be fixed on GitHub now. It goes back to the mgcv-style parameterization, so now Stan is calling `predict.gam` with `type = "lpmatrix"`.
