### ISSUE TITLE
stan_glm + log_lik fails depending on length of data

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#133]
#### Summary:
log_lik function with a stan_glm function and newdata fails depending on length of data

#### Description:
See the code below. The code works if length(y) is 20, but fails if length(y) is 30

#### Reproducible Steps:
yt <- rnorm(10000)
N<-20
y <- rnorm(N)
model1 <- stan_glm(y ~ 1, family = gaussian(link = "identity"), 
                   cores = 4, seed = i1, iter=500, refresh=-1,
                   open_progress = FALSE)
ll2 <- log_lik(model1, newdata = yt)
N<-30
y <- rnorm(N)
model1 <- stan_glm(y ~ 1, family = gaussian(link = "identity"), 
                   cores = 4, seed = i1, iter=500, refresh=-1,
                   open_progress = FALSE)
ll2 <- log_lik(model1, newdata = yt)

#### RStanARM Version:
2.12.1

#### R Version:
The version of R you are running (e.g., from `getRversion()`)
3.2.3

#### Operating System:
Ubuntu Linux 16.04

**Comment by jgabry** [comment]
Does it work if you specify newdata = data.frame(y = yt) instead of without
the data frame? If so then I think we just need a more informative error
message.

**Comment by avehtari** [comment]
On 23.11.2016 21:47, Jonah Gabry wrote:
> Does it work if you specify newdata = data.frame(y = yt) instead of without
> the data frame? If so then I think we just need a more informative error
> message.

Yes, it works with data frames (did found out this before your answer, but 
didn't have time to comment this)

Aki
