### ISSUE TITLE
loo with k_threshold error

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#135]
#### Summary:
loo function with k_threhold argument fails for no-pool rstanarm model

#### Description:
Start with vignette at 
http://mc-stan.org/documentation/case-studies/pool-binary-trials-rstanarm.html

Run 
> loo(fit_nopool,k_threshold=0.5)

to get an error
Error in model.frame.default(Terms, newdata, xlev = object$xlevels) : 
  factor Player has new level Clemente

#### Reproducible Steps:
See Description above

#### RStanARM Version:
The version of the rstanarm package you are running (e.g., from `packageVersion("rstanarm")`)
2.13.1

#### R Version:
The version of R you are running (e.g., from `getRversion()`)
3.2.3

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

Ubuntu 16.04

**Comment by jgabry** [comment]
Thanks Aki. I think I have a fix for this. The issue arises when computing
log lik (internally inside the reloo function) when nrow(newdata) is 1 and
any of the predictors are coded as factor variables in R (the Player
variable in this case). R is trying to validate the levels of the factor so
we just need to work around that. I'll merge the fix into the master branch
tonight or tomorrow once I test it more.
