### ISSUE TITLE
variable selection by projective prediction

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#14]
Let's do this for rstanarm

https://groups.google.com/d/msg/stan-users/5IxMxY3tv2w/ptm2vyJmBwAJ

see the repo https://github.com/jtpi/rstan-varsel

**Comment by jgabry** [comment]
I agree. I was thinking the same thing when I saw the post earlier.

**Comment by bgoodri** [comment]
@avehtari I have started to implement this, at least for Gaussian models with identity link. What do you want the final output to look like? Do you want to force the user to pass in a testing dataset to cross-validate with? By itself, the forward selection process does not make a decision, but I could make a plot that looks like this for the diabetes model:
![fprojsel](https://cloud.githubusercontent.com/assets/3386282/14230033/5f186b9e-f916-11e5-97ba-6f570354ba31.png)

**Comment by bgoodri** [comment]
Also, how should we start the forward selection for models without intercepts?

**Comment by avehtari** [comment]
Great!

I think we don't need to force if someone wants to make a quick experiment without CV, but the use of CV for selecting the model size should be easy and the recommended approach.

You could start the forward selection by having imaginary null model with the divergence set to infinity.

**Comment by jgabry** [comment]
@avehtari Is your student still working on integrating this with rstanarm? No rush, just checking.

**Comment by jgabry** [comment]
Ok great. No rush at all, just glad to know it's in progress.

**Comment by jgabry** [comment]
This is projpred now
