### ISSUE TITLE
Syntax for nested random effect, when using stan_gamm4 

### ISSUE THREAD

**Issue by Atan1988** [stan-dev/rstanarm#141]
#### Summary:
A short summary (no more than a sentence or two).
I am not sure how to specify nested random effect term for stan_gamm4;
Is it random = ~ (1|a/b)?

#### Description:
A full description of the problem (or question).

#### Reproducible Steps:
If applicable, the steps required to reproduce the issue. If you have a reproducible example, please include it.

#### RStanARM Version:
The version of the rstanarm package you are running (e.g., from `packageVersion("rstanarm")`)

#### R Version:
The version of R you are running (e.g., from `getRversion()`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by jgabry** [comment]
I'm not entirely sure to be honest, but I assume it's the same as it is for
gamm4 since we're supposedly emulating that function's interface. I think
@bgoodri will   know better than I do; he's been working on stan_gamm4.

**Comment by bgoodri** [comment]
It should be the same as in table 2 of
https://cran.r-project.org/web/packages/lme4/vignettes/lmer.pdf
with the exception in the `stan_gamm4` case that the `(1 | g1 / g2)` is part of a separate formula passed to `random`, whereas in the `stan_glmer` case the `(1 | g1 / g2)` is part of the `formula` argument.

**Comment by jgabry** [comment]
I'm going to close this as I think @bgoodri's answer is sufficient.
