### ISSUE TITLE
fitting models with multiple group-varying parameters (lmer syntax)

### ISSUE THREAD

**Issue by Felipe-Osorio** [stan-dev/rstanarm#154]
#### Summary:
Fitting an rstanarm model fails under certain conditions if I leave the correlation matrix unmodeled (for group-varying effects). `rstanarm` throws an index out of range exception.

#### Description:
I'm running into a bug while estimating a model with a number of group-varying intercepts and slopes. It only surfaces when more than one predictor is allowed to vary by group. Specifically, it appears to be related to the use of the double pipe notation, inherited from lmer syntax ('||').

#### Reproducible Steps:
This works:
```
library(rstanarm)
m1 = stan_glmer(log(price) ~
                  carat + # linear price
                  x + 
                  (1 + carat + x | cut)
                , data = diamonds
                , chains = 4
                , cores = 4
                , iter = 900
                , warmup = 300
)
```

This does not work:
```
m1 = stan_glmer(log(price) ~
                  carat + # linear price
                  x + 
                  (1 + carat + x || cut)
                , data = diamonds
                , chains = 4
                , cores = 4
                , iter = 900
                , warmup = 300
)
Error in eval(substitute(expr), envir, enclos) : 
  Exception thrown at line -1: []: accessing element out of range. index 161813 out of range; expecting index to be between 1 and 161812; index position = 1v
failed to create the sampler; sampling not done
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
```

#### RStanARM Version:
2.14.1

#### R Version:
3.2.3

#### Operating System:
red hat linux

**Comment by bgoodri** [comment]
Did this work with previous versions of rstanarm?

**Comment by Felipe-Osorio** [comment]
yes @bgoodri
