### ISSUE TITLE
package takes infinite time to install

### ISSUE THREAD

**Issue by ahmedelmahy** [stan-dev/rstanarm#158]
#### Summary:
The installation doesn't finish.

#### Description:
After installing rstan successfully, I used install.packages('rstanarm') the following prints on the screen

`g++ -I/usr/share/R/include -DNDEBUG -I"`"/usr/lib/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DEIGEN_NO_DEBUG  -I"/home/ahmed/R/i686-pc-linux-gnu-library/3.3/StanHeaders/include" -I"/home/ahmed/R/i686-pc-linux-gnu-library/3.3/rstan/include" -I"/home/ahmed/R/i686-pc-linux-gnu-library/3.3/BH/include" -I"/home/ahmed/R/i686-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/ahmed/R/i686-pc-linux-gnu-library/3.3/RcppEigen/include"   -fpic  -O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -flto -ffat-lto-objects  -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -c Modules.cpp -o Modules.o`

It doesn't proceed further. I tried dependencies=TRUE; type='source' ; and tried to download it from github, the problem still persists.

#### R Version:
3.3.2
#### Operating System:

-Computer-
Processor		: 2x Intel(R) Core(TM)2 Duo CPU     T8300  @ 2.40GHz
Memory		: 1022MB (312MB used)
Operating System		: Ubuntu 16.04.1 LTS (Lubuntu 32bits)

**Comment by bgoodri** [comment]
I don't think it will install from source with only 1022 MB. If you use
clang++ instead of g++, you might have a chance, which can be done by
putting

CXX = clang++

in the ~/.R/Makevars file

Also, it could help if you put

CXXFLAGS += -Os

in the ~/.R/Makevars file.

**Comment by ahmedelmahy** [comment]
This was a low memory issue, I upgraded the RAM to 2 GB and It installed well.

**Comment by jgabry** [comment]
Glad that works. Thanks for following up.

On Sat, Feb 11, 2017 at 2:45 PM ahmedelmahy <notifications@github.com>
wrote:

This was a low memory issue, I upgraded the RAM to 2 GB and It installed
well.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stan-dev/rstanarm/issues/158#issuecomment-279170766>,
or mute the thread
