### ISSUE TITLE
set.seed() across different computers

### ISSUE THREAD

**Issue by felixthoemmes** [stan-dev/rstanarm#160]
#### Summary:
Same seed values and runs of stan_glm do not produce same results on different computers. 

#### Description:
I am using rstanarm and the stan_glm function in my class. To ensure that all students have the same answers, I require a manual seed. However, results are still different, despite the identical seed. I have checked my own PC, and if I use a seed value I get the identical result every time. However, when I went to my Mac in my lab, I got a different value (yet, I can reproduce it every time I rerun the analysis). 
Below, you can download my data, and run the very simple linear Bayesian regression (with flat priors).
 
#### Reproducible Steps:
library (foreign)
library(rstan,quietly = TRUE)
library(rstanarm,quietly = TRUE)
library(BayesFactor,quietly = TRUE)

set.seed(1234)
words <- read.spss("https://github.com/felixthoemmes/hwdatasets/blob/master/childwords.sav?raw=true",to.data.frame
= TRUE)
blm1 <- stan_glm(words ~ age, data = words,prior =
normal(0,100),prior_intercept = normal(0,100),refresh=-1)
summary(blm1,digits=5)

#### RStanARM Version:
2.13.1
#### R Version:
3.3.2
#### Operating System:
Win10

**Comment by bgoodri** [comment]
This is known behavior in all of Stan. Setting a seed only ensures that you will get the same results on the same computer. The reason it is in general not the same is that different compilers or different compiler versions do not produce exactly the same binary instructions.

**Comment by felixthoemmes** [comment]
OK - thanks for the clarification. Any good suggestions to ensure that one has the same compiler, or is this generally impossible, if one machine is a PC and the other a Mac?

**Comment by betanalpha** [comment]
Generally impossible.

**Comment by felixthoemmes** [comment]
Thank you all for providing such speedy replies! Best of luck with the project and thank you for providing it to the community at large. Much appreciated!

**Comment by jgabry** [comment]
Thanks! And even though you won't get exactly the same answer if it's a
well specified model the answers should be very very similar.
