### ISSUE TITLE
printing the result of a stan_glm is broken

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#17]
```
test <- stan_glm(mpg ~ wt, data = mtcars)
> test

Call:  stan_glm(formula = mpg ~ wt, data = mtcars)

Coefficients:
(Intercept)           wt  
     37.226       -5.322  

Degrees of Freedom: Total (i.e. Null);  30 Residual
Error in signif(x$null.deviance, digits) : 
  non-numeric argument to mathematical function

> traceback()
4: format(signif(x$null.deviance, digits))
3: cat("Null Deviance:\t   ", format(signif(x$null.deviance, digits)), 
       "\nResidual Deviance:", format(signif(x$deviance, digits)), 
       "\tAIC:", format(signif(x$aic, digits)))
2: print.glm(x)
1: function (x, ...) 
   UseMethod("print")(x)
```
This seems to have to do with the fact that it is calling print.glm now.

**Comment by jgabry** [comment]
Hmm, printing seems to work fine for me:
    
    test <- stan_glm(mpg ~ wt, data = mtcars)
    > test

    Inference for Stan model: Gaussian GLM.
    4 chains, each with iter=2000; warmup=1000; thin=1; 
    post-warmup draws per chain=1000, total post-warmup draws=4000.

                 mean se_mean   sd  2.5%   25%   50%   75% 97.5% n_eff Rhat
    (Intercept) 37.29    0.04 1.94 33.46 36.01 37.26 38.60 41.15  2173    1
    wt          -5.35    0.01 0.58 -6.47 -5.73 -5.34 -4.96 -4.23  2072    1
    sigma        3.13    0.01 0.41  2.46  2.85  3.10  3.39  4.00  2154    1
    mean_PPD    20.09    0.02 0.80 18.54 19.56 20.08 20.62 21.66  2439    1

    Samples were drawn using NUTS(diag_e) at Thu Aug 20 11:46:48 2015.
    For each parameter, n_eff is a crude measure of effective sample size,
    and Rhat is the potential scale reduction factor on split chains (at 
    convergence, Rhat=1).`

**Comment by bgoodri** [comment]
Do you have any unpushed commits?

**Comment by jgabry** [comment]
Nothing that would affect this. Just one thing adding an example to posterior_predict

**Comment by bgoodri** [comment]
Mine is not calling print.stanreg()

> class(test)
[1] "stanreg" "glm"     "lm"
> print.stanreg(test)
Error: could not find function "print.stanreg"
> rstanarm:::print.stanreg(test)
trace: print(x$stanfit, pars = "lp__", include = FALSE, ...)
Inference for Stan model: Gaussian GLM.
1 chains, each with iter=1000; warmup=0; thin=1;
post-warmup draws per chain=1000, total post-warmup draws=1000.

trace: print(round(s$summary, digits_summary), ...)
            mean    sd   2.5%   25%   50%   75% 97.5%
(Intercept)  1.97  0.23   1.55  1.82  1.96  2.11  2.45
cyl         -0.05  0.93  -1.79 -0.69 -0.09  0.58  1.84
disp         0.01  0.01   0.00  0.01  0.01  0.02  0.03
hp          -0.01  0.02  -0.04 -0.02 -0.01  0.00  0.02
drat         0.87  5.53  -9.85 -2.96  1.04  4.53 11.83
wt          -2.64  1.29  -5.09 -3.50 -2.66 -1.76 -0.20
qsec         0.80  1.26  -1.49 -0.05  0.78  1.67  3.29
vs           0.55  3.73  -6.55 -1.93  0.53  2.96  7.88
am           1.81  4.49  -7.19 -1.18  1.77  4.81 10.36
gear        -0.14  1.65  -3.18 -1.35 -0.10  0.98  3.09
carb        -1.09  1.37  -3.82 -1.98 -1.11 -0.17  1.67
sigma        9.85  1.15   7.75  9.09  9.78 10.55 12.27
mean_PPD    13.16 32.40 -48.68 -8.79 12.95 33.58 79.20

What is your NAMESPACE?

**Comment by jgabry** [comment]
Weird. My NAMESPACE is exactly the one currently on the master branch:

# Generated by roxygen2 (4.1.1): do not edit by hand

S3method(VarCorr,stanreg)
S3method(coef,stanreg)
S3method(confint,stanreg)
S3method(fitted,stanreg)
S3method(fixef,stanreg)
S3method(log_lik,stanreg)
S3method(loo,stanreg)
S3method(predict,stanreg)
S3method(ranef,stanreg)
S3method(residuals,stanreg)
S3method(se,stanreg)
S3method(sigma,stanreg)
S3method(vcov,stanreg)
S3method(waic,stanreg)
export(R2)
export(cauchy)
export(decov)
export(horseshoe)
export(horseshoe_plus)
export(launch_shinystan)
export(loo)
export(normal)
export(posterior_predict)
export(prior_options)
export(stan_aov)
export(stan_glm)
export(stan_glm.fit)
export(stan_glmer)
export(stan_lm)
export(stan_lm.fit)
export(stan_lm.wfit)
export(stan_lmer)
export(stan_polr)
export(stan_polr.fit)
export(student_t)
export(waic)
import(rstan)
import(stats)
importFrom(lme4,VarCorr)
importFrom(lme4,fixef)
importFrom(lme4,glFormula)
importFrom(lme4,ranef)
importFrom(lme4,sigma)
importFrom(loo,loo)
importFrom(loo,loo.function)
importFrom(loo,waic)
importFrom(loo,waic.function)
importFrom(shinystan,launch_shinystan)

**Comment by bgoodri** [comment]
What does

grep("stanreg", methods(print), value = TRUE)

say?

**Comment by jgabry** [comment]
It gives me `"print.stanreg"`. I assume it gives you `NULL` or `character(0)` or something?

**Comment by bgoodri** [comment]
Yeah. I don't understand how yours works without a S3method(print,stanreg)
in the NAMESPACE.

**Comment by jgabry** [comment]
Me neither, but I just pushed a commit that changes the roxygen stuff for print and summary and I think the NAMESPACE recognizes them properly now.
