### ISSUE TITLE
cleanup betareg in continuous.stan

### ISSUE THREAD

**Issue by imadmali** [stan-dev/rstanarm#173]
I think we no longer need the code in the generated quantities block that "catches" NaNs from the `beta_rng` function in `continuous.stan`. (Most of what I'm referring to is here https://github.com/stan-dev/rstanarm/blob/master/exec/continuous.stan#L253-L269.) The `cleanup-betareg` branch gets rid of this.

**Comment by jgabry** [comment]
Thanks Imad. Are the underlying changes to Stan math library already
released in 2.14 or not until 2.15?

**Comment by imadmali** [comment]
It looks like it was fixed in 2.13 https://github.com/stan-dev/math/releases/tag/v2.13.0

**Comment by jgabry** [comment]
Ok great. Go ahead and make a PR whenever you think the branch is ready.

**Comment by jgabry** [comment]
closed via #174
