### ISSUE TITLE
'meanfield' results don't match 'sampling' results

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#18]
Seeing as it's the intercept that's so different, does this have to do with the centering? 

    fit <- stan_glm(mpg ~ wt, data = mtcars)
    fit_vb <- stan_glm(mpg ~ wt, data = mtcars, algorithm = "meanfield")

    > summary(fit)
                    mean mcse   sd   2.5%    25%    50%    75%  97.5% n_eff Rhat
    (Intercept)    37.25 0.04 1.94  33.31  35.96  37.22  38.55  41.09  2477    1
    wt             -5.33 0.01 0.58  -6.45  -5.72  -5.33  -4.94  -4.22  2477    1
    sigma           3.15 0.01 0.43   2.45   2.85   3.10   3.39   4.12  1813    1
    mean_PPD       20.10 0.02 0.79  18.59  19.58  20.10  20.62  21.67  2636    1
    log-posterior -53.10 0.04 1.32 -56.61 -53.65 -52.76 -52.14 -51.62   938    1

    > summary(fit_vb)
                   mean   sd  2.5%   25%   50%   75% 97.5%
    (Intercept)    0.62 0.07  0.50  0.58  0.62  0.67  0.77
    wt            -5.37 0.63 -6.65 -5.77 -5.35 -4.96 -4.16
    sigma          3.12 0.34  2.52  2.88  3.10  3.35  3.87
    mean_PPD      37.46 2.13 33.29 36.02 37.38 38.92 41.74
    log-posterior 20.16 0.88 18.52 19.54 20.19 20.75 21.84

**Comment by bgoodri** [comment]
I don't think so because the centering and the rest of the .stan file are the same, only the function being called is different. I think `vb()` is just not very reliable yet, in this case because the `mean_PPD` is way different from `mean(mtcars$mpg)`. We'll have to see once https://github.com/stan-dev/stan/pull/1590 is merged.

**Comment by jgabry** [comment]
Ok, hopefully the autotuning  will help. But if it doesn't we should probably hold off on offering vb in rstanarm.

**Comment by akucukelbir** [comment]
yeah, this seems like ADVI was nowhere near convergence. are any intermediate results printed/stored anywhere when calling `fit_vb <- stan_glm(mpg ~ wt, data = mtcars, algorithm = "meanfield")` ?

**Comment by bgoodri** [comment]
Not currently. Also, where it stops is not necessarily the best point that
it encountered along the way. This is supposed to be dealt with somewhat in
the next ADVI PR.

**Comment by akucukelbir** [comment]
yes, we are working on it. however, it might still be helpful to have some way of telling the user in what status ADVI "returned". (e.g. whether it actually converged or hit the max number of iterations) we currently handle this by printing things out to the command line in `cmdStan`.

**Comment by bgoodri** [comment]
This example works okay now (most of the time)
