### ISSUE TITLE
bias in stan_betareg()

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#185]
#### Summary:

Running `stan_betareg()` with `prior_PD = TRUE` yields an unusually positive distribution for the intercept and a `mean_PPD` near 1.

#### Description:

When `prior_PD = TRUE`, the distribution of intercept should be centered near zero. It is for `z` but not for the main part of the model.

#### Reproducible Steps:

```
example(stan_betareg, ask = FALSE)
post <- update(fit, prior_PD = TRUE, algorithm = "sampling", iter = 10^4)
post
```

#### RStanARM Version:

2.15.3

#### R Version:

3.4

#### Operating System:

Debian

**Comment by imadmali** [comment]
@bgoodri was the issue occurring because there were no bounds on the intercept?

**Comment by bgoodri** [comment]
No, it was occurring because the intercept was getting bounded when it
wasn't supposed to be. I have it fixed on a branch where I started to
implement the cdfquantreg stuff.

**Comment by imadmali** [comment]
ah, got it.
