### ISSUE TITLE
Demos Ch5, Ch12_13, and Ch14 work, but others get  error 'Error: 'data' must be a data frame.' 

### ISSUE THREAD

**Issue by dfumento** [stan-dev/rstanarm#188]
Demos for ch 5, 12_13, and 14 all work great, but ch 3, 4, 7, 8, 9 get error messages.
From ch 9:
post1 <- stan_lm(post_test ~ treatment * pre_test, data = DATA_ENV, 
+                  prior = R2(0.75), seed = SEED, refresh = REFRESH)
Error: 'data' must be a data frame

All of non-working demos have the same error message.

rstanarm_2.15.3

The source was automatically downloaded from CRAN and compiled on install.

R Version 3.4.0
Mac OS Version  10.12.4
clang version 4.0.0 (tags/RELEASE_400/final)
/usr/local/opt/llvm/bin

**Comment by jgabry** [comment]
Thanks for reporting this. I'll look into to and get it sorted out.

**Comment by jgabry** [comment]
I think all of these should be fixed by 72c9916. Thanks again for reporting.

**Comment by dfumento** [comment]
Thank you!
