### ISSUE TITLE
Before First Release

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#19]
These tasks (and probably other things I'm forgetting) still need to be done before first release:

* [x] Change periods to underscores
* [x] Roxygen templates for function args (b6c09dc)
* [ ] Sparse matrix stuff
* [ ] Copy glmer stuff from continuous.stan to most of the others
* [ ] Copy horseshoe stuff from continuous.stan to others (and make needed changes on R side)
* [x] Negative binomial log-likelihood function
* [x] Add a help page for the plotting functions (839b03f provides links to the RStan help files. For now the links will only work if the ggplot RStan branch is installed.)
* [ ] Check which other functions need tests

**Comment by jgabry** [comment]
Also:

* [ ] Decide about inclusion of advi once the auto-tuning PR is finished

**Comment by jgabry** [comment]
* [ ] Write tests for predict. 

This is partially complete. For poisson, gaussian and binomial GLMs I added tests comparing  `predict.stanreg` to `predict.glm` for `type='link'` and `se.fit = TRUE`. For `type = 'response'` we need to test `posterior_predict`.

**Comment by jgabry** [comment]
* [ ] Write tests for posterior_predict.

**Comment by jgabry** [comment]
Vignettes:

* [x] package overview
* [x] lm
* [x] aov
* [ ] polr
* [ ] glm
* [ ] glmer  

The checked boxes don't mean that these can't or shouldn't be edited further, just that they exist and are at least useable.

**Comment by bgoodri** [comment]
The polr one is almost done. I think instead of "glm", it should be

binomial / bernoulli
count
continuous

Just because whoever is reading them might not think "I need to read about
GLMs". But the glmer one can basically be "see the three vignettes on glms,
plus see the lme4 vignettes, plus here is the prior on the covariance
matrices of the group-level coefficients".

**Comment by jgabry** [comment]
Ok, I updated the list. I forgot we had decided to split up the GLMs, but I think it's a good idea.

**Comment by bgoodri** [comment]
Various R CMD check things. In the latest version of lme4, its NAMESPACE has
```
if(getRversion() >= "3.3.0") {
    importFrom("stats", sigma)
} else {
    export(sigma)
}
```
so the `sigma` function is actually not exported for r-devel (which will probably release in October).

Also our doc/ directory grew to 7.3 MB, so a giant image must have gotten in there somehow.

We need to add
```
  importFrom("methods", "is")
  importFrom("utils", "head", "tail")
```
for some internal functions, but I'm not sure how best to do that with a roxygen-generated NAMESPACE.

Remember to call `loo` with `cores = 2` in vignettes.

**Comment by jgabry** [comment]
On Thu, Sep 3, 2015 at 8:15 PM, bgoodri <notifications@github.com> wrote:

> Also our doc/ directory grew to 7.3 MB, so a giant image must have gotten
> in there somehow.
>
Weird. I'll see if I can track that down.

> We need to add
>
>   importFrom("methods", "is")
>   importFrom("utils", "head", "tail")
>
> for some internal functions, but I'm not sure how best to do that with a
> roxygen-generated NAMESPACE.
>
I think I know how to do this with roxygen tags.

**Comment by bgoodri** [comment]
I figured out the roxygen thing. It's binomial.html that has the giant
images. It may just be the way they are rendered or it may be a ggplot2
thing.

**Comment by jgabry** [comment]
It's probably because I had it set to use svg.

**Comment by bgoodri** [comment]
Maybe png would be better, but I've never actually gotten svg to look very good from knitr.

**Comment by jgabry** [comment]
In this case, when I generate the html vignette in RStudio the graphics
look quite a bit better using svg than png. So currently I have it do
`knitr::opts_chunk$set(dev = 'svg')` to set it for the whole file.

**Comment by bgoodri** [comment]
Does it also look good in a web browser for you? In Chromium, it looks
weird.

**Comment by jgabry** [comment]
Weird in what way? It looks good on Safari, Firefox and Chrome on my mac.

**Comment by bgoodri** [comment]
I sent you a screenshot through a regular email. The "yes" is partially
missing and all the words look funny.

**Comment by jgabry** [comment]
Closing this an opening a fresh issue (#25) with an updated checklist for remaining things before release
