### ISSUE TITLE
Documentation using pkgdown

### ISSUE THREAD

**Issue by imadmali** [stan-dev/rstanarm#192]
@bgoodri @jgabry is it okay if I start a `gh-pages` branch to render all the vignettes and dev notes in ~"bookdown"~ "pkgdown" form?

View a working version of the current documentation at http://mc-stan.org/rstanarm/.

**Comment by bgoodri** [comment]
Yes

**Comment by imadmali** [comment]
So the plan is to now use [pkgdown](http://hadley.github.io/pkgdown/) to do the documentation since it provides a way to list/categorize all of the exported functions in a package (and we can link to these in the vignettes). @jgabry @bgoodri if you take a look at the docs branch and open up `doc/index.html` that'll give you an idea of what the documentation looks like. Let me know if you have any suggestions (e.g. what to include/exclude from the landing page or elsewhere, etc.).

**Comment by bgoodri** [comment]
This seems like a good idea. Is it necessary for the .html files to be
tracked by Git? We don't do that for the .Rmd files for example.

**Comment by imadmali** [comment]
No. In fact I don't think anything in `docs/` needs to be tracked by Git. I'll add it to `.gitignore` and `.Rbuildignore`.

**Comment by imadmali** [comment]
@bgoodri it looks like I was wrong. The stuff in `docs/` does need to be tracked by Git otherwise the relevant site files won't appear in the repo. I think the only work around is to do everything in `gh-pages`, which is what I've currently done. That way the doc commits won't pollute the git history in the master branch. But every time there's a change to the namespace or to a vignette, master needs to be merged into gh-pages and the docs need to be rendered.

**Comment by imadmali** [comment]
@jgabry @bgoodri if [this](http://mc-stan.org/rstanarm/) looks okay to you then I can do the same for the other R packages (rstan, bayesplot, loo, and rstantools), omitting the develop tab in the navbar.

**Comment by bgoodri** [comment]
Go ahead. We can tweak how it looks later.

**Comment by bgoodri** [comment]
This happened.
