### ISSUE TITLE
How to report results from rstanarm_lmer

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#193]
#### Summary:
I've asked this question on [stackoverflow](https://stackoverflow.com/questions/44693812/how-to-report-with-apa-style-a-bayesian-linear-mixed-models-using-rstanarm), but unfortunately had no answers 😞 . So maybe you guys  could help me...

#### Description:
Basically all I want is to put the output of rstanarm_lmer() in words, if possible following the APA6 guidelines, that do not say anything about the bayesian framework.

#### Reproducible Steps:

```r
library(tidyverse)
library(neuropsychology)
library(rstanarm)
library(lmerTest)

# Get data
df <- neuropsychology::personality %>% 
  select(Study_Level, Sex, Negative_Affect) %>% 
  mutate(Study_Level=as.factor(Study_Level),
         Negative_Affect=scale(Negative_Affect)) # I understood that scaling variables is important

# Fit the model
fitB <- stan_lmer(Negative_Affect ~ Sex + (1|Study_Level),
                  data=df,
                  prior=normal(location=0, scale=1), 
                  prior_intercept=normal(location=0, scale=1),
                  prior_PD=F)
print(fitB, digits=2)
summary(fitB, probs=c(.025, .975), digits=2)
```

Is something like the following good?

"we fitted a linear mixed model within the bayesian framework with negative affect as outcome variable, sex as predictor and study level was entered as a random effect. Priors for the coefficient and the intercept were set to normal (mean=0, sd=1). Within this model, the features of the posterior distribution of the coefficient associated with the male level suggest a decrease of negative affect (mean = -0.47, sd = 0.11, 95% CI[-0.59, -0.34]).

Thanks for your help!

**Comment by bgoodri** [comment]
Stackoverflow is fine, but be sure to use the `stan` and `rstan` tags so
that those of us who subscribe to those tags will see it. I will answer
there.

**Comment by DominiqueMakowski** [comment]
Thanks :)
