### ISSUE TITLE
suggestion : support for mixed beta models

### ISSUE THREAD

**Issue by methodds** [stan-dev/rstanarm#194]
Hi,

it's already super useful to have beta regression models available in rstanarm. Could you please consider to also provide support for mixed/multilevel beta regressions? I can only speak for the Social Sciences, but at least in that discipline there is currently a huge demand for such models.

Thanks for your awesome work :)

**Comment by bgoodri** [comment]
Now you can do this by specifying `family = mgcv::betar` in `stan_glmer` or `stan_gamm4`

**Comment by methodds** [comment]
Cool thanks :)
