### ISSUE TITLE
loo with non-default k_threshold parameter produces error

### ISSUE THREAD

**Issue by awcm0n** [stan-dev/rstanarm#197]
#### Summary:
Error message when running loo with non-default k_threshold parameter may indicate a bug.

#### Description:
Running loo with the default k_threshold parameter caused no problems, but setting k_threshold to 0.7 produced an error.

model_loo <- loo(model, k_threshold = 0.7)
1 problematic observation(s) found.
Model will be refit 1 times.

Fitting model 1 out of 1 (leaving out observation 33)
**Error: variable 'x' was fitted with type "nmatrix.1" but type "numeric" was supplied**

#### RStanARM Version:
2.15.3

#### R Version:
3.3.3 (2017-03-06)

#### Operating System:
Windows 10 Version 10.0.15063 Build 15063

**Comment by bgoodri** [comment]
What was the original model?

**Comment by jgabry** [comment]
Yeah it's hard to debug this without more info on the original model and data, but I think it has to do with how the original data was constructed. Is it possible it's the same thing as reported here: 

https://stackoverflow.com/questions/22337495/how-to-solve-predict-lm-error-variable-affinity-was-fitted-with-type-nmatr
