### ISSUE TITLE
Regularized horseshoe

### ISSUE THREAD

**Issue by jpiironen** [stan-dev/rstanarm#200]
#### Summary:
Wish: implement the regularized horseshoe prior.

#### Description:
Would be great to have the regularized horseshoe implemented in prior `hs`. The paper is now in arXiv (https://arxiv.org/abs/1707.01694) and the new prior is discussed in Section 2.3. This should be easy to add on top of the current implementation of the `hs`-prior, and there's an example code in Appendix C of the paper.

I think using the Student-t slab is fine at least for the time being, and the syntax could be something like 
`prior <- hs(df=1, global_df=1, global_scale=0.01, slab_df=4, slab_scale=2)`
I also think `slab_df = 4` would be a good default value for the degrees of freedom but for `slab_scale` you could probably use the same default value as you use in `student_t`-prior (which seems to be 2.5 except for probit regression if I understood right). I don't have much preferences regarding this.

Also, although it breaks the backward compatibility, I would now change the default shrinkage degrees of freedom to `df = 1` (horseshoe) as with the regularized horseshoe there is no more reason to recommend using `df > 1` (see Sec. 2.4 of the paper).

Thanks a lot!

**Comment by bgoodri** [comment]
What should become of hs_plus ()?

**Comment by bgoodri** [comment]
Also, I am not understanding why global_scale is still an argument to the
function rather than p_0.

**Comment by jpiironen** [comment]
`hs_plus` could be regularized as well. 

For the horseshoe, the regularization is achieved as follows
```
lambda_tilde = sqrt( c^2 * square(lambda) ./ (c^2 + tau^2*square(lambda)) )
beta ~ N(0, lambda_tilde * tau)
lambda ~ C+(0,1)
```
and for the horseshoe+ like this
```
lambda_tilde = sqrt( c^2 * square(lambda .* eta) ./ (c^2 + tau^2*square(lambda .* eta)) )
beta ~ N(0, lambda_tilde * tau)
lambda ~ C+(0,1)
eta ~ C+(0,1)
```

It could be a sensible idea to replace `global_scale` by `p_0` but I feel a bit uneasy about this. One reason is that `p_0` cannot be mapped to `global_scale` analytically when `df > 1` (slightly awkward although we do not recommend `df > 1` anymore). Another reason is that then someone would need to work out the pseudo-sigmas for every possible pair of link function and observation model (straightforward but laborious), and test that they give sensible results, and then you would need to implement all these. Thirdly, I personally find that having `p_0` as an input would somewhat misleadingly hide the fact that the relationship between `tau` and `m_eff` is not exact, but based on several approximations and assumptions. 

Furthermore, even if `p_0` was an input argument, I think it should still be possible to specify `scale_global` directly, in case someone like me would like to try out different strategies for setting up the hyperprior and comparing the results.

**Comment by bgoodri** [comment]
This was merged.
