### ISSUE TITLE
pairs plot can have wrong axes

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#204]
#### Summary:

For a bimodal posterior distribution, the off-diagonal cells of a pairs plot can miss one of the modes.

#### Description:

For example, in the second row, first column the x-axis only runs from about 0 to 1 when the histogram above it shows another mode for `lKe` that is way negative.

![pairs](https://user-images.githubusercontent.com/3386282/28095880-f007514a-6672-11e7-84c7-2ec3ae17c797.png)

#### Reproducible Steps:

That plot is from the last model glmer vignette on the nlmer branch.

#### RStanARM Version:

2.16.x

#### R Version:

3.4.x

#### Operating System:

Debian

**Comment by jgabry** [comment]
Weird. Not sure what's up with that but I'll look into it.

**Comment by jgabry** [comment]
I opened an issue at the bayesplot repo (https://github.com/stan-dev/bayesplot/issues/93). I still don't know why this is happening but it's not only with rstanarm so it's happening somewhere in the bayesplot code.

**Comment by jgabry** [comment]
On second thought, @bgoodri are you sure this isn't just an artifact of the draws from the different modes coming from different chains (the pairs plot might be right in that case)?

**Comment by jgabry** [comment]
That is, the default of `mcmc_pairs` is bayesplot is to show different chains below and above the diagonal, as opposed to splitting by accept_stat, or whatever the default of pairs.stanfit used to be.

**Comment by jgabry** [comment]
I'm pretty sure I'm right about this and there's no bug. If you're referring to this example: 

```r
post3 <- stan_nlmer(conc ~ SSfol(Dose, Time, lKe, lKa, lCl) ~ 
                    (0 + lKe + lKa + lCl | Subject), data = Theoph,
                    chains = CHAINS, cores = CORES, seed = SEED, 
                    QR = TRUE, init_r = 0.25, adapt_delta = 0.999)
```

Then instead of  
```r
pairs(post3, regex_pars = "^l")
```
which splits by chain try 
```r
pairs(post3, regex_pars = "^l", condition = pairs_condition(nuts = "accept_stat__"))
```
and it looks ok.

**Comment by bgoodri** [comment]
Splitting by chain is not a good default. It is only good for visualizing
if the chains have converged to the same distribution, which is rare
compared to the case of having divergences.

**Comment by jgabry** [comment]
Well for bayesplot it has to default to something that doesn't require NUTS stuff and I thought it would be too confusing to have the defaults different between bayesplot and rstanarm. But if you want we can make the default to split by accept_stat__ for rstanarm. But then for `bayesplot::mcmc_pairs` what should the default be?

**Comment by bgoodri** [comment]
I think it should be the same as in pairs.stanfit.

**Comment by jgabry** [comment]
But `pairs.stanfit` defaults to something only valid if the user has `accept_stat__` info. The mcmc_pairs function in bayesplot doesn't assume the user has that information. So the rstanarm `pairs.stanreg` wrapper for `bayesplot::mcmc_pairs` can be changed to default to splitting by `accept_stat__` but how can the underlying `mcmc_pairs` function in bayesplot default to that?

**Comment by bgoodri** [comment]
I don't think bayesplot::mcmc_pairs has to default to that.

**Comment by jgabry** [comment]
Ok I just changed the default for pairs.stanreg to accept_stat in 29ffc72a192db22d630b884ed1472aefbc295f27. I think that resolves this issue.
