### ISSUE TITLE
demos

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#21]
With either `devtools::source_url` or just `source` in the latest version of `R`, it is fairly easy to do many of the example-models via rstanarm with the following code idiom
```
{
source("https://raw.githubusercontent.com/stan-dev/example-models/*.data.R", local = TRUE)
stan_foo(formula, data = environment(), ...)
}
```
However, since this requires an internet connection, it cannot be part of `R CMD check` but I think it would be good to make many demos that do this using best practices (from https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-subdirectories ): 

The demo subdirectory is for R scripts (for running via demo()) that demonstrate some of the functionality of the package. Demos may be interactive and are not checked automatically, so if testing is desired use code in the tests directory to achieve this. The script files must start with a (lower or upper case) letter and have one of the extensions .R or .r. If present, the demo subdirectory should also have a 00Index file with one line for each demo, giving its name and a description separated by a tab or at least three spaces. (This index file is not generated automatically.)

**Comment by bgoodri** [comment]
Also, we can replicate existing demos such as
https://svn.r-project.org/R/trunk/src/library/stats/demo/lm.glm.R

**Comment by bob-carpenter** [comment]
On a related tangent, there are demos like BUGS and others to organize and I'm still not sure what to use among

* built-in R commands (this issue)
* knitr docs (related?)
* Jupyter notebooks (related?)

**Comment by bgoodri** [comment]
The Jupyter notebooks will render on GitHub

https://github.com/blog/1995-github-jupyter-notebooks-3

so that is a strong reason to prefer Jupyter in that context

Conversely, knitr-generated HTML documents render on CRAN, which is one
reason why we are using them for vignettes in rstanarm.

If we want example-models to run for all interfaces, then we need *.data.R
files to correspond to each .stan file (although some of the data.R files
are generated by another .R file). A big problem with example-models
currently is that there is often one data.R file for several .stan files
and only one of them runs in rstan::stan_demo() because it looks for a data
file with the same name as the .stan file and just switches the extension
to .data.R. I don't think it would hurt to also have knitr files or Jupyter
notebooks in example-models but that would be a big undertaking.

**Comment by bgoodri** [comment]
I made a `demo` for ARM chapter 03 with 3cd6426b698849ae4a93dee6d37cdab748c73a34

**Comment by jgabry** [comment]
Cool, good idea
