### ISSUE TITLE
some betareg tests failing

### ISSUE THREAD

**Issue by imadmali** [stan-dev/rstanarm#212]
Some of the betareg tests are failing. Specifically the tests [here](https://github.com/stan-dev/rstanarm/blob/master/tests/testthat/test_stan_betareg.R#L80-L113) that model `phi` as a scalar. @bgoodri @jgabry can either of you confirm this to make sure it's not something specific to my machine?

**Comment by jgabry** [comment]
Are you testing using the master branch? They seem to pass for me, at least when I run them interactively. I also ran R CMD check yesterday and didn't get any failures. What are the failure/error messages you're getting?

**Comment by imadmali** [comment]
Just checked now and they passed once I updated master. Apparently running them off of commit 356a112 caused them to fail (they were `expect_equal` failures). I guess this raises the issue that we should probably make sure all the tests pass before pushing to master.
