### ISSUE TITLE
Code not evaluated in vignette in new online docs?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#217]
@imadmali In the website created via pkgdown  for some reason it looks like the code in the hierarchical partial pooling vignette isn't being evaluated or, if it is, output is not being displayed (no plots, nothing printed, etc):

http://mc-stan.org/rstanarm/articles/pooling.html

The other vignettes look ok. Any idea why this would happen?

**Comment by imadmali** [comment]
@jgabry maybe it has something to do with my machine. Did you try rending the html and seeing what the site looks like locally?

**Comment by jgabry** [comment]
I'll give that a try, thanks
