### ISSUE TITLE
What is "family==3" in count.stan?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#219]
https://github.com/stan-dev/rstanarm/blob/bb5ade23e4449f144604c187341849f408190942/exec/count.stan#L78-L82

@bgoodri As far as I know `count.stan` only fits poisson and negative binomial models. But there are a bunch of references to family==3 throughout the file even though I don't see how family could possibly ever take on the value 3 (only 1 or 2 is passed in from R in `stan_glm.fit`). None of this seems to be documented or commented on anywhere and it makes `count.stan` pretty confusing to read. Can you enlighten me so I can either add comments to the Stan file to explain it or remove all that code if it's no longer used?

**Comment by imadmali** [comment]
@bgoodri are there plans to make this callable?
Also, does it have to captured by `family == 3` or can we just use `family == 1` (poisson in count.stan) and have a `prior_aux` argument in the stan_glm call?

**Comment by bgoodri** [comment]
Originally, I had it in for testing because using the negative binomial
distribution directly is sort of flaky. Either way, I don't think we should
expose it unless we identify a situation where it works better than family
= 2.

**Comment by jgabry** [comment]
Ok thanks for clarifying. I agree we shouldn't expose it if it doesn't do
better than family=2.
