### ISSUE TITLE
stan_plot cannot exclude "log-posterior"

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#22]
`stan_plot(*, pars = "log-posterior", include = FALSE)` does not actually exclude the log-posterior from the plot
`stan_plot(*, pars = "lp__", include = FALSE)` does, so I assume it is just a naming thing?

**Comment by jgabry** [comment]
Yes, I've been meaning to fix that. It's just a naming thing.

**Comment by bgoodri** [comment]
Actually, I would say that `lp__` should be excluded by default if that is easy to do.

**Comment by jgabry** [comment]
Yup

**Comment by jgabry** [comment]
I have this fixed now in locally in rstan. Should I just push to rstan
develop?

**Comment by bgoodri** [comment]
Yes

**Comment by jgabry** [comment]
Ok lp__ excluded by default now
