### ISSUE TITLE
Can we use `beta_fam` instead of `mgcv::betar`? And other related issues.

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#220]
@bgoodri I was doing some refactoring in `stan_glm.fit` and noticed a "Beta regression" family that has nothing to do with `stan_betareg`.  I tracked down that this is related to supporting `mgcv::betar`, but I can't find anywhere that this is documented in rstanarm. So the doc for the `family` argument to the modeling functions like stan_glm,stan_glmer,stan_gamm4, is wrong now. 

1. Do we really need to introduce a new family when we already have the `beta_fam` (and `beta_phi_fam`) that @imadmali already created? 

2. Why do we even have a `stan_betareg` function if Beta regression is now supported in `stan_glm` and other functions? This is super confusing, especially since the difference between doing Beta regression with `stan_glm` vs. doing it with `stan_betareg` is not explained anywhere.  

3. I think the package is getting too complicated to introduce things like a new family without a pull request (so there can be comments and so we have a better record of why something was implemented the way it was) and without any documentation. Otherwise it's just too hard to figure out how it's supposed to behave (not just for the users but for me when I'm making sure that refactoring doesn't break something you've added).

**Comment by bgoodri** [comment]
There was an issue about using splines and group-specific terms with a beta
regression, which that commit fixed. The stan_betareg function allows you
to do a GLM for the auxiliary parameter, but if you are just using a
constant for it, then it is often better to use splines and / or
group-specific terms for the conditional mean.

**Comment by jgabry** [comment]
Hmmm, ok. It definitely won't be clear to users when they should use `stan_betareg` and when they shouldn't unless there are recommendations. If `stan_betareg` is now only really useful when there's a model for phi then we should discourage people from using it in the documentation or only allow it to be used when there's a model for phi or something. 

Also, could this new functionality be done using the same family objects/function (`beta_fam`) that @imadmali created for `stan_betareg`? Or could we could replace `beta_fam` with this new one you added? Either way I think it would be preferable to only have one way to specify the `family` argument for beta regression models and we could avoid having to copy lines like
```r
if (family$family == "Beta regression") family$family <- "beta"
```
into three or four different files now, along with some other code that wouldn't be necessary to maintain if we didn't have multiple ways of specifying beta families.

**Comment by bgoodri** [comment]
This got figured out
