### ISSUE TITLE
ibgfortran.so.3: cannot open shared object file on Fedora 26

### ISSUE THREAD

**Issue by skeydan** [stan-dev/rstanarm#225]
Hi,

I'd love to use rstanarm, but cannot install it on Fedora 26 because Fedora 26 has switched to libgfortran 4 instead of libgfortran 3:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/key/R/x86_64-redhat-linux-gnu-library/3.4/minqa/libs/minqa.so':
  libgfortran.so.3: cannot open shared object file: No such file or directory
ERROR: lazy loading failed for package ‘rstanarm’

Unfortunately, I cannot install both versions 3 and 4 of libquadmath, required by libfortran:

[key@key Downloads]$ sudo dnf install libgfortran-6.4.1-1.fc25.i686.rpm
 Problem: conflicting requests
  - nothing provides libquadmath = 6.4.1-1.fc25 needed by libgfortran-6.4.1-1.fc25.i686

[key@key Downloads]$ sudo dnf install libquadmath-6.4.1-1.fc25.i686.rpm
Error: Transaction check error:
  file /usr/share/info/libquadmath.info.gz from install of libquadmath-6.4.1-1.fc25.i686 conflicts with file from package libquadmath-7.1.1-3.fc26.x86_64

Would you have an idea what I could do?

Thank you very much in advance!
Sigrid

**Comment by bgoodri** [comment]
The rstanarm package does not use Fortran, so I think you are referring to
the loading of lmer on which rstanarm depends. Can you confirm that just
doing library(lmer) throws the same error?

**Comment by skeydan** [comment]
Oops, I'm sorry. Thanks for your response, which made me check if I had a package "lmer", which I don't have, but then I thought that from the above error message I should try reinstalling "minqa" (which probably was installed before the upgrade to Fedora t6 and still linked to libgfortran 3).

Now it works, thank you very much!!

**Comment by vasutweaks** [comment]
I work on a software named pyferret which needs `libgfortran.so.3`. I am running fedora 27 whose package manager installs gfortran 7 (A higher version) by default. This produces the shared object `libgfortran.so.4` in `/usr/lib64`. Another Linux system running Ubuntu 16.04.3, however has `libgfortran.so.3`. I copied it to my system in ~/pkgs/libs and ran the application as

    export LD_PRELOAD=/home/vasu/pkgs/libs/libgfortran.so.3:/home/vasu/pkgs/libs/libopenblas.so.0;pyferret

This worked without the above error.
