### ISSUE TITLE
plot_nonlinear error when smoothing "by" a categorical variable

### ISSUE THREAD

**Issue by matthewbranan** [stan-dev/rstanarm#226]
#### Summary:
The plot_nonlinear() function fails with an error when running on a stan_gamm4() object when applying a smooth "by" a categorical variable.

#### Reproducible Steps:
I had been running a model on some data for a project, but the error was reproducible on the roaches sample dataset as well.

##### Running without "by" works fine:
    library(rstanarm)
    data(roaches)
    roaches$roach1 <- roaches$roach1 / 100
    roaches$new_classvar <- as.factor(sample(letters[1:3], nrow(roaches), replace = TRUE))
    post <- stan_gamm4(y ~ s(roach1), 
                   data = roaches, family = neg_binomial_2
                   chains = 2, cores = 2, seed = 2017)
    plot_nonlinear(post)

##### Running with the "by" returns an error:
    library(rstanarm)
    data(roaches)
    roaches$roach1 <- roaches$roach1 / 100
    roaches$new_classvar <- as.factor(sample(letters[1:3], nrow(roaches), replace = TRUE))
    post <- stan_gamm4(y ~ s(roach1, by = new_classvar), 
                   data = roaches, family = neg_binomial_2,
                   chains = 2, cores = 2, seed = 2017)
    plot_nonlinear(post)

> plot_nonlinear(post)
Error in `[.data.frame`(original, , xnames[term]) : 
  undefined columns selected`

#### Description:
The error returned is: 

> plot_nonlinear(post)
Error in `[.data.frame`(original, , xnames[term]) : 
  undefined columns selected`

And can be traced to the df_list() function within plot_nonlinear():

>df_list <- lapply(labels, FUN = function(term) {
        incl <- grepl(term, colnames(B), fixed = TRUE)
        xz <- XZ[, incl, drop = FALSE]
        b <- B[, incl, drop = FALSE]
        **x <- original[, xnames[term]]**
        xz <- xz[order(x), , drop = FALSE]
        f <- linear_predictor.matrix(b, xz)
        data.frame(predictor = sort(x), lower = apply(f, 2, quantile, 
            probs = (1 - prob)/2), upper = apply(f, 2, quantile, 
            probs = prob + (1 - prob)/2), middle = apply(f, 2, 
            median), term = term)
    })

When "by" is specified in the smooth term  **xnames** tries to access columns from **original** that don't exist because the "by" argument causes the glmod smooths labels to be inconsistent. 

##### Without the "by", **original** subsetting works fine

    Browse[3]> head(original, n = 1)
>    y roach1 g        Xr.1        Xr.2        Xr.3        Xr.4        Xr.5
1 153   3.08 1  0.04270320 -0.03358483  0.20409863 -0.04612162 -0.07849912
         Xr.6        Xr.7        Xr.8 y.0 X.(Intercept) X.s(roach1)Fx1
1 -0.75375383  0.46185929 -0.85133414 153       1.00000        3.53851

(Sorry, this ^ looks like a mess. Every other line, starting with the first, are the column names and the rest of the lines are values from the first row of **original**)

    Browse[3]> names(original)
>[1] "y"      "roach1" "g"      "Xr"     "y.0"    "X"     

(The names of **original**, notice there is a column named "roach")

    Browse[3]> xnames
>s(roach1) 
 "roach1" 

(And this is exactly the term **xnames** is looking for)

##### With the "by", **original** looks funny

    Browse[1]> head(original, n = 1)
>    y treatment roach1 new_classvar g Xr.1 Xr.2 Xr.3 Xr.4 Xr.5 Xr.6 Xr.7
1 153         1   3.08            c 1    0    0    0    0    0    0    0
  Xr.8 g.0 Xr.0.1 Xr.0.2 Xr.0.3 Xr.0.4 Xr.0.5 Xr.0.6 Xr.0.7 Xr.0.8 g.1
1    0   1      0      0      0      0      0      0      0      0   1
       Xr.1.1      Xr.1.2      Xr.1.3      Xr.1.4      Xr.1.5      Xr.1.6
1  0.04270320 -0.03358483  0.20409863 -0.04612162 -0.07849912 -0.75375383
       Xr.1.7      Xr.1.8 y.0 X.(Intercept) X.treatment
1  0.46185929 -0.85133414 153       1.00000     1.00000
  X.s(roach1):new_classvaraFx1 X.s(roach1):new_classvarbFx1
1                      0.00000                      0.00000
  X.s(roach1):new_classvarcFx1
1                      3.53851

(Sorry, this ^ looks like a mess. Every other line, starting with the first, are the column names and the rest of the lines are values from the first row of **original**)

    Browse[1]> names(original)
 >[1] "y"            "treatment"    "roach1"       "new_classvar"
 [5] "g"            "Xr"           "g.0"          "Xr.0"        
 [9] "g.1"          "Xr.1"         "y.0"          "X" 

(Notice that not all the columns shown when running head() are named here)
  
    Browse[1]> xnames
>s(roach1):new_classvara s(roach1):new_classvarb s(roach1):new_classvarc 
  "roach1new_classvara"   "roach1new_classvarb"   "roach1new_classvarc"

(These are the names **original[, xnames[term]]** is trying to access, but **original** has no columns with these names)

I'm not sure how to fit it, personally, but hopefully this code helps. If I'm missing something obvious and this isn't a bug, my apologies.

#### RStanARM Version:
2.15.3

#### R Version:
3.4.1

#### Operating System:
Both OSX 10.11.6 and Windows 7

**Comment by bgoodri** [comment]
I think this was fixed on GitHub. Can you try it after doing a

devtools::install_github("stan-dev/rstanarm", args = "--preclean",
build_vignettes = FALSE)

**Comment by matthewbranan** [comment]
That works, you guys are on top of it, thank you Ben and team!
