### ISSUE TITLE
rstanarm+kfold add groupby option

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#228]
#### Summary:
Let's say we have a model
`fit1<-stan_glmer(Un~ Entrenchment + (1 + Entrenchment |PID), data=BOTH)`
Add option to call
(kfold1 <- kfold(fit1, groupby = PID))
where PID is some variable in data (or variable in environment?)

This would make it easier to make leave-one-group-out cross-validation

**Comment by avehtari** [comment]
I'm still learning R, and I don't know yet how to handle option function arguments, but assuming that we would have
```
kfold <- function(x, K = 10, save_fits = FALSE, groupby = NULL) {
```
then if groupby is not NULL, we would have
```
groupbyvalues<-d[[groupby]]
groupbyuniquevalues<-unique(groupbyvalues)
K<-length(groupbyuniquevalues)
message(groupbyname, " has ", K, " unique values")
for (k in 1:K) {
    message("Fitting model ", k, " out of ", K)
    omitted <- which(groupbyvalues == groupbyuniquevalues[k])
    ...
```
To add this to kfold-function would require argument checking: K vs. groupby and that groupby is valid column name in data. Although right now I realized that it would be good to allow groupby to be also an array. We could check that if groupby is a string, then do as above and if it's already an array then just skip the assignment `groupbyvalues<-d[[groupby]]`

@jgabry what do you think?

**Comment by jgabry** [comment]
Aki also suggests having an option to allow user to pass in a vector of indexes that indicate to which fold each data point belongs.

**Comment by jgabry** [comment]
@avehtari How about a `folds` argument that works like this:

```r
library(rstanarm)
library(loo)
fit <- stan_lmer(mpg ~ disp + (1|cyl:gear), data = mtcars, adapt_delta = 0.99)

# use kfold helper to split by cyl
table(mtcars$cyl)
folds_cyl <- kfold_split_stratified(K = 3, x = mtcars$cyl)
table(cyl = mtcars$cyl, fold = folds_cyl)

# requires 'kfold-options' branch
kfold_cyl <- kfold(fit, K = 3, folds = folds_cyl) 
```

**Comment by avehtari** [comment]
Looks good

**Comment by jgabry** [comment]
@avehtari I haven’t done thorough testing on this but since the loo k-fold
helpers are going to be released I guess we could release this in rstanarm
as an “experimental” feature if you want. Otherwise we can wait until the
next release.

**Comment by jgabry** [comment]
Actually I had a chance to do some more testing
