### ISSUE TITLE
Bug in calculating density of MVN on sambrilleman-master branch

### ISSUE THREAD

**Issue by sambrilleman** [stan-dev/rstanarm#229]
#### Summary:
Just noting a small, but serious, bug [here](https://github.com/stan-dev/rstanarm/blob/sambrilleman-master/R/log_lik.R#L600) on the sambrilleman-master branch.

#### Description:
There are brackets missing around the entire term after the -0.5 multiplier. It should be 

-0.5 * **[** c(determinant(Sigma, logarithm = TRUE)$modulus) + 
             (b %*% chol2inv(chol(Sigma)) %*% b)[1] + length(b) * log(2 * pi) **]**

not

-0.5 * c(determinant(Sigma, logarithm = TRUE)$modulus) + 
             (b %*% chol2inv(chol(Sigma)) %*% b)[1] + length(b) * log(2 * pi)

#### Reproducible Steps:
n/a

#### RStanARM Version:
n/a

#### R Version:
n/a

#### Operating System:
n/a

**Comment by bgoodri** [comment]
@sambrilleman This was fixed somewhere in the merge, right?

**Comment by sambrilleman** [comment]
Yep, seems to be ok [here](https://github.com/stan-dev/rstanarm/blob/master/R/log_lik.R#L610), so I'll close this issue.
