### ISSUE TITLE
rstanarm::stan_glm() error in model with no intercept

### ISSUE THREAD

**Issue by bgall** [stan-dev/rstanarm#233]
#### Summary:

Linear regression with no intercept throws error to be reported to maintainer in stan_glm() 

#### Description:

Error from running the code in 'reproducible steps' while fitting a model with no intercept and default priors:

Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  no valid constructor available for the argument list
trying deprecated constructor; please alert package maintainer

#### Reproducible Steps:

```
# Preliminaries
library(rstanarm)
set.seed(1)

# Generate fake data
w1 <- rbeta(n = 50, shape1 = 2, shape2 = 1.5)
w2 <- rbeta(n = 50, shape1 = 3, shape2 = 2.5)

dat <- data.frame(y = log(w1 / (1-w1)),
                  x = log(w2 / (1-w2)),
                  z = seq(1:50))

# Fit linear regression without an intercept:
# throws an error
m1 <- rstanarm::stan_glm(y ~ 0 + w1 + w2, 
                         data = dat,
                         family = gaussian(),
                         algorithm = "sampling")

# Same error when specifying intercept differently
m2 <- rstanarm::stan_glm(y ~ -1 + w1 + w2, 
                         data = dat,
                         family = gaussian(),
                         algorithm = "sampling")
```

#### RStanARM Version:

2.15.3

#### R Version:

3.4.1

#### Operating System:

Windows 10

**Comment by bgoodri** [comment]
Don't worry about that. It finds a viable constructor and runs, with or without the intercept. That message will go away on the next upload of **rstanarm** to CRAN.
