### ISSUE TITLE
glFormula error 

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#24]
@bgoodri I just triggered an error I didn't know about in `glFormula`. Apparently it won't allow a model with more random effects than observations because "the random-effects parameters are probably unidentifiable." That's a reasonable concern for `glmer`, but for `stan_glmer` this will rule out many models (like a lot of the ones Andrew fits) for which it's possible to overcome this with informative priors.

**Comment by bgoodri** [comment]
OK. My guess is that we just have to live with that for now. Maybe we can
later convince the lme4 maintainer to throw that error when the model is
estimated rather than when the formula is parsed.

**Comment by jgabry** [comment]
Yeah I don't see how we could get around it on our end if we're going to
keep using glFormula, so maybe they would be amenable to making that
change. We can just accept the limitation for now. Any reason I
shouldn't post an issue at the lme4 repo now and get the ball rolling?

**Comment by jknowles** [comment]
I'm just a lurker anticipating the release of this package, but I came across a similar issue in my own package `merTools`. I'm not sure our solution would work here because I'm unfamiliar with your specific goals for `glFormula`, but we constructed the model.matrix using the following:

```r
matrixForm <- formulaBuild(merMod)
modelMatrix <- model.matrix(matrixForm, data = data)
```

You can still flag the DV after using `formulaBuild` but I'm not sure it does everything else you need it to do. I just know that you can parse the formula without worrying about triggering the `glmer` checks you reference above, because our application is constructing a model.matrix from a subset of data for the purposes of prediction, so we had to work around cases where there were very few rows (a user predicting one row of data) and many random effects (on a complex model).

**Comment by bgoodri** [comment]
I don't think it would hurt anything to wait until rstanarm is released so
that they can see how to replicate the issue and why a Bayesian approach
makes the issue relevant. The `sigma` thing is more pressing I think.

**Comment by jgabry** [comment]
@jknowles Thanks for the suggestion. I'll take a look at `formulaBuild` and see if it would be useful here.

**Comment by jgabry** [comment]
@jknowles Do you guys have something in merTools similar to the `formulaBuild` / `model.matrix` combination from above but that can be used to create the Z matrix (for the random effects terms) without triggering glFormula warnings?

**Comment by jknowles** [comment]
Not something that elegant. Are you looking for a matrix that has all the Z effects (if multiple group levels are involved) in one flat matrix? We do something with arrays to stack them up, but I think I could work it out to be flat.

**Comment by jgabry** [comment]
Thanks Jared. Actually, what we want the Z matrix for is for doing
posterior predictive simulations. For example, if someone fits a model like

stan_lmer(mpg ~ wt + (1|cyl), data = mtcars)

and then wants to generate from the posterior predictive distribution with
something like

newdata = data.frame(wt = 2, cyl = 3)

then I wanted to use glFormula using the original formula and newdata,
but we can't use glFormula on this newdata to get the Z matrix because it
will complain that cyl has only one level.

For a simple formula like the one in this example it's not hard to create
Z, but we haven't found a good way to automate the creation of Z for
newdata when the formulas get more complicated with multiple varying
intercepts and slopes.

**Comment by bgoodri** [comment]
Can we add rows to newdata in order to make the grouping factors have more
than one level, parse it with lme4::glFormula, and then drop the added rows
from X and Z?

**Comment by jknowles** [comment]
I think how we do it in merTools might work for you. It is pretty robust and it makes an array of the linear combination of the prediction from all of the Z terms:

This loops through all of the group levels in a `merMod` and constructs a sampled distribution by sampling the posterior of the random effects of the `merMod` object. It creates an array that is multiplied by `newdata` and it only samples the posterior for random effect terms that match between `newdata` and the `merMod` object. It's really the core of the `predictInterval` function in `merTools`. 

```r
re.xb <- vector(getME(merMod, "n_rfacs"), mode = "list")
  names(re.xb) <- names(ngrps(merMod))
    for(j in names(re.xb)){
    reMeans <- as.matrix(ranef(merMod)[[j]])
    reMatrix <- attr(ranef(merMod, condVar=TRUE)[[j]], which = "postVar")
    # OK, let's knock out all the random effects we don't need
    obslvl <- unique(as.character(newdata[, j]))
    alllvl <- rownames(reMeans)
    keep <- intersect(obslvl, alllvl)
    # Add switch if no random groups are observed to avoid indexing errors,
    # we burn 1 sample of 1 group of all coefficients that will eventually
    # be multiplied by zero later on
    if(length(keep) > 0){
      reMeans <- reMeans[keep, , drop=FALSE]
      dimnames(reMatrix)[[3]] <- alllvl
      reMatrix <- reMatrix[, , keep, drop = FALSE]
    } else{
      reMeans <- reMeans[1, , drop=FALSE]
      reMatrix <- reMatrix[, , 1, drop = FALSE]
    }
    #
    reSimA <- array(data = NA, dim = c(nrow(reMeans), ncol(reMeans), n.sims))
    for(k in 1:nrow(reMeans)){
      meanTmp <- as.matrix(reMeans[k, ])
      matrixTmp <- as.matrix(reMatrix[,,k])
      reSimA[k, ,] <- mvtnorm::rmvnorm(n.sims,
                                       mean=meanTmp,
                                       sigma=matrixTmp,
                                       method="svd")
      rownames(reSimA) <- rownames(reMeans)
      colnames(reSimA) <- colnames(reMeans)
    }
     tmp <- cbind(as.data.frame(newdata.modelMatrix), var = newdata[, j])
     keep <- names(tmp)[names(tmp) %in% dimnames(reSimA)[[2]]]
     tmp <- tmp[, c(keep, "var"), drop = FALSE]
     tmp[, "var"] <- as.character(tmp[, "var"])
     colnames(tmp)[which(names(tmp) == "var")] <- names(newdata[, j,  drop=FALSE])
     tmpCoef <- reSimA[, keep, , drop = FALSE]
     tmp.pred <- function(data, coefs, group){
       yhatTmp <- array(data = NA, dim = c(nrow(data), ncol(data)-1, dim(coefs)[3]))
   new.levels <- unique(as.character(data[, group])[!as.character(data[, group]) %in% dimnames(coefs)[[1]]])
       msg <- paste("     The following levels of ", group, " from newdata \n -- ", paste0(new.levels, collapse=", "),
                    " -- are not in the model data. \n     Currently, predictions for these values are based only on the \n fixed coefficients and the observation-level error.", sep="")
       if(length(new.levels > 0)){
         warning(msg, call.=FALSE)
       }
       for(k in 1:ncol(data)-1){
         for(i in 1:nrow(data)){
           lvl <- as.character(data[, group][i])
           if(lvl %in% dimnames(coefs)[[1]]){
             yhatTmp[i, k,] <- as.numeric(data[i, k]) * as.numeric(coefs[lvl, k, ])
           } else{
             yhatTmp[i, k,] <- as.numeric(data[i, k]) * 0
           }

         }
       }
       return(yhatTmp)
     }
     re.xb[[j]] <- apply(tmp.pred(data = tmp, coefs = tmpCoef,
                                  group = names(newdata[, j, drop=FALSE])), c(1,3), sum)
  }

```

**Comment by jgabry** [comment]
Thanks Jared, much appreciated. I'll see if I can make this work with what
we have without too much trouble. If not I think I have an alternative
idea.

@bgoodri I'm working on this now. We can't just add some generic extra rows
and remove them because we'll want each level of each of the grouping
variables to get its own column in Z (even if those columns are just zeros
because newdata contains just one or a subset of the levels) and glFormula
won't do this unless all levels are in newdata. But I think we _might_ be
able to get around this by just rbinding newdata and the original model
frame. Then we use glFormula on this augmented dataset and then remove the
rows corresponding to the original model frame from the resulting X and Z.
Does that make sense?

**Comment by bgoodri** [comment]
On Thu, Sep 24, 2015 at 2:12 PM, Jonah Gabry <notifications@github.com>
wrote:

> Does that make sense?
>

Yes, it is probably easiest to rbind the whole original dataset than to
figure out what subset of the levels needs to be added.

**Comment by bgoodri** [comment]
The original problem with parsing 8 schools type models can be circumvented by specifying 
```
control = [g]lmerControl(check.nobs.vs.nlev  = "ignore",  check.nobs.vs.nRE = "ignore")
```
in the call to `stan_[g]lmer`.

**Comment by jgabry** [comment]
Cool. Should we default to this or have the user specify it?

**Comment by bgoodri** [comment]
I think there is nothing in the `control` list that `lmer()` and `glmer()` accepts that is relevant to us, but it is difficult if the user passes it because `control` is also an argument to `sampling`. So, I think we have to interpret a list named `control` in the ... as being intended for `sampling` and pass an internal list named control to `glFormula` that turns off all its checks.

**Comment by jgabry** [comment]
Yeah I think doing it internally is fine. We could add an argument allowing
users to toggle it, but it would probably never be necessary to turn it
off.

**Comment by bgoodri** [comment]
I've hard-coded that in 64b289a .
