### ISSUE TITLE
R2 for multiple regression

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#240]
#### Summary:
How to compute R2 (explained variance) for multiple regression model.

#### Description:
I've read your [paper](http://www.stat.columbia.edu/~gelman/research/unpublished/bayes_R2.pdf) on R2 computation. However, your function doesn't work for multiple regression (the error message is ` Error: The 'R2' function only accepts a single value for 'location', which applies to the prior R^2. If you are trying to put different priors on different coefficients rather than specify a joint prior via 'R2', you can use stan_glm which accepts a wider variety of priors, many of which allow specifying arguments as vectors. `. 

I can compute an R2 distribution using `stlan_lm` and setting an R2 prior. However, I can't use it (as I have no R2 prior and don't know how to a set a uninformative prior). 

Is there a way to compute R2 (or adjusted R2) on multiple regression models?

#### Reproducible Steps:
```R
bayes_R2 <- function(fit) {
  y <- get_y(fit)
  ypred <- posterior_linpred(fit, transform = TRUE)
  if (family(fit)$family == "binomial" && NCOL(y) == 2) {
    trials <- rowSums(y)
    y <- y[, 1]
    ypred <- ypred %*% diag(trials)
  }
  e <- -1 * sweep(ypred, 2, y)
  var_ypred <- apply(ypred, 1, var)
  var_e <- apply(e, 1, var)
  var_ypred / (var_ypred + var_e)
}


data <- normalize(datasets::attitude)
fit <- rstanarm::stan_glm(rating ~ advance + privileges + learning + raises,
                         data=data, prior=normal(0, 1))
bayes_R2(fit)  # this errors


fit <- rstanarm::stan_lm(rating ~ advance + privileges + learning + raises,
                          data=data, prior=R2(0.5))
fit
```

**Comment by bgoodri** [comment]
You have to do

library(rstanarm)

to access get_y, posterior_linpred, etc.

**Comment by DominiqueMakowski** [comment]
Here's the modified code that produces the same error:

```R
library(rstanarm)

bayes_R2 <- function(fit) {
  y <- rstanarm::get_y(fit)
  ypred <- rstanarm::posterior_linpred(fit, transform = TRUE)
  if (family(fit)$family == "binomial" && NCOL(y) == 2) {
    trials <- rowSums(y)
    y <- y[, 1]
    ypred <- ypred %*% diag(trials)
  }
  e <- -1 * sweep(ypred, 2, y)
  var_ypred <- apply(ypred, 1, var)
  var_e <- apply(e, 1, var)
  var_ypred / (var_ypred + var_e)
}


data <- normalize(datasets::attitude)
fit <- rstanarm::stan_glm(rating ~ advance + privileges + learning + raises,
                         data=data, prior=normal(0, 1))
bayes_R2(fit)  # this errors


fit <- rstanarm::stan_lm(rating ~ advance + privileges + learning + raises,
                          data=data, prior=R2(0.5))  # This works but I can't use this
```

**Comment by bgoodri** [comment]
I don't get an error. What is the error message you see?

**Comment by DominiqueMakowski** [comment]
```R
library(rstanarm)
bayes_R2 <- function(fit) {
  y <- rstanarm::get_y(fit)
  ypred <- rstanarm::posterior_linpred(fit, transform = TRUE)
  if (family(fit)$family == "binomial" && NCOL(y) == 2) {
    trials <- rowSums(y)
    y <- y[, 1]
    ypred <- ypred %*% diag(trials)
  }
  e <- -1 * sweep(ypred, 2, y)
  var_ypred <- apply(ypred, 1, var)
  var_e <- apply(e, 1, var)
  var_ypred / (var_ypred + var_e)
}


data <- normalize(datasets::attitude)
fit <- rstanarm::stan_glm(rating ~ advance + privileges + learning + raises,
                         data=data, prior=normal(0, 1))
bayes_R2(fit)  # this errors
```

This returns:

`Error: The 'R2' function only accepts a single value for 'location', which applies to the prior R^2. If you are trying to put different priors on different coefficients rather than specify a joint prior via 'R2', you can use stan_glm which accepts a wider variety of priors, many of which allow specifying arguments as vectors. `

- R version 3.4.2 (2017-09-28)
- Platform: x86_64-w64-mingw32/x64 (64-bit)
- Running under: Windows >= 8 x64 (build 9200)
- rstanarm_2.15.3

**Comment by bgoodri** [comment]
But the bayes_R2() function is not even calling the R2() function. What
happens if you just paste the body of the bayes_R2() function into the
console?

**Comment by DominiqueMakowski** [comment]
@bgoodri I must had have something messed up, it works well on my other computer. Thanks for your answers, and your very useful work.
