### ISSUE TITLE
Cannot install development version on Windows

### ISSUE THREAD

**Issue by billdenney** [stan-dev/rstanarm#241]
When I try to install the development version of `rstanarm` on Windows 10 with R 3.4.1, I get an error:

```
** testing if installed package can be loaded
Error: package or namespace load failed for 'rstanarm' in .doLoadActions(where, attach):
 error in load action .__A__.1 for package rstanarm: is(module, "character"): object 'm' not found
```

Steps to reproduce:
```
library(devtools)
install_github("stan-dev/rstanarm")
```

**Comment by bgoodri** [comment]
Please see

https://github.com/stan-dev/rstanarm#development-version

in particular the `args = "--preclean"` part (which won't be necessary much
longer).

**Comment by billdenney** [comment]
That seems to have gotten me through.  Thanks!
