### ISSUE TITLE
Error in if (is.mer(x) && x$stan_function != "stan_gamm4")

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstanarm#244]
While investigating some differences between brms and rstanarm mentioned on brms-users by Travis Riddle (https://groups.google.com/forum/#!topic/brms-users/gj5-NvAUlEU), I loaded a stanreg object fitted with an old version of rstanarm and tried to summarize it using the newly released version 2.17.2, which resulted in

```R
> print(m.rstanarm)
Error in if (is.mer(x) && x$stan_function != "stan_gamm4") return(formula_mer(x,  : 
  missing value where TRUE/FALSE needed
```

I am almost sure having seen `x$stan_function != "stan_gamm4"` to be added in a recent commit of yours somewhere, but apparently, older stanreg object so not have a `stan_functions` slot. 

I am not sure where you store the version number with which the model was fitted, but you can download the model yourself here: https://drive.google.com/file/d/1qGYQOWb6zNaUDJbRzEsEan_YD35GSlRx/view

**Comment by hrlai** [comment]
Hi, I also encounter this error message after the updating rstanarm last Friday 29/12/2017.

I fitted stan models with rstanarm with an older version of rstanarm, but cannot print the same object with the newer rstanarm package.

**Comment by tjmahr** [comment]
Yup, I have the same issue. I had a model that took 24 hours to fit, so I'm loading it from an RDS file and can't `summary()` it anymore. This was a breaking code change. 😱 

Actually, wait, I can get it to work if I change my model...

```
model$stan_function <- "stan_glmer"
```

I would recommend getting the rstanarm function dynamically from `model$call[1]`. That would work with older models.

**Comment by bgoodri** [comment]
It is true that we didn't anticipate this breaking change, but it is also true that we don't really strive to make **rstanarm** completely backwards compatible.

**Comment by paul-buerkner** [comment]
Still, I think it would be nice if you fixed it in the next version, since it may frustrate quite a few users, who are not immediately aware how to fix it themselves.

**Comment by jgabry** [comment]
Working on the next release of rstanarm and going through open issue and just noticed I missed this issue before. I agree we should try to fix this somehow. Or at least throw an error telling people to manually add stan_function to their object.

@tjmahr that’s exactly what I initially did but scrapped it when I ran into the same thing you noticed.

**Comment by paul-buerkner** [comment]
just write isTRUE(x$stan_function != "stan_gamm4")

Jonah Gabry <notifications@github.com> schrieb am Do., 22. März 2018, 21:54:

**Comment by paul-buerkner** [comment]
or maybe better !isTRUE(x$stan_function == "stan_gamm4")

Paul Buerkner <paul.buerkner@gmail.com> schrieb am Do., 22. März 2018,
22:14:

**Comment by jgabry** [comment]
Or that, yeah. Thanks!

**Comment by jgabry** [comment]
Fixed using Paul's suggestion. Will be in the next release.
