### ISSUE TITLE
cannot install 2.17.12

### ISSUE THREAD

**Issue by lurch999** [stan-dev/rstanarm#245]
#### Summary:
In R version 3.4.2 I cannot install rstanarm
#### Description:
Trying to install rstanarm version 2.17.12 fails.
#### Reproducible Steps:
> install.packages('rstanarm')
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://ftp.osuosl.org/pub/cran/src/contrib/rstanarm_2.17.2.tar.gz'
Content type 'application/x-gzip' length 1995569 bytes (1.9 MB)
==================================================
downloaded 1.9 MB

* installing *source* package ‘rstanarm’ ...
** package ‘rstanarm’ successfully unpacked and MD5 sums checked
** libs
"/usr/lib64/R/bin/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/bernoulli.stan
Error: (converted from warning) S3 methods 'print.stanfit', 'as.array.stanfit', 'as.matrix.stanfit', 'as.data.frame.stanfit', 'is.array.stanfit', 'dim.stanfit', 'dimnames.stanfit', 'names.stanfit', 'names<-.stanfit', 'pairs.stanfit' were declared in NAMESPACE but not found
Execution halted
make: *** [stan_files/bernoulli.cc] Error 1
ERROR: compilation failed for package ‘rstanarm’
* removing ‘/usr/lib64/R/library/rstanarm’

The downloaded source packages are in
	‘/tmp/RtmpHsLJyi/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rstanarm") :
  installation of package ‘rstanarm’ had non-zero exit status

#### RStanARM Version:
2.17.12
#### R Version:
3.4.2

#### Operating System:
Centos 7

**Comment by bgoodri** [comment]
Are you using a make program that is not GNUmake? I know that we have that
problem, but I have not been able to replicate the error your are seeing.
Maybe try remove.packages("rstanarm") first.

**Comment by lurch999** [comment]
Thanks bgoodri, although I had removed the old rstanarm package already, what worked was removing rstan, then reinstalling both. All good now! Thanks again for sending me into the right direction...
