### ISSUE TITLE
stan_glmer "weights" bug

### ISSUE THREAD

**Issue by lhunsicker** [stan-dev/rstanarm#250]
#### Summary:
There is a bug in the handling of a "weights" parameter at line #22 of 
stan_glmer (and possibly in other rstanarm functions).

#### Description:
I found this while trying to use stan_glmer for an aggregated binomial mixed model analysis.  The following shows the results of an analysis of the "reedfrogs" data set from McElreath's rethinking package.  The first version of the call, using a two column matrix on the left of the model statement, works entirely correctly.  The second version, using a proportion on the left side of the model statement with a "weights" parameter abends with an error message saying that the "weights" variable has to be a numeric vector.  But in the call, "weights" is set to "density," which is indeed an integer vector.

The problem at line 22 of the program is that the statement:  
" weights <- validate_weights(weights)" 
doesn't find the value to which the "weights" parameter is set.  Rather it finds the base::weights() function, which, of course, is not a numerical vector.

I'm not sure that one needs a "proportion/weights" version of stan_glmer to run an aggregated binomial model.  I find the two column model left side much more obvious.  But it appears that some prefer the "proportion/weights" form, and the lme4::glmer() function documentation gives it as an alternative call.  In addition, I suspect that non-binomial models that try to use the weights parameter may also fail for the same reason.

Thanks for a very useful package!

#### Reproducible Steps:
library(rethinking)
data(reedfrogs)
d <- reedfrogs
d$tank <- 1:nrow(d)
sglmer <- stan_glmer(cbind(surv, density-surv) ~ 1 + (1|tank), 
            family = binomial, data = d) #  Works correctly.
sglmer1 <- stan_glmer(surv/density ~ 1 + (1|tank), weights = density, 
            family = binomial, data = d)
>  Error: 'weights' must be a numeric vector.

#### RStanARM Version:
The version of the rstanarm package you are running:  2.17.2

#### R Version:
The version of R you are running (e.g., from `getRversion()`):  3.4.3

#### Operating System:
Windows 10, Most current update

**Comment by jgabry** [comment]
Thanks for reporting this and for the reproducible example. We’ll get this
sorted out for the next release.

(I always use the 2-column format for binomial models but we tried to allow
for the weights version too.)

**Comment by jgabry** [comment]
Thanks again for reporting this. Fixed on github now and the fix will be in the upcoming release that we'll be submitting within the next few days.
