### ISSUE TITLE
beta regression vignette

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstanarm#251]
At the bottom of the vignette "Modeling Rates/Proportions using Beta Regression with rstanarm"

> 
> elpd_diff        se 
>      33.7       3.7 
> Evaluating the expected log predictive distribution using loo reveals that the second of the two models is slightly preferred. That said, in this case the standard error of the difference in elpd is large enough (relative to the difference itself) that we can’t say there is a definitive preference for the second model.
> 
> 

I don't understand the comment: elpd_diff is 10*se, no preference?

**Comment by jgabry** [comment]
Thanks for letting us know. That looks like we might have written that line for a different example and forgot to change it. But I'm not sure. @imadmali you wrote this vignette right? can you give this a look?

**Comment by jgabry** [comment]
Fixed in 9e0d788a7bdac7a2443c12d3aae670e4937b4237
