### ISSUE TITLE
rstanjm still alive

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstanarm#256]
The examples in the vignette "Estimating Joint Models for Longitudinal and Time-to-Event Data with rstanarm" by  Sam Brilleman use package https://github.com/sambrilleman/rstanjm, but the package does not build and has not been updated for a year.

Any outlook if this going to be part of rstanarm in the future? We wanted to give it a try, but would not waste time with it if it has been abandoned.

**Comment by bgoodri** [comment]
It is already in rstanarm on CRAN. There are actually two main functions
now: stan_jm and stan_mvmer.

**Comment by dmenne** [comment]
I had seen it, but was mislead by "to fit the model we use the main modelling function in the rstanjm package: stan_jm. " in the vignette. Maybe better remove it.

**Comment by sambrilleman** [comment]
Woops, sorry for the confusion. This is definitely just a copy and paste error, from the old vignette. I'll fix it.

More generally, I've just decided to make the rstanjm repo private. It was creating to much confusion I think (e.g. rstanjm was the first hit on google when you type in "bayesian joint models stan"). Hopefully, now the rstanarm stan_jm vignette will be the prominent search result.

**Comment by sambrilleman** [comment]
* The reference to rstanjm in the vignette has been removed, as per [this](https://github.com/stan-dev/rstanarm/commit/b6f1c9efbb6fb157c8135ab6ef208335d9a14381) commit

* The rstanjm repository is now private. 

* My rstanarm fork [here](https://github.com/sambrilleman/rstanarm) now has a big banner at the top of the README telling people the repo is inactive and redirecting them to stan-dev/rstanarm.
