### ISSUE TITLE
rstanarm changes ggplot2 theme at start-up

### ISSUE THREAD

**Issue by malcolmbarrett** [stan-dev/rstanarm#257]
Hi folks,

Firstly, thanks for the great package and all the hard work that's gone into it. It's really a treat to use.

`rstanarm` changes the `ggplot2` theme to `bayesplot::theme_default()` at start-up. I believe this is misguided, for two reasons:
1. It globally changes the `ggplot2` theme, even though I can say as an analyst, plots related to my model are only a subset of the plots that I am making. Obviously, this can just as easily be overriden by adding the `ggplot2` default theme to those plots, but I don't think the default of this package should  "break" the theme of other plots.
1. It's not really in the spirit of `ggplot2`'s layer-by-layer API; if you want the `bayesplot` theme, you should just add it, particularly since it's only a line of code, and otherwise leave it up to the user.

I do appreciate that `bayesplot` has a nice aesthetic, and that it's also nice to have a distinct look based on that for `rstanarm` to have, but I think this is the wrong way to go about it. I'm submitting a PR that removes the startup code and adds a quick function to set it. It also directly adds `bayesplot::theme_default()` to `plot.stanreg` and `pairs.stanreg`.

Thanks!
Malcolm

**Comment by jgabry** [comment]
Hey Malcolm, sorry again for the delay in responding. I keep thinking we need to change this but I haven't had a chance to get more into it yet. But my bayesplot coauthor @tjmahr has a proposal over at the bayesplot repo

https://github.com/stan-dev/bayesplot/issues/117

to change this functionality. It would be great to get your feedback on that proposal if you're still interested in helping out with this.
