### ISSUE TITLE
adding formula to loo::compare

### ISSUE THREAD

**Issue by Athanasiamo** [stan-dev/rstanarm#261]
Is it perhaps possible to add an option to add the formula for the model comparisons in the row names of as a column for the compare function? 

I don't know if others would find this valuable, but at least when I compare my models, I often find myself looking up their formulas when doing the comparisons, or when writing tables for publication, because it is informative for me and other readers to easily see the different models being compared.

**Comment by jgabry** [comment]
Thanks for the suggestion. Yeah, I think it's a good idea. Many formulas
would be too long to print but I guess that's ok if the default is to not
print them.

**Comment by jgabry** [comment]
Hey @Athanasiamo, instead of adding an additional column, which pretty much guarantees the output doesn't fit cleanly in  the console, I've started by implementing the following for the next release:

```r
compare_models(fit1, fit2, fit3, detail=TRUE)  # detail argument is new

Model formulas: 
  fit1:  mpg ~ wt
  fit2:  mpg ~ wt + cyl
  fit3:  mpg ~ wt + cyl + am

Model comparison (ordered by highest ELPD): 
     elpd_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
fit2   0.0     -78.4      4.6         3.9   1.2    156.7   9.2   
fit3  -1.2     -79.5      4.5         4.8   1.3    159.0   9.0   
fit1  -5.1     -83.4      4.3         3.2   1.1    166.8   8.6 
```

Is that what you had in mind (aside from making it a column vs printing before)?

**Comment by jgabry** [comment]
This is merged and will be in the next release (coming very soon!)

**Comment by Athanasiamo** [comment]
Hi @jgabry !

Thanks, I'm not too fuzzy about it fitting in the console really, but I understand that perhaps that is what most people would be interested in. And my models are likely less complex than a lot of people's.

I was looking for something to fit more nicely in a table for publication/supplementary materials. Something that would make it easy for reviewers to understand the the comparisons.

I think this solution would do what I want, easily.

How does this element look if assigned to a variable? If it is fairly easy to grab the table vs. the printed models, I think it definitely serves my purpose, as I could use the top part as a footnote. 

👍

**Comment by jgabry** [comment]
If `detail=TRUE` the formulas are all stored as a list in the `formulas` attribute of the returned object. If you want to make a data frame that has the formulas as a column you will be able to do it like this when the new release comes out:

```
comp <- compare_models(loo1, loo2, loo3, detail=TRUE)
print(comp, digits = 2)

print(comp)

Model formulas: 
  fit1:  mpg ~ wt
  fit2:  mpg ~ wt + cyl
  fit3:  mpg ~ disp * as.factor(cyl)

Model comparison: 
(ordered by highest ELPD)

     elpd_diff elpd_loo se_elpd_loo p_loo  se_p_loo looic  se_looic
fit3   0.00    -77.99     3.38        5.71   1.17   155.98   6.75  
fit2  -0.54    -78.53     4.61        4.08   1.26   157.07   9.21  
fit1  -5.56    -83.55     4.34        3.33   1.22   167.10   8.68  
```

```
# Make a data frame with formula column
comp_df <- data.frame(comp)
comp_df$formula <- as.character(attr(comp, "formulas"))
print(comp_df, digits = 2)

     elpd_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic                     formula
fit3      0.00      -78         3.4   5.7      1.2   156      6.8                    mpg ~ wt
fit2     -0.54      -79         4.6   4.1      1.3   157      9.2              mpg ~ wt + cyl
fit1     -5.56      -84         4.3   3.3      1.2   167      8.7 mpg ~ disp * as.factor(cyl)
```

**Comment by Athanasiamo** [comment]
yes @jgabry ! This is brilliant! Thank you so much for this extra feature!
