### ISSUE TITLE
kfold fails if formula is given as a string

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#262]
#### Summary:
A short summary (no more than a sentence or two).

kfold fails if formula is given as a string

#### Reproducible Steps:
```
n<-100
x <- array(rnorm(n), c(n,1))
y <- array(rnorm(n), c(n,1))
df <- data.frame(x=x, y=y)
fit <- stan_glm(x ~ y, data = df, seed=1, refresh=0)
k_fold <- kfold(fit, K = 4, save_fits = T)
fit2 <- stan_glm("x ~ y", data = df, seed=1, refresh=0)
k_fold2 <- kfold(fit2, K = 4, save_fits = T)
```
kfold for fit2 fails with an error
```
Error in formula(object)[[2L]] : subscript out of bounds
```

#### RStanARM Version:
2.17.3

#### R Version:
3.4.3

#### Operating System:
Ubuntu Linux 16.04.1

**Comment by jgabry** [comment]
Thanks Aki. Should be fixed on GitHub now.

**Comment by RNMahon** [comment]
Hello, 

I am running into the same issue:
k-fold is failing if the formula is provided as a string

Using the same repeatable steps code from above:
`n<-100
x <- array(rnorm(n), c(n,1))
y <- array(rnorm(n), c(n,1))
df <- data.frame(x=x, y=y)
fit <- stan_glm(x ~ y, data = df, seed=1, refresh=0)
k_fold <- kfold(fit, K = 4, save_fits = T)
fit2 <- stan_glm("x ~ y", data = df, seed=1, refresh=0)
k_fold2 <- kfold(fit2, K = 4, save_fits = T)`

 The error has changed to:

`Error in .subset(x, j) : invalid subscript type 'list'`

rstanarm version: 2.19.2
R version: 3.6.1 (2019-07-05) -- "Action of the Toes"
Operating system: Mac OSX 10.15.3 Catalina
