### ISSUE TITLE
Silent fitting

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#266]
Since the `verbose` parameter doesn't seem to influence the output, is there a way to run function fitting silently, *i.e.*, deactivating the iterations and elapsed time information?

Many thanks

**Comment by jgabry** [comment]
If you're not using multiple cores then this should work: 

```r
output <- capture.output(fit <- stan_glm(mpg ~ wt, data = mtcars))
print(fit)
```

Unfortunately I'm not sure how to do it when using multiple cores. @bgoodri I forget, is it impossible to suppress output when parallelizing chains?

**Comment by jgabry** [comment]
You can now do refresh=0 and it should actually work!

**Comment by bgoodri** [comment]
Just do refresh = 0

**Comment by DominiqueMakowski** [comment]
Awesome thanks!
