### ISSUE TITLE
change the name of a model

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#267]
I compute models iteratively as follows:

```r
for(formula in formulas){
   newfit <- update(fit, formula)
   loo <- rstanarm::loo(newfit)
}
```

However, I'd like to further rename the model (for now they're all called "newfit") so that when doing model comparisons, it prints something better than:

```r
       looic se_looic elpd_loo se_elpd_loo p_loo se_p_loo
newfit  84.7   7.4    -42.3      3.7         2.9   0.7   
newfit  86.2   7.3    -43.1      3.6         3.4   0.8   
newfit  88.4   7.1    -44.2      3.6         4.3   1.0   
newfit  89.3   6.7    -44.7      3.4         2.4   0.5 
```

Is it possible?

Thanks

**Comment by jgabry** [comment]
Yeah, each object returned by the rstanarm's `loo` method has a `name` attribute. So you can do, for example, `attr(loo_object, "name")  <- "model_name"`. Then the `compare_models` function should use `"model_name"` when printing. 

Presumably you're storing the fitted models and loo objects in a list or something like that, so you could do something like this: 

```r
fit <- stan_glm(mpg ~ 1, data = mtcars)

newfits <- list()
loos <- list()
formulas <- c("mpg ~ wt", "mpg ~ wt + cyl", "mpg ~ wt + cyl + gear")
model_names <- c("tomato", "pasta", "fish")
for (j in 1:length(formulas)){
  newfits[[j]] <- update(fit, formula = as.formula(formulas[j]))
  loos[[j]] <- loo(newfits[[j]])
  attr(loos[[j]], "name") <- model_names[j]
}

comp <- compare_models(loos = loos)
```

Then `print(comp)` gives: 

```r
Model comparison: 
(ordered by highest ELPD)

       elpd_diff elpd_loo se_elpd_loo p_loo se_p_loo looic se_looic
pasta    0.0     -78.4      4.6         4.0   1.2    156.8   9.1   
fish    -0.9     -79.3      4.6         4.8   1.4    158.7   9.2   
tomato  -5.0     -83.4      4.3         3.2   1.2    166.9   8.6   
```

NOTE: your output from `compare_models` will look a bit different but the names thing should work. The output above is from the latest __rstanarm__ on Github that will be released to CRAN soon.

**Comment by DominiqueMakowski** [comment]
Thanks!
