### ISSUE TITLE
kfold pointwise elpds in wrong order

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#268]
#### Summary:
If running
```
loocv<-loo(fit)
kcv<-kfold(fit)
```
`loocv$pointwise[,1]` and `kcv$pointwise[,1]` are not in the same order.

Changing
```
  elpds <- unlist(lapply(lppds, function(x) {
    apply(x, 2, log_mean_exp)
  }))
```
to
```
  elpds <- unlist(lapply(lppds, function(x) {
    apply(x, 2, log_mean_exp)
  }))
  elpds <- elpds[order(as.integer(names(elpds)))]
```
fixes this, but I'm not certain if this is robust or the best way to retain the order, so I don't make a commit for that yet. @jgabry can you check this?

**Comment by jgabry** [comment]
Thanks @avehtari. I'll get it sorted out.
