### ISSUE TITLE
fail to install rstanarm

### ISSUE THREAD

**Issue by XinglinTao** [stan-dev/rstanarm#272]
#### Summary:
I try to install rstanarm in rstudio but failed. Is there any way I can change the url or manually install rstanarm? Thanks a lot for helping! 

#### Description:
> install.packages("rstanarm")
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rstanarm_2.17.3.tgz'
Warning in install.packages :
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rstanarm_2.17.3.tgz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/rstanarm_2.17.3.tgz'
Warning in install.packages :
  download of package ‘rstanarm’ failed

#### Operating System:
Your operating system (e.g., OS High Sierra 10.13.4)

**Comment by bgoodri** [comment]
Something is wrong with your internet connection or perhaps the server was
just temporarily down. Try the same command again, or you could choose a
different mirror with

chooseCRANmirror()

**Comment by jgabry** [comment]
Hi @XinglinTao did that work? If not we can reopen this issue.
