### ISSUE TITLE
Warning: Omitting the 'data' argument is not recommended

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#273]
I am trying to upload a [package](https://github.com/neuropsychology/psycho.R) on CRAN which uses rstanarm. However, while the build is clean locally and with travis, the CRAN automated tests stop because of a warning that says:

`Warning: Omitting the 'data' argument is not recommended and may not be allowed in future versions of rstanarm. Some post-estimation functions (in particular 'update', 'loo', 'kfold') are not guaranteed to work properly unless 'data' is specified as a data frame.` 

However, I do not omit the data argument anywhere (this warning appears only in CRAN's checks).

I've noticed this error in one of rstanarm's [vignette](http://mc-stan.org/rstanarm/reference/posterior_predict.stanreg.html).

- The [CRAN log](https://win-builder.r-project.org/incoming_pretest/psycho_0.2.0_20180420_123334/Windows/00check.log) with the error
- The vignette using [rstanarm](https://github.com/neuropsychology/psycho.R/blob/0.2.0/vignettes/bayesian.Rmd#model-visualization)

Is there a way I can fix  this? Thanks

**Comment by bgoodri** [comment]
I don't think it is the warning, but rather the lines after that

Quitting from lines 173-187 (bayesian.Rmd)
Error: processing vignette 'bayesian.Rmd' failed with diagnostics:
the condition has length > 1

But I am not sure what it is referring to

**Comment by jgabry** [comment]
@DominiqueMakowski were you able to get this fixed or is it still giving you trouble? Let us know if you can’t get it working

**Comment by DominiqueMakowski** [comment]
@jgabry Unfortunately no :( 

I made a new attempt after some fixings but it didn't help.

here's the [log](https://win-builder.r-project.org/incoming_pretest/psycho_0.2.0_20180428_165325/Windows/00check.log). It says again that: 

```
...


Warning: Omitting the 'data' argument is not recommended and may not be allowed in future versions of rstanarm. Some post-estimation functions (in particular 'update', 'loo', 'kfold') are not guaranteed to work properly unless 'data' is specified as a data frame.
Quitting from lines 173-187 (bayesian.Rmd) 
Error: processing vignette 'bayesian.Rmd' failed with diagnostics:
the condition has length > 1
Execution halted
```

 I don't understand what's wrong with the Bayesian.Rmd vignette, as my build is errorless.

You'll find the vignette's code [here](https://github.com/neuropsychology/psycho.R/blob/0.2.0/vignettes/bayesian.Rmd) in case you want to try run it (you'll need to install the dev version of the `psycho` package: `devtools::install_github("neuropsychology/psycho.R", ref="0.2.0")`)

Thanks a lot for your help (as well as any advices, opinions on the vignette (which is a manifesto for the use of the Bayesian framework and rstanarm))!

**Comment by jgabry** [comment]
Ok sorry you’re still having trouble. I’ll take a look at the vignette as soon as I can and try to figure this out.

**Comment by jgabry** [comment]
Ok here’s where the warning is coming from: `fit <- rstanarm::stan_glm(Y ~ X, seed=666) `. Can you Try adding the argument `data=data.frame(Y,X)` and see if that gets rid of the warning?

**Comment by DominiqueMakowski** [comment]
@jgabry Thanks a lot, that solved it (sorry for didn't noticing it before!).

By the way, do you have any comments / suggestions as for this vignette? (I'm trying to motivate mmmy colleagues from psycholgy to use the Bayesian framework, but as I'm relatively new to it as well, I'm sometimes unsure as whether everything I understood is correct)

I'll close this issue as its main object is solved :) thanks a lot for your help

**Comment by jgabry** [comment]
I'll take a look at the vignette more closely!

**Comment by DominiqueMakowski** [comment]
@jgabry Wow thanks a lot for these comments! I'll improve all these points :)

**Comment by jgabry** [comment]
No problem!
