### ISSUE TITLE
bad call to grep() in collect_nms()

### ISSUE THREAD

**Issue by BillDunlap** [stan-dev/rstanarm#276]
#### Summary:
A call to grep in collect_nms() looks like it is missing a call to paste0().

#### Description:
In R/misc.R:collect_nms() I see
  alpha <- c(alpha, grep("^", stub, ".{1}\\|\\(Intercept\\)", x, ...))
I think you meant to paste together the first 3 arguments to grep to make the pattern:
  grep(pattern=paste0("^", stub, ".{1}\\|\\(Intercept\\)"), x=x, ...)
Otherwise it is interpreted as
  grep(pattern = "^", x = stub, ignore.case = ".{1}\\|\\(Intercept\\)", perl = x, ...) 
and will always return seq_along(stub), which is always 1L.

#### RStanARM Version:
rstanarm-2.17.4

#### R Version:
R-3.4.3

#### Operating System:
Windows 10

**Comment by jgabry** [comment]
@BillDunlap Thanks for reporting this!

**Comment by jgabry** [comment]
Actually fixed in 523577ce7a436dc6b9b29c88bfa98ccb1c96b46a

**Comment by sambrilleman** [comment]
@BillDunlap @jgabry Sorry for my late reply, thanks both for resolving this!
