### ISSUE TITLE
Option to turn off mean_ppd computation

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#283]
#### Summary:
For big data, mean_ppd computation in generated quantities can take much longer than the model fitting. Add an option to turn mean_ppd computation off.

#### Description:
For big data, `stan_glm` with `algorithm="optimizing"` is accurate enough. Compared to `lm` the optimization is just a bit slower, but sampling from the posterior predictive distribution can take much longer. As mean_ppd is not a crucially important quantity it would be useful to have an option to turnn off the mean_ppd computation.

#### Reproducible Steps:
```
n <- 1e6
x <- rnorm(n)
a <- 2
b <- 3
sigma <- 100
y <- a + b*x + sigma*rnorm(n)
fake <- data.frame(x, y)
fit_1 <- lm(y ~ x, data=fake)
fit_3 <- stan_glm(y ~ x, algorithm="optimizing", data=fake) 
```
lm takes about 2s. stan_glm finishes optimization after about 4s, but then spends 90s to compute mean_ppd

#### RStanARM Version:
[1] ‘2.17.4’

#### R Version:
[1] "R version 3.4.4 (2018-03-15)"

**Comment by jgabry** [comment]
I will have a PR soon with an argument `mean_PPD` to toggle this. Should we have this default to FALSE for optimization or is being able to set it to FALSE sufficient?

**Comment by bgoodri** [comment]
I think off by default is fine for optimization.

**Comment by avehtari** [comment]
I agree with Ben
