### ISSUE TITLE
Add space before printing sigma and aux, so the don't look like coef

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#284]
#### Summary:
When doing `print(fit)` add space before printing sigma and aux, so the don't look like coef

The current output
```
            Median MAD_SD
(Intercept) -1.1    1.2  
height       0.0    0.0  
male         0.9    0.2  
sigma        1.9    0.0  
```
The proposed output
```
            Median MAD_SD
(Intercept) -1.1    1.2  
height       0.0    0.0  
male         0.9    0.2  
 sigma       1.9    0.0  
```
Other suggestions how to separate sigma/aux from coefs are also welcome.

**Comment by betanalpha** [comment]
Perhaps 

male …
sigma (male) ..

**Comment by avehtari** [comment]
@betanalpha the sigma is for the residual, so maybe something else than (male)?

**Comment by betanalpha** [comment]
(sigma)?  Or be explicit and do something like

Intercept:
Residual:

maybe?
