### ISSUE TITLE
predict for stan_gamm4 doesn't work with newdata

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#286]
I manage to predict values on a newdata using the frequentist gamm4:

    library(gamm4)
    library(rstanarm)
        
    fit <- gamm4::gamm4(Sepal.Length ~ s(Petal.Width),
                 random = ~(1|Species),
                 data=iris)
    
    ref_grid <- data.frame(Petal.Width = seq(min(iris$Petal.Width),
                                             max(iris$Petal.Width),
                                             length.out = 10))
    predict(fit$gam, newdata=ref_grid)

However, the same using rstanarm errors...

    fit <- rstanarm::stan_gamm4(Sepal.Length ~ s(Petal.Width),
                        random = ~(1|Species),
                        data=iris,
                        algorithm="meanfield")
    
    ref_grid <- data.frame(Petal.Width = seq(min(iris$Petal.Width),
                                             max(iris$Petal.Width),
                                             length.out = 10))
    
    posterior_predict(fit, newdata=ref_grid)
    posterior_linpred(fit, newdata=ref_grid)

It returns the following:

    Error in lme4::mkReTrms(lme4::findbars(re.form[[2]]), rfd) : 
      inherits(fr, "data.frame") is not TRUE

**Comment by jgabry** [comment]
Thanks for reporting this. It may very well be a bug. @bgoodri have you seen this before?

**Comment by DominiqueMakowski** [comment]
Note that it seems to work without the `random` parameter, which may be related to the error. Thanks :)

**Comment by jgabry** [comment]
Just had a chance to take a real look. The problem is that the "Species" variable is missing from `newdata`. We need a more informative error message for this but I don't think it's a bug. If you add the species variable (either with existing species or a new species) it should work.

**Comment by DominiqueMakowski** [comment]
You're  right,

as such, it works with changing the re.form parameter: 

```r
posterior_predict(fit, newdata=ref_grid, re.form=NA)
posterior_linpred(fit, newdata=ref_grid, re.form=NA)
```

Thanks !!
