### ISSUE TITLE
cannot install rstanarm

### ISSUE THREAD

**Issue by beew** [stan-dev/rstanarm#293]
#### Summary:
Try to install rstanarm from cran and got error

#### Reproducible Steps:
start R

run

install.packages('rstanarm')

the outputs:

```
Installing package into ‘/usr/lib/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/rstanarm_2.17.4.tar.gz'
Content type 'application/x-gzip' length 2317004 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

* installing *source* package ‘rstanarm’ ...
** package ‘rstanarm’ successfully unpacked and MD5 sums checked
** libs
"/usr/lib/R/bin/Rscript" -e "source(file.path('..', 'tools', 'make_cc.R')); make_cc(commandArgs(TRUE))" stan_files/jm.stan
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '../tools/make_cc.R': No such file or directory
Execution halted
Makevars:17: recipe for target 'stan_files/jm.cc' failed
make: *** [stan_files/jm.cc] Error 1
ERROR: compilation failed for package ‘rstanarm’
* removing ‘/usr/lib/R/library/rstanarm’
```
#### R Version:
3.4.4

#### Operating System:
Ubuntu 16.04.4 64 bits

**Comment by beew** [comment]
I figured it out myself.

The problem is that rstanarm's install script assumes R's working directory is the user's $HOME on Linux. But mine is in $HOME/R and I have setwd(~/R) in my .RProfile. Commenting out this line in .RProfile and restart R installation went through. After that I just uncommented the setwd  line in .RProfile and rstanram loads with no problem.

I think this should be a bug since the install script should be able to find the user's working directory. I have no such issue with most other R packages.

**Comment by bgoodri** [comment]
It does not assume the working directory is your home directory, but rather the working directory is the root of the package directory, which is not the case if you call `setwd` in .Rprofile . The **rstanarm** package has a more complicated build process than most other packages, but we can only assure that it builds on CRAN or systems that behave sufficiently like CRAN.
