### ISSUE TITLE
define default values for variables in vignette prior to function call

### ISSUE THREAD

**Issue by aaelony** [stan-dev/rstanarm#296]
#### Summary:
Not a huge issue, but the nice vignette at https://cran.r-project.org/web/packages/rstanarm/vignettes/rstanarm.html might be friendlier if it were runable out of the box.  Need to declare and assign variables `CHAINS`, `CORES`, `SEED` beforing calling `stan_glm` with these variables. 

```
library(rstanarm)
womensrole_bglm_1 <- stan_glm(cbind(agree, disagree) ~ education + gender,
                              data = womensrole,
                              family = binomial(link = "logit"), 
                              prior = student_t(df = 7), 
                              prior_intercept = student_t(df = 7),
                              chains = CHAINS, cores = CORES, seed = SEED)
```

Cheers,
Avram

**Comment by bgoodri** [comment]
These are defined by a hidden knitr chunk. The reason we didn't unhide the
chunk is because the values were chosen for speed rather than being good
values. But since we are not evaluating the code in the vignettes on CRAN
anymore, maybe we can change that.

**Comment by aaelony** [comment]
Makes sense.  Maybe it's a good thing to make sure the reader is paying attention.
For me, I did the following:

```
CORES <- CHAINS <- SEED <- 4
```
or perhaps the vignette could have something fancier that detects appropriate values.
Feel free to close this issue if it's too trivial.

**Comment by jgabry** [comment]
@aaelony Thanks for bringing this up. Yeah I don’t think hiding those values is good practice on our part. We had our reasons like @bgoodri said, but we can change that going forward.
