### ISSUE TITLE
stan_clogit error when there is only one predictor

### ISSUE THREAD

**Issue by sschloss1** [stan-dev/rstanarm#297]
#### Summary:
When the formula for stan_clogit has only one predictor (one term on the right-hand side of the formula), the function fails with error "Error in `reformulate(attr(termobj,` "term.labels")[-dropx], if (keep.response) termobj[[2L]] else NULL,  :  'termlabels' must be a character vector of length at least one"

This error can be eliminated by simply adding a "0+" in front of the predictor.

#### Description:
See above.

#### Reproducible Steps:
```
require(rstanarm)

set.seed(123)

dat=data.frame(case=rep(0:1,times=200),var1=rnorm(400),var2=rnorm(400),strat=rep(1:200,each=2),
    group=round(runif(400,1,10)))

#this works
post1 <- stan_clogit(case ~ var1 + var2, strata = strat,data = dat,chains=2,iter=500)

#this works
post2 <- stan_clogit(case ~ var1 + (1|group), strata = strat,data = dat,chains=2,iter=500)

#this fails with termlabels error
post3 <- stan_clogit(case ~ var1, strata = strat,data = dat,chains=2,iter=500)

#this fails with termlabels error
post4 <- stan_clogit(case ~ (1|group), strata = strat,data = dat,chains=2,iter=500)

#this works
post5 <- stan_clogit(case ~ 0+var1, strata = strat,data = dat,chains=2,iter=500)

#this works
post6 <- stan_clogit(case ~ 0+(1|group), strata = strat,data = dat,chains=2,iter=500)
```

#### RStanARM Version:
2.17.4

#### R Version:
3.4.0

#### Operating System:
Microsoft Windows 10 Pro

(Note: exact same results found for same RStanArm version running on R version 3.4.2 with operating system Ubuntu 17.10).

**Comment by bgoodri** [comment]
Thanks. We'll fix it somehow.

**Comment by bgoodri** [comment]
I think I fixed this. Thanks @sschloss1 .
