### ISSUE TITLE
Standardized posteriors

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#298]
I came across two methods of computing standardized coefficients (posteriors), one from @bgoodri  ([here](https://stackoverflow.com/questions/49332080/obtaining-standardized-coefficients-from-rstanarm-package-in-r?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)) and one from @jgabry ([here](http://discourse.mc-stan.org/t/obtaining-standardized-coefficients-from-rstanarm-package-in-r/3603/2)):

```r
fit <- stan_glm(wt ~ vs*gear, data = mtcars)
ouctome <- "wt"
```
## bgoodri 

```r
    X <- model.matrix(fit)
    sd_X <- apply(X, MARGIN = 2, FUN = sd)[-1]
    sd_Y <- apply(posterior_predict(fit), MARGIN = 1, FUN = sd)
    beta <- as.matrix(fit)[ , 2:ncol(X), drop = FALSE]
    posteriors_std <- sweep(
      sweep(beta, MARGIN = 2, STATS = sd_X, FUN = `*`),
      MARGIN = 1, STATS = sd_Y, FUN = `/`
    )
```

## jgabry
```r
    X <- model.matrix(fit)[, -1]  # -1 to drop column of 1s for intercept
    sd_X_over_sd_y <- apply(X, 2, sd) / sd(fit$data[[outcome]])
    beta <- as.matrix(fit, pars = colnames(X))  # posterior distribution of regression coefficients
    posteriors_std <- sweep(beta, 2, sd_X_over_sd_y, "*")  # multiply each row of b by sd_X_over_sd_y
```

These two methods return slightly different results. Is there any reason to prefer one another (I understand the first one would need the QR parameter to set to TRUE?) Thanks :)

**Comment by jgabry** [comment]
I think the difference is that @bgoodri is estimating sd_y via the posterior predictive distribution whereas as my version was just using the sample standard deviation.

**Comment by jgabry** [comment]
And to answer your actual question, @bgoodri's approach is a bit more principled than mine as it doesn't assume that sd(y) computed from the data is actually the standard deviation of y (instead it is estimated using the posterior predictive draws). And I don't think using `QR=TRUE` would be absolutely _required_ for this method, but it can certainly be more efficient.

**Comment by DominiqueMakowski** [comment]
Thanks a lot for these answers!! :)
