### ISSUE TITLE
stan_glmer shifts values of parameter with option algogithm="meanfield"

### ISSUE THREAD

**Issue by arnaudmgh** [stan-dev/rstanarm#303]
#### Summary:
stan_glmer with algo="meanfield" will duplicate the value of the first parameter, and shift all the other parameters *values* by one; but not the parameter names, resulting in wrong values for the parameters. 

#### Description:
I am running stan_glmer with the same model and the same data, just changing the algorithm argument from "Sampling" to "meanfield". There is a bug with the intercept returned with "meanfield": the second intercept is exactly identical the first one, and then all the other intercepts are shifted by one (the second one is in place of the third one, etc). Importantly, the *name* of the parameters are *not* shifted, and therefore the values are wrong. 

#### Reproducible Steps:
    reedfrogs <- read.csv("https://raw.githubusercontent.com/rmcelreath/rethinking/master/data/reedfrogs.csv", sep=";")
    d <- reedfrogs
    d$tank <- 1:nrow(d)

    library(rstanarm)
    reedarm <- stan_glmer(cbind(surv, density-surv)~(1|tank), data=d, algorithm = "sampling", family=binomial())
    reedarmvb <- stan_glmer(cbind(surv, density-surv)~(1|tank), data=d, algorithm = "meanfield", family=binomial())
    # see in the data.frame how the values are shifted
    data.frame(sampling=colMeans(as.matrix(reedarm))[2:8], meanfield=colMeans(as.matrix(reedarmvb))[2:8])

Which shows:

                            sampling  meanfield
    b[(Intercept) tank:1]  0.7550621  0.8797813
    b[(Intercept) tank:2]  1.7484607  0.8797813  # DUPLICATED WITH FIRST WHEN USING MEANFIELD!
    b[(Intercept) tank:3] -0.3773396  1.4443334
    b[(Intercept) tank:4]  1.7010447 -0.2794685
    b[(Intercept) tank:5]  0.7895597  1.5234424
    b[(Intercept) tank:6]  0.7589158  0.7587912
    b[(Intercept) tank:7]  1.6665793  0.7248997

#### RStanARM Version:
2.17.4

#### R Version:
3.5.0

#### Operating System:
Amazon Linux AMI (https://aws.amazon.com/amazon-linux-ami/2018.03-release-notes/).
PS: I also tried on Mac OS 10.12 with R 3.2.0 and rstanarm 2.17.2, with same results

**Comment by bgoodri** [comment]
This was actually a bug with **rstan**, but it should now be fixed on develop.
