### ISSUE TITLE
rstanarm fails to install in RStudio

### ISSUE THREAD

**Issue by PCK1992** [stan-dev/rstanarm#304]
#### Description:
I tried to install rstanarm but the installation in RStudio crashes. rstan is installed and can be loaded, I followed the instructions from the wiki for the installation. I can see no error message because RStudio crashes abruptly.
I also tried to install the development version but that also doesn't work. I also tried installing it outside of RStudio.

UPDATE: It worked the second time installing from an R terminal. However, installation within RStudio still fails.

#### RStanARM Version:
2.17.4 CRAN

#### R Version:
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"

### RStudio Version:
Version 1.1.453

#### Operating System:
Xubuntu 18.04 LTS (16GB RAM +8GB swap)

**Comment by corriebar** [comment]
I had the same issue, though I only tried `install.packages("rstanarm")` in Rstudio which then crashed. After reading this, I installed from an R terminal which worked.

**RStanARM** Version:**
2.17.4 CRAN

**R Version:**
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"

**RStudio Version:**
Version 1.1.45

**Operating System:**
Ubuntu 18.04.1 LTS

**Comment by dandermotj** [comment]
I also have issues installing `rstanarm` on my Ubuntu 18.04 machine. Definitely not a RAM issue - I have 16GBs. `rstanarm` has been "building" for over 5 minutes. I'll try to include any additional error messages/warnings once it's given up.
