### ISSUE TITLE
stan_polr drops levels with no observations

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#310]
#### Summary:
If target variable is factor or ordered factor with L levels, but there are observations for K<L levels, `stan_polr` will make a model with K levels. This is probably not a common situation, but 
 - it might be useful to be able to still make a model with L levels
 - or at least give a warning that there are less observed levels than defined factors.

#### Description:
ARM book had and an example with `bayesplor` code defined in R here http://www.stat.columbia.edu/~gelman/arm/software/. I tried to reproduce the results with `stan_polr`, but that didn't work if K<L.

#### Reproducible Steps:
```
data_405$factor_vote <- factor(c(1,3,1,3,1,1,1,1,3,3,1,1,1,3,3,1,1,3,1,3),
                               levels = c(1, 2, 3), labels = c("1", "2", "3"),
                               ordered=TRUE)
data_405$value <- c(44,98,1,77,43,2,20,54,70,81,10,56,39,86,80,24,32,56,52,78)
fit_1 <- stan_polr(factor_vote ~ value, data = data_405,
                   prior = R2(0.5, "mean"))
data_405$factor_vote
print(fit_1, digits=2)
```
`factor_vote` has three levels defined, but `stan_polr` produces a model with only two levels.

#### RStanARM Version:
‘2.17.4’

#### R Version:
R version 3.5.1 (2018-07-02)

#### Operating System:
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

**Comment by bgoodri** [comment]
This got fixed for 2.18
