### ISSUE TITLE
Confusion of interpreting random effect and residual in summary( stan_glmer(...) ) 

### ISSUE THREAD

**Issue by chenpanliao** [stan-dev/rstanarm#313]
#### Summary:
The random effect and residual seems presented in different scale in summary( stan_glmer(...) ) .

#### Description:
It seems that summary( stan_glmer(...) ) reports the standard deviation for residual but report variance for random intercept/slop. Is this a mistake or the authors designed in purpose?

#### Reproducible Steps:
I fit sample data with same mixed model formula by using `lme4::lmer()`, `MCMCglmm::MCMCglmm()` and `rstanarm::stan_glmer()`.

`library(lme4)`
`library(MCMCglmm)`
`library(rstanarm)`
`m.lme4 <- lmer(Reaction ~ Days + (1 | Subject), sleepstudy)`
`m.MCMCglmm <- MCMCglmm(Reaction ~ Days, random = ~ Subject, data = sleepstudy)`
`m.rstanarm <- stan_glmer(Reaction ~ Days + (1 | Subject), sleepstudy, seed = 1234, chains = 1, iter = 5000)`

Than I focused on the results about random intercept and residual.
`summary(m.lme4)`
`summary(m.MCMCglmm)`
`print(m.rstanarm)`
`summary(m.rstanarm)`

All these results showed that the standard deviation of random intercept is about 38 and standard deviation of residuals is about 30 (notice that MCMCglmm reported in variance scale). However, **`summary(m.rstanarm)` reported residual in standard deviation scale but reported random intercept in variance scale**.

I'm not saying the calculations were incorrect, but the `summary(stan_glmer(...))` outputs of residual (called `sigma`) and random effect (called `Sigma[Subject:(Intercept),(Intercept)]`) in different scale could be very confusing since they were labeled as sigma. Is this just a mistake about naming the posterior distribution for random effect? Or the authors designed in purpose? Thanks for any response.

PS. I also tried `brms::brm()` to fit same data with same formula, and confirmed that `brm(...)` reports residual and random effect in SD scale, and the name of these terms are very clear to me (`sigma` for residual and `sd(Intercept)` for random intercept).

#### RStanARM Version:
2.17.4

#### R Version:
3.5.1

#### Operating System:
Windows 10 Enterprise 1803

**Comment by bgoodri** [comment]
This was more or less on purpose. The `stan_glmer` function estimates a variance-covariance matrix for the group level deviations, even if this variance-covariance matrix is merely 1x1 in the case of group-wise intercept deviations only. So, the primitive parameter being sampled is a variance, and I think `print` is just taking the standard deviation of the mean variance (which is not even exactly right). In contrast, the primitive parameter for the measurement error (sigma) is a standard deviation, so there is a difference there.
