### ISSUE TITLE
CRAN package reminder by Prof. Brian D Ripley: vanilla in Makevars

### ISSUE THREAD

**Issue by dmenne** [stan-dev/rstanarm#321]
I received two emails by BDR; the second one was addressed to the maintainers of: 

BMSC DeLorean MADPop MetaStan RBesT bayesLopod bayesdfa beanz bmlm 
conStruct ctsem dfpk eggCounts gastempt glmmfields idealstan idem rstan 
rstanarm survHE tmbstan trialr walker

I do not dare to cite the content of the email, since I have been ripleyed quite a few times for not asking permission to cite from his emails in the good old R-help times. Or for not citing the complete message. But, as usual, I am sure BDR makes a valid point.

The subject was `--vanilla` in `Makevars`. BDR had good reasons against its use, and I understood the first email that it simply should be removed, but after reading the second one, I am no longer sure.

Here is my first attempt, submitted to CRAN

https://github.com/dmenne/breathteststan/blob/master/src/Makevars

I do not know if my new submission has already been taken into account by BDR.
Since rstanarm is the mother of all similar packages, it would be good to get some advise on the matter.

**Comment by bgoodri** [comment]
We'll get it sorted out on Discourse today

**Comment by gbradburd** [comment]
@bgoodri could you link the discourse thread from this Issue once it's started?  I got the same email (I'm the maintainer for conStruct) and want to follow the discussion. Thanks!

**Comment by bgoodri** [comment]
https://discourse.mc-stan.org/t/how-to-update-a-package-that-has-stanheaders-and-rstan-in-its-linkingto-part-ii/6214?u=bgoodri
