### ISSUE TITLE
error when getting prior.info if subset argument is supplied

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#33]
@bgoodri 

These lines 

    all_args <- mget(names(formals()), sys.frame(sys.nframe()))
    prior.info <- all_args[grep("prior", names(all_args), fixed = TRUE)]

are intended to collect all the prior-related arguments so after the model is fit we or the user can see what choices were made for the priors. Because `match.call` won't include these if the user leaves the default priors I came up with the solution above. But I just discovered that something like

    stan_glm(mpg ~ wt, data = mtcars, subset = cyl < 8) 

leads to the following error:

    Error in mget(names(formals()), sys.frame(sys.nframe())) : 
      object 'cyl' not found

which I guess makes sense, but I'm not sure how to work around it. Any ideas?

**Comment by bgoodri** [comment]
To get the information on the priors, I think we should parse the call.

**Comment by bgoodri** [comment]
Or you might be able to do it the existing way by specifying the ifnotfound
argument to mget().

**Comment by jgabry** [comment]
Ok thanks. I'll give it a try.

**Comment by jgabry** [comment]
I think this is fixed by 7625725
