### ISSUE TITLE
validate_newdata should not complain about irrelevant variables

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#347]
#### Summary:

The `validate_newdata` throws an error if there are any NAs
https://github.com/stan-dev/rstanarm/blob/918103f961732e393f123b8960d5daeeadb99590/R/misc.R#L769
without checking (or having any way to check) that the variables with NAs are actually being used.

**Comment by jgabry** [comment]
Ok I’ll look into this soon and see if we can change things to give it a way to tell which are the relevant variables.

**Comment by bgoodri** [comment]
I think the easiest thing would be to figure out which are the relevant
variables and only pass that subset of newdata to validate_newdata.

**Comment by jgabry** [comment]
Yeah that makes sense.

**Comment by sambrilleman** [comment]
You might be able to borrow an idea/code from `validate_newdatas`, see lines 1289 to 1300 [here](https://github.com/stan-dev/rstanarm/blob/918103f961732e393f123b8960d5daeeadb99590/R/misc.R#L1289). I pass the entire data frame to `validate_newdatas` but only check for NAs in the relevant subset of columns.

**Comment by jgabry** [comment]
Thanks Sam

**Comment by jgabry** [comment]
I think we can do something like this, which I now have on a branch:

```r
  # only check for NAs in used variables
  vars <- all.vars(formula(object, m = m))
  newdata_check <- newdata[, colnames(newdata) %in% vars, drop=FALSE]
  if (any(is.na(newdata_check)))
    stop("NAs are not allowed in 'newdata'.", call. = FALSE)
```
