### ISSUE TITLE
Errors from StanHeaders when compiling rstanarm

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#361]
@bgoodri when I run `R CMD INSTALL --preclean rstanarm` (using master branch) I'm seeing a bunch of errors that seem to be related to StanHeaders and prevent compilation from succeeding. Any idea what's going on? Here's a sample of the errors:

```
In file included from stan_files/jm.cc:3:
stan_files/jm.hpp:8824:35: error: no member named
      'cholesky_factor_corr_constrain' in 'stan::io::reader<double>'
                bCholesky2 = in__.cholesky_factor_corr_constrain(((primi...
                             ~~~~ ^

...

In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/src/stan/services/experimental/advi/fullrank.hpp:11:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/StanHeaders/include/src/stan/variational/advi.hpp:114:47: error: 
      no matching member function for call to 'log_prob'
            double log_prob = model_.template log_prob<false, true>(zeta, &ss);

...

stan_files/jm.hpp:10910:14: error: no matching member function for call to
      'log_prob'
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
```

and other similar messages.

**Comment by bgoodri** [comment]
Yeah, you need to use the forthcoming StanHeaders, but GitHub does not have
some of the files I had to add to make it work because it won't let me push
into a subrepo. I will send you a .tar.gz file when I am back on my other
computer.

**Comment by jgabry** [comment]
Ok thanks

**Comment by jgabry** [comment]
@sambrilleman may need this too. I think it’s ok to just attach it to this issue (drag into text box). @bgoldri If that’s not a problem for some reason I can do that.

**Comment by sambrilleman** [comment]
Ok, perfect, thanks.

**Comment by bgoodri** [comment]
You can get build it if you change StanHeaders/inst/include/upstream to the
stuff_for_2.19 branch.
