### ISSUE TITLE
stan_gamm4 error when bs="cc"

### ISSUE THREAD

**Issue by peterphalen** [stan-dev/rstanarm#362]
#### Summary:
The `s` function in stan_gamm4 throws an error when bs = "cc". 

#### Description:
Despite working until relatively recently, use of the `s` function now appears to fail when trying to fit cyclical splines using `bs="cc"`.  The function continues to work on other settings such as `bs="cr"` or `bs="tp"`.

#### Reproducible Steps:
In R:
```
N <- 100
data <- data.frame(y = rpois(N, 2), x = rep(1:(N/2),2))
stan_gamm4(y ~ s(x, bs = "cc"), data=data)
```
Yields the following error:
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: mismatch in number dimensions declared and found in context; processing stage=data initialization; variable name=S; dims declared=(100,1); dims found=(1,100,8)  (in '/data/NKX.stan' at line 19; included from 'model_continuous' at line 28)

failed to create the sampler; sampling not done
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug

#### RStanARM Version:
2.18.2

#### R Version:
3.5.2

#### Operating System:
OS X 10.14.4

**Comment by jgabry** [comment]
Thanks not good, thanks for reporting this. I’m not aware of anything in our implementation that would have changed this. @bgoodri any ideas off the top of your head? If not I can look into this.

**Comment by bgoodri** [comment]
No, but mgcv may have changed or it looks like maybe we just have the
dimensions out of order. See what `mgcv::jagam` does with that formula.

**Comment by peterphalen** [comment]
@bgoodri I took the liberty and it seems to run okay with JAGS. 


The following code generates random data, fits the model in JAGS, and plots the result. No errors and the result seems totally reasonable.

```
require(mgcv)
require(rjags)

N <- 100
y <- rnorm(N, 0, 1)
x <- rep(1:(N/2),2)
data <- data.frame(x, y)

jags.file <- paste(tempdir(),"/test.jags",sep="") 
jd <- jagam(formula(y ~ s(x, bs="cc")), file=jags.file, data=data)

jm <-jags.model(jags.file, data=jd$jags.data, inits=jd$jags.ini,n.chains=1)
sam <- jags.samples(jm,c("b","rho","scale","mu"),n.iter=10000,thin=10)
jam <- sim2jam(sam,jd$pregam)
plot(jam, ylim=c(-3,3))
points(y ~ x, data = data)
```
![Rplot01](https://user-images.githubusercontent.com/6245003/57962707-5d070e00-78e8-11e9-8289-b03b2f6065ef.png)

Here is the model code produced by `mgcv::jagam(formula(y ~ s(x, bs="cc")), file="out", data=data)`:

```
model {
  mu <- X %*% b ## expected response
  for (i in 1:n) { y[i] ~ dnorm(mu[i],tau) } ## response 
  scale <- 1/tau ## convert tau to standard GLM scale
  tau ~ dgamma(.05,.005) ## precision parameter prior 
  ## Parametric effect priors CHECK tau=1/19^2 is appropriate!
  for (i in 1:1) { b[i] ~ dnorm(0,0.0029) }
  ## prior for s(x)... 
  K1 <- S1[1:8,1:8] * lambda[1] 
  b[2:9] ~ dmnorm(zero[2:9],K1) 
  ## smoothing parameter priors CHECK...
  for (i in 1:1) {
    lambda[i] ~ dgamma(.05,.005)
    rho[i] <- log(lambda[i])
  }
}
```

**Comment by bgoodri** [comment]
OK, that would suggest that we mess things up after calling mcgv::jagam

**Comment by jgabry** [comment]
I’m on my phone now so can’t look into it further at the moment, but I meant to say earlier that one place where things definitely go wrong is here:

https://github.com/stan-dev/rstanarm/blob/6bb150024fe70903edd3e99bd2e19395b9ae0e1d/R/stan_glm.fit.R#L108-L113
