### ISSUE TITLE
suppress confusing warning from lme4

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#365]
On Discourse Shira Mitchell [wrote](https://discourse.mc-stan.org/t/autoscale-in-rstanarm-warning-to-consider-rescaling/8951): 

> When running `stan_glmer()` I got the following warning message:
> 
> `Some predictor variables are on very different scales: consider rescaling`
> 
> I'm confused because I thought the default is `autoscale = TRUE` (https://cran.r-project.org/web/packages/rstanarm/vignettes/priors.html#automatic-prior-scale-adjustments)?

@bgoodri I think this must be coming from **lme4** and it's definitely confusing since it seems like it's coming from `stan_glmer()`. We should see if we can suppress this. @shiraamitchell is right that it conflicts with the whole autoscaling thing.

**Comment by bgoodri** [comment]
Probably need to do suppressWarnings() when it builds the model.frame or
something.

**Comment by jgabry** [comment]
That could work but would suppress all warnings. if there are no important warnings thrown by whatever is throwing this warning then yeah let’s just suppressWarnings() it.

**Comment by jgabry** [comment]
I think it's coming from `lme4::[g]lFormula()`

**Comment by shiraamitchell** [comment]
thanks for tracking this down!

**Comment by jgabry** [comment]
Thanks for letting us know about it!

**Comment by jgabry** [comment]
In the next release it will only let lme4 throw that warning if autoscale=FALSE for the prior on the coefficients on X.
