### ISSUE TITLE
default degrees of freedom for hs() and hs_plus()

### ISSUE THREAD

**Issue by mcol** [stan-dev/rstanarm#369]
#### Summary:
The documentation asserts that default degrees of freedom for `hs` and `hs_plus` are 3, but in the code they are actually set to 1. 

#### RStanARM Version:
git repository

**Comment by mcol** [comment]
I can submit a patch for this, but I'm not sure if I should fix the code or the documentation. I think 3 degrees of freedom was the suggested value for the non-regularized horseshoe, but perhaps it's still a safe default even for the regularized horseshoe?

**Comment by avehtari** [comment]
Thanks for pointing this out (and coming back to remind us!) Please, fix the documentation. 1 is the correct one, 3 was something we experimented to reduce divergences, but then regularized hs with additional slab component turned out to be a better solution.

**Comment by jgabry** [comment]
Closing this since I just merged #373. Thanks for catching this and fixing the doc!
