### ISSUE TITLE
Posterior predict (.pp_data_mer) error with newdata using tbl_df

### ISSUE THREAD

**Issue by jburos** [stan-dev/rstanarm#37]
I noticed the following error when calling posterior_predict with newdata, where my newdata contains a `tbl_df` (which inherits from data.frame) instead of a `data.frame`.

Here is a reproducible example:
```{R}
library(dplyr)
data(mtcars)
mtcars_tbl_df <- tbl_df(mtcars)

m1 <- stan_glmer(qsec ~ 1 + wt + (1 | cyl), data = mtcars)
ppred1_df <- posterior_predict(m1, newdata = mtcars)

m2 <- stan_glmer(qsec ~ 1 + wt + (1 | cyl), data = mtcars_tbl_df)
ppred2_tbl <- posterior_predict(m2, newdata = mtcars_tbl_df)
```

Which produces the following error: 
```{R}
> ppred2_tbl <- posterior_predict(m2, newdata = mtcars_tbl_df)
Error in .pp_data_mer(object, newdata, ...) : 
  New levels found in grouping variable(s) cyl
```

However, in this example, the following will work:
```{R}
ppred2_tbl2 <- posterior_predict(m2, newdata = as.data.frame(mtcars_tbl_df))
```

This seems like a minor bug to me, since there is such an easy work-around (demonstrated above). Documenting in case it is helpful.

**Comment by jgabry** [comment]
Thanks for letting us know and for the example. Should be fixed now by 9787747.
