### ISSUE TITLE
Linux rstanarm install fail

### ISSUE THREAD

**Issue by googkoen** [stan-dev/rstanarm#375]
#### Summary:
Cannot install rstanarm; usually R crashes.

#### Description:
Have tried installing rstan and rstantools first, using repos = 'http://cran.rstudio.com' and repos = 'https://cloud.r-project.org/'.  I also tried installing rstanarm from Github and from command line -- nothing seems to work.  My .Rprofile files don't seem to have a place where I can tinker with the working directory location.

If R does not crash, I end up with the following error: 
"Error: package or namespace load failed for ‘rstanarm’:
 object ‘loo_R2’ is not exported by 'namespace:rstantools'"

Installing rstan does install the Loo package, but I don't see loo_R2 from ls("package:loo").

#### Reproducible Steps:
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
library(rstan)
install.packages('devtools')
library(devtools)
install_github("stan-dev/rstanarm", build_vignettes = FALSE)

Should yield this error.  As does: 
install.packages('rstanarm', dependencies = T, repos = 'http://cran.rstudio.com')

#### RStanARM Version:
2.18.9

#### R Version:
3.5.0

#### Operating System:
Debian GNU/Linux 10 (buster)

**Comment by bgoodri** [comment]
This is in rstantools on CRAN now
