### ISSUE TITLE
default to QR=TRUE for advi?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#38]
@bgoodri I've also noticed that doing the QR composition before advi seems to be more reliable, the same you discussed with @akucukelbir in [this thread](https://groups.google.com/forum/?fromgroups#!topic/stan-dev/qkQsG0f8krk) on stan-dev. Do you think we should default to `QR=TRUE` if the user specifies `"meanfield"` or `"fullrank"` as the estimation algorithm?

**Comment by bgoodri** [comment]
My sense is that meanfield would be better on average with the QR
reparameterization than without it. But defaulting to QR = algorithm ==
"meanfield" is not something that the typical user would be cognizant of.
Someone could try to put a prior on beta and unknowingly have it applied to
theta = R * beta. Maybe it would be better to output a message if someone
does meanfield without QR. In principle, if someone does fullrank, I don't
think the QR reparameterization should make a systematic difference. But it
seems as if fullrank induces so many local optima that it is hard to
separate problems in the variational approximation from problems getting to
the global optimum. Also, the QR reparameterization tends to help the
effective sample size when doing sampling, but we can't expect most users
to understand that.

**Comment by jgabry** [comment]
Ok I think you're right that defaulting to QR=TRUE will lead to confusion
and a message if meanfield is selected without QR is a better idea.

This also reminds me that we should make it very clear that toggling QR
changes the interpretation of the priors, which isn't obvious unless the
user knows about how everything is implemented.

**Comment by jgabry** [comment]
To add to the last point, I think we want to be as clear as possible about
anything like that in rstanarm so that anyone who uses it (and who cares
about the details) can report what they did without
accidentally misrepresenting the priors (or anything else subtle).

We are in strange territory with this package in some sense, because I
think the target audience is broader than just people who would otherwise
just use glm and lme4. I think it will be really useful to current Stan
users as well and also anyone interested in doing well-implemented and
flexible Bayesian regression models. There's also some pretty novel and
challenging stuff going on in some of the models, so it's hard to find the
right level of detail without alienating one group or being too simplistic
for the other.

**Comment by bob-carpenter** [comment]
In general, dependent arguments make understanding how a program
is going to behave very difficult, because you lose modularity.

- Bob

**Comment by bob-carpenter** [comment]
How do you "be as clear as possible in rstanarm"?  This
is the heart of the problem --- if you dump too much,
people won't read it (or will get freaked out).  If you
bury it in doc, people won't read it.

If you can, make it as safe as possible by default and
provide warnings if people override things that may be unsafe.

It's easier for advanced users (by definition) to override default
behavior than it is for beginners.

But it's a classic conundrum of how to design a system for
both beginning and advanced users, especially one with a 
transition path.

- Bob

**Comment by jgabry** [comment]
On Thursday, December 10, 2015, Bob Carpenter <notifications@github.com>
wrote:

> How do you "be as clear as possible in rstanarm"? This
> is the heart of the problem --- if you dump too much,
> people won't read it (or will get freaked out). If you
> bury it in doc, people won't read it.


Exactly. That's my concern, and I'm not sure we're doing it as effectively
as possible at the moment. Some it is just not having the time yet, but
it's also that it's just hard to do well.


It's easier for advanced users (by definition) to override default
> behavior than it is for beginners.


That's a good point. I wonder how we can make it safe by default without
having mean some arguments depend on others so that the best combination is
made for people who want a mostly hands off experience (for example it is
very useful to set adapt_delta based on the type of prior chosen). In other
words, assuming that users who do the most tweaking are likely to know what
they're doing, how much do we want the behavior to react to "light to
moderate" tinkering?

**Comment by bgoodri** [comment]
I think if someone specifies prior = NULL, then there is a strong case for
make QR be TRUE even if the user is unaware of what is going on. In other
words, an improper uniform on beta is basically the same as an improper
uniform on theta = R * beta. But if someone puts a proper prior on "the
coefficients", it seems unethical to apply that to theta without the user
explicitly specifying QR = TRUE.

**Comment by jgabry** [comment]
On Thu, Dec 10, 2015 at 12:52 AM, bgoodri <notifications@github.com> wrote:

> I think if someone specifies prior = NULL, then there is a strong case for
> make QR be TRUE even if the user is unaware of what is going on. In other
> words, an improper uniform on beta is basically the same as an improper
> uniform on theta = R * beta. But if someone puts a proper prior on "the
> coefficients", it seems unethical to apply that to theta without the user
> explicitly specifying QR = TRUE.
>

Yeah I agree with that. I just want to make sure that the implications for
the prior are clear to the user if they do select QR=TRUE.

**Comment by bgoodri** [comment]
I think this was accomplished for the initial release.

**Comment by jgabry** [comment]
I think we should still add a message if the user does mean-field vb with
QR=FALSE. I can do that.

And maybe we should make QR=TRUE if priors are omitted on the coefficients.
