### ISSUE TITLE
Error while loading the package

### ISSUE THREAD

**Issue by atnplab** [stan-dev/rstanarm#382]
Hi everyone,

I have been using the package for the last months but after 2 weeks off I got this message:

**Error: package or namespace load failed for ‘rstanarm’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘processx’**

How can I solve this?
Many thanks!

**Comment by bgoodri** [comment]
Install the processx package
