### ISSUE TITLE
rstanarm stan_jm crash:  Requested bug report

### ISSUE THREAD

**Issue by lhunsicker** [stan-dev/rstanarm#389]
#### Summary:
I ran a stan_jm model that crashed with the following request to submit a bug report:
Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
In addition: Warning message:
In .local(object, ...) :
  some chains had errors; consider specifying chains = 1 to debug

#### Description:
I recently tried to run an rstanarm stan_jm model, and it crashed with output that requested that I submit a bug report.  Attached is a zip file that contains an r file with the error output at the end, and a dmp file that contains the two data sets used in the stan_jm call, together with the output of an lme4 program and a stan_lme4 program for the longitudinal part.  (I forgot to include the output of the Event part, but it runs very quickly and can be run from the r file.)  Both pieces run fine separately.  But the joint model crashes.

As I said, I am sending this to you because the crash output asked me to.  But I am not at all sure that the problem is yours, other than, perhaps, having a less than helpful error message.

This was sort of a test run for me of a joint model.  The longitudinal value (cpep) is closely linked to the definition of failure in the event model, and the data set has a number of failures.  The data includes cpep values below the lower limit of detection -- effectively zeros.  So the joint model may be very poorly conditioned, since a close to zero value for cpep is, in effect, a synonym for failure.  I just wanted to see how much correction there was of the estimated  longitudinal slope for the values missing because of failure.  I have looked at this with other predictors and I see some, but so far not much, adjustment of the estimated slope when the longitudinal model is run separately vs. in a joint model.  The reverse effect works fine in these other models.  The eta shows clearly that the risk of failure is markedly increased by time evolving values in the longitudinal model that predict failure. 

So again, this bug report is not a complaint.  It was requested.   Keep up the good work.

Larry Hunsicker
Prof IntMed Emeritus, UIowa 
#### Reproducible Steps:
See the files in the attached zip file BugReport.zip
[BugReport.zip](https://github.com/stan-dev/rstanarm/files/3664771/BugReport.zip)

#### RStanARM Version:
2.18.2
#### R Version:
3.6.1 (2019-07-05) -- "Action of the Toes"
#### Operating System:
Windows 10 up to date version

**Comment by lhunsicker** [comment]
An update:  Consistent with my suspicions noted above, stan_jm worked fine on the above model once I deleted all of the "0" cpep values that were highly correlated with the fact (not just the risk) of failure.  This new model gave a credible and highly significant value for eta, confirming that a low level of cpep (but above the lower limits of detection) is highly significantly correlated with risk of subsequent failure, and the estimated groupwise slopes for cpep were more negative than in the separate stan_lmer model by an amount roughly proportional to the frequency of failures.

**Comment by sambrilleman** [comment]
@lhunsicker Great, thanks for letting us know you managed to resolve it! :-)

By the way, fyi, if you get a similar error message in the future and it includes the warning "some chains had errors; consider specifying chains = 1 to debug" then you can specify `chains=1` as an argument to your `stan_jm` call and you will likely get more informative error information about why some of the MCMC chains are crashing... often Stan will tell you something about the chains not being able to initialise or something similar.
