### ISSUE TITLE
posterior_predict fails for stan_glmer if transformations used in formula

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#39]
@Felipe-Osorio is the error thrown when running the code below the one you were referring to?
    
    fit <- stan_glmer(mpg ~ log1p(wt) + (1|cyl), data = mtcars)
    p <- posterior_predict(fit) # ok
    p2 <- posterior_predict(fit, newdata = mtcars[1:10, ])
    Error in `[.data.frame`(newdata, , colnames(frX)) : 
      undefined columns selected

**Comment by Felipe-Osorio** [comment]
that's the one. interestingly also fails if you were to pass in a column named 'log1p(wt)', which is annoying.

**Comment by jgabry** [comment]
Ok thanks, we'll get this sorted out.

**Comment by jgabry** [comment]
I think this was fixed by 763c0850166eaa1eb8058111c61df3a3417383a5
