### ISSUE TITLE
CRAN versions of vignettes are messed up

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#393]
@bgoodri I just noticed that none of the CRAN versions of the vignettes have any output from the code chunk no output anymore (e.g. if you look at https://cran.r-project.org/web/packages/rstanarm/vignettes/count.html
or any of the other vignettes). That is, it looks like none of the code is getting evaluated. I know that we're using that mechanism with `params$EVAL` to avoid evaluating the vignettes on CRAN but shouldn't the output still show up from when they were evaluated locally before submitting?

**Comment by bgoodri** [comment]
I probably generated the vignettes in CRAN-mode. Just pull and we can put
the actual vignettes on the Stan website.

**Comment by jgabry** [comment]
Ok, I got them up on the rstanarm website. I think we should put a link to the rstanarm website version in the cran versions just in case (and in general they’re nicer to read on the rstanarm website). Gonna leave this open until I do that.
