### ISSUE TITLE
rstanarm failing to build in Centos7 'memory not mapped'

### ISSUE THREAD

**Issue by lurch999** [stan-dev/rstanarm#394]
#### Summary:
I'm following instructions here: https://github.com/stan-dev/rstanarm
gcc version 9.2.0
Centos 7

#### Description:
rstanarm failing to build in Centos7 with error 'memory not mapped'

#### RStanARM Version:
Attempting to install 2.19.2

#### R Version:
3.6.0

#### Operating System:
Centos7

#### Reproducible Steps:
export PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin 
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/usr/local/lib64:/usr/lib64
cat ~/.R/Makevars:
 
CXX14FLAGS=-O3 -march=native -mtune=native -fPIC
CXX14=g++ -std=c++11
CXX14STD='-std=c++1y'

In R:
remove.packages("rstan")
if (file.exists(".RData")) file.remove(".RData")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE) 
install.packages("rstanarm")
......
** testing if installed package can be loaded from temporary location
sh: line 1: 21051 Segmentation fault      (core dumped) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/Rtmpms23Cf/file472c7828875c'

 *** caught segfault ***
address 0x20, cause 'memory not mapped'

Traceback:
 1: Module(module, mustStart = TRUE, where = env)
 2: doTryCatch(return(expr), name, parentenv, handler)
 3: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 4: tryCatchList(expr, classes, parentenv, handlers)
 5: tryCatch(Module(module, mustStart = TRUE, where = env), error = function(e) e)
 6: loadModule(m, what = TRUE)
 7: fun(libname, pkgname)
 8: doTryCatch(return(expr), name, parentenv, handler)
 9: tryCatchOne(expr, names, parentenv, handlers[[1L]])
10: tryCatchList(expr, classes, parentenv, handlers)
11: tryCatch(fun(libname, pkgname), error = identity)
12: runHook(".onLoad", env, package.lib, package)
13: loadNamespace(package, lib.loc)
14: doTryCatch(return(expr), name, parentenv, handler)
15: tryCatchOne(expr, names, parentenv, handlers[[1L]])
16: tryCatchList(expr, classes, parentenv, handlers)
17: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
18: library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE)
19: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
20: suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE))
21: doTryCatch(return(expr), name, parentenv, handler)
22: tryCatchOne(expr, names, parentenv, handlers[[1L]])
23: tryCatchList(expr, classes, parentenv, handlers)
24: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        sm <- strsplit(conditionMessage(e), "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && isTRUE(getOption("show.error.messages"))) {        cat(msg, file = outFile)        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
25: try(suppressPackageStartupMessages(library(pkg_name, lib.loc = lib,     character.only = TRUE, logical.return = TRUE)))
26: tools:::.test_load_package("rstanarm", "/usr/lib64/R/library/00LOCK-rstanarm/00new")
An irrecoverable exception occurred. R is aborting now ...
ERROR: loading failed
* removing ‘/usr/lib64/R/library/rstanarm’

The downloaded source packages are in
	‘/tmp/RtmpDRZNZI/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("rstanarm", repos = "https://cloud.r-project.org/",  :
  installation of package ‘rstanarm’ had non-zero exit status

**Comment by lurch999** [comment]
I pored through some older forums and found a suggestion to first remove Rcpp then reinstall rstanarm. This solved the problem, and it successfully compiled.

**Comment by jgabry** [comment]
Sorry for the hassle but glad it's working now!

We should make tips like "remove Rcpp then reinstall Rcpp and then rstanarm" easier to find, but I'm not sure where we should put them. Maybe an installation tips wiki page or something?

**Comment by JazzyPierrot** [comment]
If anybody stumbles upon this issue, I had a similar segfault problem on centos7 and I had to reinstall "Rcpp" AND "rstan"  to make it work (which is done in the first post's reproducible steps but I missed it).
For my case, I suspect discrepancies between gcc versions when installing these packages and "rstanarm".

**Comment by jgabry** [comment]
@JazzyPierrot thanks for sharing. I think discrepancies in gcc version is definitely a possible explanation.
