### ISSUE TITLE
Intercept only models giving wrong results using compound glm functions

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#396]
#### Summary:

In the latest release to 2.19.2 the introduction of the compound glm functions (e.g. bernoulli_logit_glm, poisson_log_glm) to the Stan code has introduced a bug where 
intercept only models give the wrong answer. 

@bgoodri @avehtari I've been digging into this and I think it's a real problem but I can't figure out why it's happening other than that turning off the compound glms fixes it (I don't think they're broken in Stan, just the implementation here). I haven't identified where in the Stan code things are going awry. As soon as we figure this out I think we should submit a patch to CRAN. 

Update: see comment below, seems like a bug in Stan not in rstanarm's implementation

#### Description:

I was alerted to this problem on Discourse: https://discourse.mc-stan.org/t/using-stan-glm-to-estimate-a-proportion/11339

I can confirm that changing the stan code to set `can_do_bernoullilogitglm` to `0` and recompiling fixes the problem, so it seems to have been introduced there. 

I can also confirm that the same is true for poisson. See Reproducible steps, below. 

#### Reproducible Steps:

```
# bernoulli 
y <- c(rep(1, 280), rep(0, 1000 - 280))
x <- rnorm(1000) # i don't include x in model here, but including it fixes the problem
dat <- data.frame(x, y)
fit_glm <- glm(y ~ 1, data = dat, family = binomial())
fit_stan <- stan_glm(y ~ 1, data = dat, family = binomial())

coef(fit_glm)[1]
coef(fit_stan)[1]
rstan::get_posterior_mean(fit_stan$stanfit, pars = "gamma") # messed up

# poisson (haven't checked but probably neg-binom too)
y <- rpois(1000, 5)
x <- rnorm(1000) # i don't include x in model here, but including it fixes the problem
dat <- data.frame(x, y)
fit_glm <- glm(y ~ 1, data = dat, family = poisson())
fit_stan <- stan_glm(y ~ 1, data = dat, family = poisson())

coef(fit_glm)[1]
coef(fit_stan)[1]
rstan::get_posterior_mean(fit_stan$stanfit, pars = "gamma") # messed up
```

If you change count.stan and bernoulli.stan to turn off using the compound glms and recompile rstanarm then this problem goes away and the results are very close between glm and stan_glm.

#### RStanARM Version:
`2.19.2`

**Comment by jgabry** [comment]
Actually, is this a bug in Stan? If I run the following Stan program: 

```stan
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
transformed data {
  matrix[N, 0] X;  // 0 columns
}
parameters {
  real gamma;
  vector[0] beta; // 0 elements 
}
model {
  gamma ~ normal(0, 10);
  target += bernoulli_logit_glm_lpmf(y | X, gamma, beta);
}
generated quantities {
  real test_lpmf = bernoulli_logit_glm_lpmf(y | X, gamma, beta);
}
```

Then `test_lpmf` comes out to `0.0e+00` (i.e., 0) even though `gamma` isn't size 0 and should influence it.

**Comment by avehtari** [comment]
> Actually, is this a bug in Stan? If I run the following Stan program:

Great that you tested this, too.

**Comment by jgabry** [comment]
@avehtari This really does seem like it could be a bug in Stan's compound glm functions. Who is the right person to ask about this? @VMatthijs? @seantalts?

**Comment by avehtari** [comment]
When I tracked who made the PRs for these compound functions, all of them were by @VMatthijs

**Comment by t4c1** [comment]
Matthijs originaly wrote them. Later I did a lot of work optimizing them. I think I know what is probably the bug. All glm implementations have a line like (from mormal_id_glm_lpdf):
```
  if (size_zero(y, x, beta, sigma)) {
    return 0;
  }
```
In intercept only model x and beta have size of 0, so this will just return instead of continuing with correct calculations. I think I can fix this tomorrow.

**Comment by avehtari** [comment]
Here's the minimal changed version which works. Instead of 0 size X and beta, use dummy X, and beta=0.
```
// Bernoulli model
data {
  int<lower=0> N;
  int<lower=0,upper=1> y[N];
}
transformed data {
  matrix[N, 1] X = rep_matrix(0, N, 1); // dummy X
  vector[1] beta = [0]'; // fixed beta=0
}
parameters {
  real gamma;
}
model {
  y ~ bernoulli_logit_glm(X, gamma, beta);
}
```

**Comment by avehtari** [comment]
> I think I can fix this tomorrow.

Great! It would then get to the next Stan release which has feature freeze starting tomorrow and release in one week.

What do we need to do for rstanarm?

**Comment by jgabry** [comment]
Thanks @t4c1. I hadn't seen your response and I opened an issue here: https://github.com/stan-dev/math/issues/1398

**Comment by jgabry** [comment]
> What do we need to do for rstanarm?

I think for now we need to disable this for models that only have an intercept and submit a patch to CRAN as soon as possible so we don't have the wrong inferences for intercept only models. @bgoodri I know it's not ideal to release again so soon, but I really don't think we should have a release out there that is fitting the wrong model if we can fix it and CRAN does make exceptions.
