### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by bholden7** [stan-dev/rstanarm#398]
#### Summary:
Not sure what this message refers to: 
Error in array(STATS, dims[perm]) : 'data' must be of a vector type, was 'NULL' 
after this code:
```{r}
par(mfrow = 1:2, mar = c(5,3.7,1,0) + 0.1, las = 3)
boxplot(sweep(y_rep[,womensrole$gender == "Male"], 2, STATS = 
               womensrole$total[womensrole$gender == "Male"], FUN = "/"), 
        axes = FALSE, main = "Male", pch = NA,
        xlab = "Years of Education", ylab = "Proportion of Agrees")
with(womensrole, axis(1, at = education[gender == "Male"] + 1, 
                      labels = 0:20))
axis(2, las = 1)
with(womensrole[womensrole$gender == "Male",], 
     points(education + 1,  agree / (agree + disagree), 
            pch = 16, col = "red"))
boxplot(sweep(y_rep[,womensrole$gender == "Female"], 2, STATS = 
          womensrole$total[womensrole$gender == "Female"], FUN = "/"), 
          axes = FALSE, main = "Female", pch = NA,
        xlab = "Years of Education", ylab = "")
with(womensrole, axis(1, at = education[gender == "Female"] + 1,
     labels = 0:20))
with(womensrole[womensrole$gender == "Female",], 
     points(education + 1,  agree / (agree + disagree), 
            pch = 16, col = "red"))
```

#### Description:
see above

#### RStanARM Version:
The version of the rstanarm package you are running (e.g., from `packageVersion("rstanarm")`)

#### R Version:
Run on RStudio, 1.2.1335, R version 3.6.1

#### Operating System:
OS Catalina 10.15

**Comment by jgabry** [comment]
Hmm that’s weird. Sorry you’re getting an error. Just to confirm, the model ran successfully but there’s an error when you run the code above using the results? I would have been less surprised if OS X Catalina caused an issue that didn’t let you even run the model successfully (we’ve been seeing some issues since Catalina was released that we’re trying to sort out).

**Comment by bholden7** [comment]
Hi. Thanks for getting back to me. And, btw, I think rstanarm is an incredible (and incredibly useful) package (I did the Data Camp course and I’m trying to go through all your work online).
Alas, no; the model doesn’t run - all I get is the error message.
Your intuition is probably correct - I can run it out of RStudio and it works fine…so maybe it’s Catalina…
Many thanks and keep up the great work!


Billy Holden, PhD
email: billyholden7@gmail.com
mobile: 917.515.4227

**Comment by jgabry** [comment]
Glad you like rstanarm! And glad you can at least run it out of RStudio for the moment. We’ll get a new version released when we sort out Catalina issues. it seems to be affecting lots of people using compiled code, not just Stan so hopefully either we’ll find the solution or someone else will soon and we’ll use it

**Comment by jgabry** [comment]
Closing this old issue since I think it's fixed. If not we can reopen.
