### ISSUE TITLE
add predict method

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#4]

**Comment by bgoodri** [comment]
I wonder if there should be an option for `predict` to return a matrix of posterior predictives and an option to return a vector of point predictions.

**Comment by jgabry** [comment]
That's certainly doable. Are you wondering more whether users would want
it, or more if we want to stick to output that all users will know what to
do with?

**Comment by bgoodri** [comment]
We don't want to give users of this package too many choices, but I think
the predict function is a case where maybe this choice is needed. On one
hand, there is already a fitted function that returns in-sample point
predictions. So, predict could be free to do something else. Also, I think
people who only know how to look at quantiles to see if they include zero
probably won't be calling predict very much.

**Comment by jgabry** [comment]
So if the user selects the option to return the entire y_rep matrix, would
we just ignore if they specify type='link' instead of type='response'?

**Comment by bgoodri** [comment]
On Fri, Jul 10, 2015 at 4:39 PM, Jonah Gabry <notifications@github.com>
wrote:

> So if the user selects the option to return the entire y_rep matrix, would
> we just ignore if they specify type='link' instead of type='response'?
>

I think it is okay to return the posterior distribution of eta if the
posterior predictive option is selected and type='link', even though it is
just posterior and not posterior predictive.

**Comment by jgabry** [comment]
Ok that works. I can write up a draft of the predict method later today or
sometime this weekend.

**Comment by jgabry** [comment]
Actually, it was pretty simple to make a version that (not having tested it too thoroughly yet) seems to do what we want. Check out the newest commit to develop branch ([here](https://github.com/stan-dev/rstanarm/blob/develop/R/predict.R)). 

(For now I called the argument for specifying point predictions vs sims matrix "output" with options "point" and "sims", but that might not be the best choice of names.)

**Comment by jgabry** [comment]
@bgoodri 
An example of something we should think about from the user's perspective:

`predict(glm(y ~ x, family = gaussian), se.fit = TRUE)`

will return the same thing regardless of whether `type='link'` or `type='response'`. The standard errors returned are roughly those that we would return for `predict(stan_glm(same model), se.fit = TRUE)` if we took the `se.fit` to be the column sds of the posterior for `eta`. However, we probably want to take `se.fit` to to be the column sds of `yrep`, which will be larger and probably confusing to the user, but also what we probably should be returning from a Bayesian perspective.  

Thoughts on this?

**Comment by jgabry** [comment]
For the behavior of `predict()` if the model is fit using MCMC, here's what we decided if I remember correctly:

* no `newdata` and `se.fit = FALSE` 
Value: `object$linear.predictors` if `type='link` and `object$fitted.values` if `type='response'`

* no `newdata` and `se.fit = TRUE` 
Value: column means and SDs of `eta`  if `type='link` and error (use `posterior_predict`) if `type='response'`

* `newdata` specified
Value: column means and SDs (if `se.fit`) of `eta` (using `newdata`) if `type='link'` and error (use `posterior_predict`) if `type = 'response'`

That still look good?

**Comment by bgoodri** [comment]
Yes. Conceivably we could get frequentist standard errors using the
posterior means as a point estimate by calling optimHess(), which we are
going to have to do anyway when we support ML. But I think it is fine to
start with what you outlined.

**Comment by bgoodri** [comment]
Upon further review, I think posterior_predict() should "work" even if the user has done optimization (see #9) by drawing from the estimated multivariate normal sampling distribution in the unconstrained space, converting to the contrained space, and so on. There is now preliminary support in stan_glm[_fit] for utilizing the optimizing() method, which includes the estimated variance-covariance matrix of the unconstrained estimates and a basically empty `stanfit` object so that `unconstrain_pars` could be called. But we really need an entirely different logic for the optimization case than is provided by `stanreg`.

**Comment by jgabry** [comment]
Ok that seems like a good idea.

And yeah we'll need to deal with the non-mcmc models separately I guess. We
could just make stanreg handle whatever's thrown at it, but a different
function would be much cleaner and easier to debug/maintain, etc.

**Comment by bob-carpenter** [comment]
The variational inference does the same thing (generating
from multivariate normal, transforming to constrained). 
The only difference is that it uses the variational approximation,
not the Laplace one.

- Bob

**Comment by bgoodri** [comment]
True, but the VB thing already comes with transformed draws from a
multivariate normal, so there is not a whole lot for us to do (except
expose the VB algorithm) that we weren't already doing when MCMC is used.
With optimizing, we have a Hessian but it is not the Hessian for the
parameters we want. So, I think we are going to have to do some Delta
method stuff.

**Comment by andrewgelman** [comment]
I’m not sure if this is what you’re talking about, but for our goal of getting standard errors and uncertainty intervals from point estimation or optimization, I think we should _not_ use any delta method stuff; we should do it all using 1000 (or however many) simulation draws and then transform to get what we need.
A

**Comment by bob-carpenter** [comment]
> On Jul 26, 2015, at 7:25 PM, bgoodri <notifications@github.com> wrote:
> 
> True, but the VB thing already comes with transformed draws from a
> multivariate normal, so there is not a whole lot for us to do (except
> expose the VB algorithm) that we weren't already doing when MCMC is used.

Exactly.  I just meant we can reuse all the code because it's
doing the same thing.

> With optimizing, we have a Hessian but it is not the Hessian for the
> parameters we want. So, I think we are going to have to do some Delta
> method stuff.

I don't even know what a Delta method is, but if it's adjusting
Hessians for change of variables, I'm not sure I want to know.

So for traditional standard errors, do you need the Hessian of the log
density on the constrained space?  Do you somehow reduce the degrees
of freedom?

- Bob


> 
> On Sun, Jul 26, 2015 at 5:44 PM, Bob Carpenter <notifications@github.com>
> wrote:
> 
> > The variational inference does the same thing (generating
> > from multivariate normal, transforming to constrained).
> > The only difference is that it uses the variational approximation,
> > not the Laplace one.
> >
> > - Bob
> >
> >
> >

**Comment by bgoodri** [comment]
That code isn't exposed to R, which is not to say that it shouldn't be in
Stan3, but for the time being, drawing from a multivariate normal
distribution in R is no big deal. I put the transform-the-simulations
method in, but it's a huge relative cost in the sense that it takes a lot
longer to transform the unconstrained simulations (one draw at a time) than
it does to find the optimum and takes up much more memory. But if they are
doing this with a small model the absolute costs are still manageable.

**Comment by jgabry** [comment]
I think this can be closed, right?

**Comment by bgoodri** [comment]
Yes since predict() exists. If there are bugs discovered with it, those can
be separate issues.
