### ISSUE TITLE
df.residual

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#40]
@bgoodri  Is there any reason why we should definitely report residual degrees of freedom? Right now we have a call to `qr` in `stanreg` that is only used to get the rank of `x` for computing `df.residual`. If `x` is really large we probably don't want to compute the QR decomposition in `stanreg` unless we really want to report `df.residual`. What do you think?

**Comment by bgoodri** [comment]
I would say to assume that X is of full-rank unless QR = TRUE, in which case if we do the QR decomposition, we might as well calculate the residual degrees of freedom.

**Comment by jgabry** [comment]
Ok, I think that would be ideal but it's a little tricky because if QR=TRUE
the decomposition is done in `stan_glm.fit` rather than in `stan_glm`.
Currently `stan_glm.fit` only returns a stanfit object, so in order to keep
the rank of the matrix after calling qr we'd need to have `stan_glm.fit`
return a list containing possibly just a stanfit object but also possibly
the stanfit and the rank if QR=TRUE. That seems suboptimal.

**Comment by jgabry** [comment]
@bgoodri Any thoughts on this before the release?

**Comment by bgoodri** [comment]
I would say to make df.residual() return NA_integer_ unless it has been
explicitly set and only explicitly set it when it makes sense to do so.

**Comment by jgabry** [comment]
I have it computing df.residual for models fit using optimization. Otherwise it's NA_integer_. We can change that at some point I guess, but I'm not sure it's particularly useful for anything really. If you're ok with that then we can close this issue.

**Comment by bgoodri** [comment]
Yeah, close it.
