### ISSUE TITLE
Error message from posterior_linpred with beta regression model

### ISSUE THREAD

**Issue by landerso777** [stan-dev/rstanarm#406]
#### Summary:
After updating R and rstanarm, I am getting an error message from posterior_linpred using a multilevel beta regression model. 

#### Description:
Error in (function (optimizer = "nloptwrap", restart_edge = TRUE, boundary.tol = 1e-05,  : 
  unused arguments (tolPwrss = 1e-07, compDev = TRUE, nAGQ0initStep = TRUE, checkControl = list("ignore", "ignore", "ignore", "stop", "ignore", "message+drop.cols", "warning", "stop", "ignore"), checkConv = list(list("ignore", 0.001, NULL), list("ignore", 1e-04), list("ignore", 1e-06)))

I did not get an error message prior to updating R and rstanarm while running similar code, and I don't get the error with a logistic regression model (although it seems to run slow).

#### Reproducible Steps:
```
library(rstanarm)

iris$Petal.Length.std <- iris$Petal.Length/7

SEED = 101

fit.iris <- stan_glmer(Petal.Length.std ~ Petal.Width + (1|Species), family=mgcv::betar(link="logit"), adapt_delta=0.95, data=iris, seed = SEED, chains=3)

ndd <- iris[which(iris$Species=="setosa"),]

P <- posterior_linpred(fit.iris, newdata=ndd, transform=TRUE)
```

#### RStanARM Version:
rstanarm 2.19.2

#### R Version:
R 3.6.1
RStudio 1.1.383

#### Operating System:
Windows 10

**Comment by ewenharrison** [comment]
Hi Martin, 
Many thanks for all your work on this. 
We're deep in Covid-19 work and have hit this error. 
As pointed out in #407 it doesn't occur if random effects are not included in predictions. 
Do you think this will be fixed soon, so we know whether to move this model to rstan.
Many thanks again. 
Ewen

**Comment by martinmodrak** [comment]
Unfortunately, I've never really worked with rstanarm codebase so can't help directly, maybe @jgabry or @bgoodri can help more directly. Also,  before moving to rstan you can consider brms, which works almost the same as rstanarm and AFAIK doesn't have this particular issue. Best of luck!

**Comment by jgabry** [comment]
I think this is finally fixed now. Sorry it took so long to get to this! The fix is now on the master branch and will be included in the next release.

**Comment by landerso777** [comment]
Thank you!

________________________________
