### ISSUE TITLE
gamm and mer examples from vignette fail

### ISSUE THREAD

**Issue by apeterson91** [stan-dev/rstanarm#417]
#### Summary:
As in title. In reproducing the roaches example [here](https://mc-stan.org/rstanarm/articles/glmer.html) the function failed.

#### Description:
Error messages produced from the above are below. I've tried getting other _mer examples to also work to no effect. However, I can get the sampler to work for simple stan_lm/stan_glm function calls. e.g. 
`> stan_lm(hp ~ wt, data = wtcars) #samples as expected.` 
I realize that there have been issues with Catalina, but thought that if the compiler issues were resolved for at least one model type, then they should likely be resolved for others- especially, e.g. stan_glmer, as they use the same root stan file.

```
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: variable does not exist; processing stage=data initialization; variable name=offset_; base type=vector_d  (in '/data/weights_offset.stan' at line 7; included from 'model_count' at line 16)
 [origin: unknown original type]
failed to create the sampler; sampling not done
Error in new_CppObject_xp(fields$.module, fields$.pointer, ...) : 
  Exception: variable does not exist; processing stage=data initialization; variable name=offset_; base type=vector_d  (in '/data/weights_offset.stan' at line 7; included from 'model_count' at line 16)
 [origin: unknown original type]
failed to create the sampler; sampling not done
here are whatever error messages were returned
[[1]]
Stan model 'count' does not contain samples.

[[2]]
Stan model 'count' does not contain samples.

Error in check_stanfit(stanfit) : 
  Invalid stanfit object produced please report bug
In addition: Warning message:
In .local(object, ...) :
  some chains had errors; consider specifying chains = 1 to debug
```

#### Reproducible Steps:
// New Rstudio session
```
devtools::install_github("stan-dev/rstanarm")
data("roaches")

roaches$roach1 <- roaches$roach1 / 100
roaches$log_exposure2 <- log(roaches$exposure2)
post <- stan_gamm4(
  y ~ s(roach1) + treatment + log_exposure2,
  random = ~(1 | senior),
  data = roaches, 
  family = neg_binomial_2, 
  QR = TRUE,
  cores = 2,
  chains = 2, 
  adapt_delta = 0.99,
  seed = 12345
)
```

#### RStanARM Version:
rstanarm 2.19.3

#### R Version:
3.6.1
#### Operating System:
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

**Comment by bgoodri** [comment]
I think it will be okay if you get the versions of everything in sync with
```
install.packages(c("StanHeaders", "rstan", "rstanarm"), type = "source")
```

**Comment by apeterson91** [comment]
That did it. Thought I had everything updated, but maybe I hadn't installed them from source...
