### ISSUE TITLE
stanreg-methods.R not parsing

### ISSUE THREAD

**Issue by petestmarie** [stan-dev/rstanarm#42]
Some weirdness in the latest edit around lines 424-432.

commit b2c73f0

**Comment by jgabry** [comment]
Thanks, looks like it got screwed up when attempting to mix merge conflicts in the most recent commits. We'll get it sorted out.

**Comment by jgabry** [comment]
Ok I think this is fixed but that commit that messed this up also seems to have introduced a bug in stan_glmer that causes some failed tests. I'm opening a separate issue for that.
