### ISSUE TITLE
errors after rstan update

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#44]
@bgoodri 

With rstan 2.9 I'm getting the following error when running

    stan_glm(mpg ~ wt, data = mtcars)

sampling seems to proceeds ok, bun then

    Error in dim(sssf) <- c(n2, object@sim$chains, length(tidx)) : 
    dims [product 20000] do not match the length of object [40000]

which looks like it's coming from `extract` as defined in the `stanfit-class.R` file in rstan.

**Comment by bgoodri** [comment]
Yeah. I got that error once. You have to install rstanarm before you do
check.

**Comment by jgabry** [comment]
Ok I'll give that a try and then close the issue if resolved

**Comment by jgabry** [comment]
Ok that worked. Thanks.

**Comment by bgoodri** [comment]
BTW, that error was precipitated by rstanarm making use of the new
save_warmup = FALSE option to rstan. So, if there are any places in
rstanarm or shinystan where we assume unconditionally that the warmup is
available, we should fix them. But the tests seem to pass once you get
rstanarm installed.

**Comment by jgabry** [comment]
Yeah fixing that is part of the shinystan update, which I just submitted.

**Comment by bgoodri** [comment]
Does win-builder have the latest shinystan on it?

**Comment by jgabry** [comment]
Yes, http://win-builder.r-project.org/FQ8t47Q8rjgy/.  I also just got the
confirmation from Kurt that it was accepted for CRAN.

**Comment by jgabry** [comment]
Actually, this is the right version: http://win-builder.r-project.org/UfUW8YCyWEjg/

**Comment by bgoodri** [comment]
Ah, now I get it. The shinystan you uploaded is on R-release rather than
R-devel. I think the latter is preferable for testing, but it will
presumably pick up the CRAN version soon.

**Comment by jgabry** [comment]
I tested both R-release and R-devel.

**Comment by jgabry** [comment]
But I think I tested it on R-devel before bumping the version from 2.0.2 to
2.1.0. I realized I forgot to bump the version so I did that before testing
on R-release, but that's the only difference between the two versions on
win-builder.

**Comment by bgoodri** [comment]
Hmm. I can only get it to take rstanarm on R-release and then we have these
errors

http://win-builder.r-project.org/atvNPMrdOv7F

**Comment by bgoodri** [comment]
Ah, that would explain it.

**Comment by jgabry** [comment]
Sorry for the confusion.

**Comment by bgoodri** [comment]
It is mostly ok now.

http://win-builder.r-project.org/T6a1uSDd4WT2
