### ISSUE TITLE
Incorrect model matrix with user-supplied contrasts

### ISSUE THREAD

**Issue by rvlenth** [stan-dev/rstanarm#445]
#### Summary:
The `model.matrix()` function returns the wrong model matrix when the user supplies contrasts

#### Description:
Above says it all. See the example below. This is sort of related to #444, but I think it is a separate issue

#### Reproducible Steps:
(same example is #444 )
```r
library("rstanarm")
m1 <- stan_glm(breaks ~ wool * tension, data = warpbreaks,
               prior = rstanarm::student_t(3, 0, 3, autoscale = FALSE), 
               contrasts = list(wool = "contr.sum", tension = "contr.sum"))

model.matrix(m1)
##   (Intercept) woolB tensionM tensionH woolB:tensionM woolB:tensionH
## 1            1     0        0        0              0              0
## 2            1     0        0        0              0              0
##     ...
## 53           1     1        0        1              0              1
## 54           1     1        0        1              0              1
## attr(,"assign")
## [1] 0 1 2 2 3 3
## attr(,"contrasts")
## attr(,"contrasts")$wool
## [1] "contr.treatment"
## 
## attr(,"contrasts")$tension
## [1] "contr.treatment"
```
Note that the `contrasts` attribute does not match the user-specified contrasts.

#### RStanARM Version:
2.19.3

#### R Version:
4.0.1

#### Operating System:
Windows 10

**Comment by rvlenth** [comment]
Anybody looked at this yet????

**Comment by jgabry** [comment]
This did turn out to be fixed by the same fix as for #444. This PR should fix both issues: https://github.com/stan-dev/rstanarm/pull/459

**Comment by rvlenth** [comment]
Thanks so much!

--Russ

**Comment by singmann** [comment]
@jgabry  Also a big thank you from me. This solves all problems of my (in development) [`stanova`](https://github.com/bayesstuff/stanova) package. So once the new `rstanarm` version is on its way to CRAN, I can also submit.
