### ISSUE TITLE
tag release?

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#447]
@bgoodri Can we tag a release? Do you have anything locally that still needs to be pushed?

**Comment by bgoodri** [comment]
Pushed v2.21.1

**Comment by jgabry** [comment]
Ok I'll tag the release and update gh-pages for mc-stan.org/rstanarm

**Comment by jgabry** [comment]
@bgoodri I don't think the latest commits for v2.21.1 are on master. Can you add them before I update the website?

**Comment by bgoodri** [comment]
pushed again

**Comment by jgabry** [comment]
That doesn't seem to be working. They're just empty commits: see https://github.com/stan-dev/rstanarm/commit/75bf5cf70416c5fc3ddd00ecc858d34d4b5fee00

**Comment by jgabry** [comment]
never mind, sorry. now i see it.
