### ISSUE TITLE
Stan syntax error when installating feature/survival 

### ISSUE THREAD

**Issue by proof-by-accident** [stan-dev/rstanarm#451]
#### Summary:
Trying to install the `feature/survival` branch, but getting Stan errors.

#### Description:
I'm running `devtools::install_github('stan-dev/rstanarm@feature/survival')` and receiving the following error:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
Void function cannot return a value.
 error in '/functions/mvmer_functions.stan' at line 345, column 19
 included from 'model_jm' at line 12
  -------------------------------------------------
   343:       target += student_t_lpdf(gamma | df, mean_, scale);
   344:     /* else dist is 0 and nothing is added */
   345:     return target();
                          ^
   346:   }
  -------------------------------------------------

PARSER EXPECTED: ";"
Error in rstan::stanc(file, allow_undefined = TRUE, obfuscate_model_name = FALSE) : 
  failed to parse Stan model 'jm' due to the above error.
Calls: make_cc -> <Anonymous>
Execution halted
make: *** [Makevars:23: stan_files/jm.cc] Error 1
rm stan_files/count.cc stan_files/bernoulli.cc stan_files/binomial.cc stan_files/continuous.cc
ERROR: compilation failed for package ‘rstanarm’
* removing ‘/home/peter/R/library/rstanarm’
Error: Failed to install 'rstanarm' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpt80ko5/file8bbf968b578aa/rstanarm_2.21.2.tar.gz’ had non-zero exit status

```
Looks like it's a pretty standard Stan syntax error somewhere in `mvmer_functions.stan`, maybe a hanging paren or something? Interestingly when I run just `devtools::install_github('stan-dev/rstanarm')` everything works fine, so I believe it's a specifically a problem within the `feature/survival` branch. Any chance of a quick workaround for this?  

#### RStanARM Version:
Trying to install version 2.21.2

#### R Version:
R 4.0.1

#### Operating System:
Manjaro 20.0.3 Lysia

**Comment by jgabry** [comment]
Thanks for reporting this. I'm also get this error but I'm not sure why. 

@bgoodri or @sambrilleman Any idea what's going on here? This seems to be coming from a file included by `jm.stan` and not `surv.stan`. But when I go look at the function in question (/functions/mvmer_functions.stan' at line 345) it's this

```stan
  void gamma_lp(real gamma, int dist, real mean_, real scale, real df) {
    if (dist == 1)  // normal
      target += normal_lpdf(gamma | mean_, scale);
    else if (dist == 2)  // student_t
      target += student_t_lpdf(gamma | df, mean_, scale);
    /* else dist is 0 and nothing is added */
    return target();
  }
```

which looks like it should be syntactically correct. So I don't know why the parser thinks there's a missing semicolon.

**Comment by nohemihuanca** [comment]
I am facing the same error any idea how to do a work around?

**Comment by jgabry** [comment]
@nohemihuanca Not quite yet but working on it.

**Comment by proof-by-accident** [comment]
Oh looking at the code chunk @jgabry posted seems like the problem is that the `gamma_lp` func has return type `void` when it should be returning `real` (since it calls `return target();`). My guess is that someone was changing those functions over but forgot to adjust the return type from `master` or something. Changed `void` to `real` in my own [fork](https://github.com/proof-by-accident/rstanarm/tree/feature/survival) and it installs fine. No guarantee that it doesn't break something downstream, but if anyone wants a cheapo fix it's an option.

**Comment by jgabry** [comment]
@proof-by-accident Exactly! Was about to say the same thing. 

The parser error about a missing semicolon is wrong here. If I take the function in question and try to compile it with CmdStanR then it gives me a different error which makes a lot more sense: 

```
Expression return statements may only be used inside returning function definitions.
```

**Comment by proof-by-accident** [comment]
Great minds think alike!

**Comment by jgabry** [comment]
I just pushed the fix to the feature/survival branch. Sounds like it works for @proof-by-accident but @nohemihuanca can you try again and see if it works now? 

Also, @sambrilleman when you have a chance can you check that my fix doesn't cause any issues with anything else? I'm guessing it doesn't, but just in case...

**Comment by nohemihuanca** [comment]
@jgabry I tried and worked fine. Thank you all!

**Comment by jgabry** [comment]
Great, glad it's working

**Comment by sambrilleman** [comment]
@jgabry @proof-by-accident Thanks for resolving this! 😀
