### ISSUE TITLE
log_lik() with newdata is sometimes wrong for stan_polr()

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#455]
@bgoodri There's a few spots where I think `log_lik()` is doing the wrong thing for `stan_polr()` models, but I'm not 100% sure of the fix, so I have a few questions for you.

For `stan_polr()`, if `newdata` is specified to `log_lik()` (which it is when doing reloo or kfold), then errors can occur here

https://github.com/stan-dev/rstanarm/blob/709d0db9000fb53b15f0c8f93aef755e18c04209/R/log_lik.R#L323-L326

because `y` is referring to `y` from `newdata`, which might only have two unique values while the original y has more than 2 levels. In that case `stanmat[, zetas, drop = FALSE]` doesn't find the right columns because `patt` is wrong (`patt` thinks it's a binary model when it isn't). 

So, a few questions: 

1. Should we just always define `patt`

https://github.com/stan-dev/rstanarm/blob/709d0db9000fb53b15f0c8f93aef755e18c04209/R/log_lik.R#L323

using the original `y` and not the `y` from `newdata`? 

2. Should `max_y` also always be defined using the original data and not newdata? This is important because in `ll_polr_i` does `J <- draws$max_y` and then uses `J` when computing the log-lik:

https://github.com/stan-dev/rstanarm/blob/709d0db9000fb53b15f0c8f93aef755e18c04209/R/log_lik.R#L463-L469

If you want to actually see this bug in action, first pull the recent commits to master (this bug isn't apparent until you pull in changes fixing another error that would happen first) and then run the `stan_polr()` model provided in this discourse post (data provided in post): https://discourse.mc-stan.org/t/loo-with-k-threshold-error-for-stan-polr/17052/6

**Comment by bgoodri** [comment]
We should figure out the number of potential levels from the number of cutpoints that were estimated.

**Comment by jgabry** [comment]
So is `draws$max_y <- max(y)` supposed to actually be max(y) (even if from newdata) or always fixed at total number of levels in original y?

**Comment by bgoodri** [comment]
draws$max_y should be ncol(zeta) + 1 or something like that.
