### ISSUE TITLE
posterior_survfit should throw an error when newdataEvent is specified

### ISSUE THREAD

**Issue by sambrilleman** [stan-dev/rstanarm#458]
#### Summary:

Predictions for `stan_surv` and `stan_jm` models are generated using `posterior_survfit` although they have different methods called via the generic method.

If providing new data then the function takes argument:

- `newdata` for predictions for `stan_surv` models
- `newdataEvent` for predictions for `stan_jm` models

If someone calls `posterior_survfit.stansurv()` and specifies the `newdataEvent` argument by mistake, this isn't caught as an error. Instead the argument is accepted (via `...`) and silently goes unused and the estimation dataset is used in the predictions instead of the new data. This is dangerous. We should probably do the following:

- throw an error in `posterior_survfit.stansurv()` if the user specifies `newdataEvent` instead of `newdata`.
- throw an error in `posterior_survfit.stanjm()` if the user specifies `newdata` instead of `newdataLong` / `newdataEvent`.

**Comment by sambrilleman** [comment]
This should now be resolved on a working branch, and should close when this commit is merged: https://github.com/stan-dev/rstanarm/commit/99eea89f235db64fb3ca72a23ed4204715f2ca71

**Comment by jgabry** [comment]
@sambrilleman Just going through issues seeing if we can close any. Did your branch for this end up getting merged? If so I'll close this, if not let me know if we need to review something. Thanks!

**Comment by sambrilleman** [comment]
So I think the reason for my slightly cryptic comment above was that I knew that commit would close the issue on merge, but because it is related to stan_surv, it wouldn't get merged into master for a long time.

As to why I haven't merged that commit into the `feature/survival` branch I'm not sure, maybe I wanted to get that branch in sync with the binary we are hosting. Anyway, can't recall, but I will merge it now.

**Comment by sambrilleman** [comment]
Ok, I've merged the fix for this into the `feature/survival` branch (via #526) so I think we can just close this manually since it's resolved on what is effectively the master branch for stan_surv at the moment.

**Comment by jgabry** [comment]
> Ok, I've merged the fix for this into the `feature/survival` branch (via #526) so I think we can just close this manually since it's resolved on what is effectively the master branch for stan_surv at the moment.

Thanks, and yeah closing makes sense
