### ISSUE TITLE
posterior prediction following stan_gamm4

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#46]
Currently, there is just a stub that throws an error saying it is unimplemented (unless you are only doing in-sample prediction). The `predict.gam()` function in the mgcv package has the complicated stuff for handling the smooth terms when `newdata` is specified and if `type = "lpmatrix"`, it returns the necessary matrix of predictors rather than the predictions. But we need to dig into the details of it to make sure we are multiplying the correct columns by the correct margins of the posterior.

**Comment by jgabry** [comment]
resolved by #131
