### ISSUE TITLE
Effective Number of Parameters in kfold

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstanarm#460]
#### Summary:
Implement effective number of parameters in kfold.

#### Description:
@avehtari noted that neither rstanarm nor brms computed the effective number of parameters (2nd row in the loo estimates slot) in `kfold`. Since we couldn't think of a reason, why we shouldn't compute it, I added it to brms (https://github.com/paul-buerkner/brms/blob/master/R/kfold.R line 260 ff). This implementation could be used to quickly implement it in rstanarm as well.

**Comment by jgabry** [comment]
Thanks!
