### ISSUE TITLE
stan_glmer() error on Catalina

### ISSUE THREAD

**Issue by bk568** [stan-dev/rstanarm#464]
#### Summary:
I'm trying to fit a model using stan_glmer() and I'm getting an error message.

#### Description:
I am experiencing a very similar issue to the one described [here](https://github.com/stan-dev/rstanarm/issues/446) and [here](https://discourse.mc-stan.org/t/new-user-struggling-to-get-rstanarm-running/13151/2) and I would be very grateful if you could help. I tried the suggested fixes from those pages, but they didn't work.
When I try to fit a model using stan_glmer(), I get the following error message:

`SAMPLING FOR MODEL 'continuous' NOW (CHAIN 1).`
`Chain 1: `
`Chain 1: Gradient evaluation took 0.000121 seconds`
`Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 1.21 seconds.`
`Chain 1: Adjust your expectations accordingly!`
`Chain 1: `
`Chain 1: `
`Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)`
`[1] "Error in sampler$call_sampler(args_list[[i]]) : "`
`[2] "  c++ exception (unknown reason)"`               
`error occurred during calling the sampler; sampling not done`
`Error in check_stanfit(stanfit) : `
  `Invalid stanfit object produced please report bug`
`Error in dimnamesGets(x, value) : `
 ` invalid dimnames given for “dgCMatrix” object`

The same types of model worked perfectly on my previous computer but I've been experiencing these issues since I switched to Catalina on my new Mac.

#### RStanARM Version:
‘2.19.2’

#### R Version:
"R version 3.6.0 (2019-04-26)"

#### Operating System:
macOS Catalina Version 10.15.6

**Comment by jgabry** [comment]
Sorry for the slow reply! I was just going through rstanarm issues and noticed nobody responded. Are you still having this problem? 

> I am experiencing a very similar issue to the one described [here](https://github.com/stan-dev/rstanarm/issues/446) and [here](https://discourse.mc-stan.org/t/new-user-struggling-to-get-rstanarm-running/13151/2) and I would be very grateful if you could help. I tried the suggested fixes from those pages, but they didn't work.

Hmm, my suggestions would have been the ones from those links, so if you tried all that and it didn't help them I'm not sure. @bgoodri do you have any other ideas?

**Comment by bk568** [comment]
No worries and thanks for responding. Yes, unfortunately I'm still having the same issue.

**Comment by jgabry** [comment]
We'll see if @bgoodri has any other suggestions, but one option could be to upgrade to the latest version of R, which should allow you to install the Mac binary for the latest version of rstanarm (v2.21.1) . I understand if you're hesitant to upgrade R though.

**Comment by bgoodri** [comment]
For Catalina, you have to build a lot of packages from source with exactly
the right ~/.R/Makevars . I would just download R 4.x.
