### ISSUE TITLE
Minor suggestion for VI: don't message about QR when only one predictor

### ISSUE THREAD

**Issue by DominiqueMakowski** [stan-dev/rstanarm#469]
``` r
model <- rstanarm::stan_glm(mpg ~ disp, data = mtcars, algorithm = "meanfield", refresh=0)
#> Setting 'QR' to TRUE can often be helpful when using one of the variational inference algorithms. See the documentation for the 'QR' argument.
```

<sup>Created on 2020-09-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The message suggests to set QR to TRUE but then when once tries it errors. It's a minor thing but could avoid unnecessary confusion ☺️

**Comment by jgabry** [comment]
Thanks, yeah I think you're right we should skip the message in this case. Definitely better to avoid the unnecessary confusion.
