### ISSUE TITLE
Check that y is the same for model comparison (loo or waic)

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#47]
The `compare` function in the loo package checks that models have the same number of observations, but we can also check that the outcome variable is the same. This would probably require a wrapper around `loo::compare` that first does this check, which means rstanarm would have its own model comparison function, instead of users just using the loo package. But I'm not sure that doing this check is worth adding a function since `compare`'s check for the number of observations will catch almost all cases of y being different.

**Comment by avehtari** [comment]
I know it's difficult to check that the same y is used, and I don't try to say that it should be made, but just as an example, it's common that people try to compare, e.g,  models
 y ~ normal(mu1,sigma1)
and
 z ~ normal(mu2,sigma2), where z<-log(y)
which ignores the Jacobian, and the check would help. And the correct second model would be
 y ~ lognormal(mu2,sigma2)

**Comment by bgoodri** [comment]
rstanarm got rejected due to numerical failures in the test, so go ahead and put this check in ASAP

**Comment by jgabry** [comment]
This is going to be harder than I thought, because `compare` takes objects created by `loo` as its inputs and those don't have information about the response variable. So, we'd either need a function that servers as a wrapper not only around `compare` but also around `loo.stanreg` (so that we have the loo information and the response variable information available simultaneously), or we'd need to modify the objects returned by `loo.stanreg` so that they contain information about the response (possibly saved as additional attributes?). The best method isn't obvious to me so, unless there's an obvious way to do this that I'm just not thinking of, I guess we should save this for the next release so we can figure out a decent way to do it.

**Comment by bgoodri** [comment]
OK. I was about to reupload without it anyway.

**Comment by jgabry** [comment]
Ok. Were the failures just due to using multiple cores? It's strange that
if it passes locally for me, locally for you, on travis, and on win-builder
that it could then somehow not pass on cran.

**Comment by bgoodri** [comment]
Yes, they were errors due to nodes not finding the rstanarm namespace
rather than numerical failures that I initially guessed.

**Comment by avehtari** [comment]
If you decide to save information about the response, save only hash of the response. In generalyou shouldn't force response variables to be exactly same because if the other response variable is transformation of the other _and_ the modeler has taken the into account the Jacobian of the transformation in the Stan program, but maybe in rstanarm you can assume that the response variables should be same for a valid comparison.

**Comment by jgabry** [comment]
That's a good point, but you're right that with rstanarm there's not really
a mechanism for the user to take that approach. So I think the y variables
should really have to be the same  for any comparisons to be
meaningful when using rstanarm (maybe there's a few rare exceptions).

Basically I think we should just guard against users trying to compare the
same models fit to y and log(y), and things of that sort.

**Comment by bgoodri** [comment]
Should we also check that the likelihood function is the same in rstanarm? Say if someone does `family = Gamma` and `family = inverse.gaussian` with the same `formula` and `data`?

**Comment by jgabry** [comment]
Yeah probably a good idea. I think we can basically require that the y
variables are all.equal and the families are identical (in R's sense of
all.equal and identical).

Although to do any of this requires adding a model comparison function to
rstanarm that wraps around loo::compare instead of just using loo::compare
directly. I can add that if we want to do this. Maybe compare_models()?

**Comment by bgoodri** [comment]
Can we just have a `compare()` function in rstanarm that possibly masks
`loo::compare()` but calls `loo::compare()` after doing the checks?

**Comment by jgabry** [comment]
Yes but it will definitely mask or be masked by loo's compare and I'd
prefer to avoid that.

**Comment by bgoodri** [comment]
Is there any reason why someone using rstanarm would need to do
library(loo) ? I'm not sure masking in this case is as bad as the other
cases we've had to deal with.

**Comment by jgabry** [comment]
If they also want to use compare after using rstan + loo, which applies to
people like me and you and a bunch of other users, although not all and
perhaps not the majority.

We would need compare to accept stanreg objects to do these checks on y and
family but loo's compare accepts the results from calling loo or waic.

**Comment by bgoodri** [comment]
I guess it is best to have a compare_models() function that takes stanreg
objects and stop reexporting compare.

**Comment by jgabry** [comment]
Ok
