### ISSUE TITLE
Wrong fixed effects estimates when running stan_glm without an intercept

### ISSUE THREAD

**Issue by paul-buerkner** [stan-dev/rstanarm#49]
I get weird fixed effects estimates when fitting a model without an intercept:

```R
library(rstanarm)
devtools::install_github("paul-buerkner/brms")
library(brms)
foo1 <- stan_glm(mpg ~ -1 + ., data=mtcars, chains=2, iter=2000, warmup=500)
foo1

foo2 <- brm(mpg ~ -1 + ., data=mtcars, chains=2, iter=2000, warmup=500)
foo2

foo3 <- glm(mpg ~ -1 + ., data = mtcars)
summary(foo3)
```
The results of `foo2` and `foo3` closely match each other while `foo1` produces very different results. Especially the  `MD_SD` (and `SD`) estimates are a bit off. This may be a result of centering the fixed effects design matrix X regardless of whether an intercept is present or not. I believe that centering is invalid in models without an intercept (at least when not corrected otherwise) but I may be mistaken.

**Comment by jgabry** [comment]
Thanks for catching that.

**Comment by bgoodri** [comment]
This needs to be reopened.
