### ISSUE TITLE
posterior_predict() and posterior_epred() return objects of different classes

### ISSUE THREAD

**Issue by davidkane9** [stan-dev/rstanarm#490]
#### Summary:
posterior_predict() and posterior_epred() return objects of different classes. Shouldn't they produce objects of the same class given that what they both return are draws from a posterior probability distribution?

#### Reproducible Steps:
``` r
suppressPackageStartupMessages(library(rstanarm))

fit_1 <- stan_glm(formula = mpg ~ cyl,
                  data = mtcars,
                  refresh = 0)

pp <- posterior_predict(fit_1)
class(pp)
#> [1] "ppd"    "matrix" "array"

pe <- posterior_epred(fit_1)
class(pe)
#> [1] "matrix" "array"
```

<sup>Created on 2020-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I much prefer the behavior of posterior_epred(). Matrices are easy to deal with. Objects of class ppd are not. But is there any reason for one function to return a matrix and one a ppd? That behavior makes teaching hard!

**Comment by jgabry** [comment]
Yeah I agree with you. To be honest I forgot that we had the "ppd" class. `posterior_predict()` is much older than `posterior_epred()` and at the time we did `posterior_predict()` I think we had the idea that we would add more attributes to the object and that a class in addition to "matrix" would be useful for defining methods. But we never ended up adding any additional attributes or doing anything else that would benefit from using a separate class. We do have methods for  `predictive_error()` and `predictive_interval()` that accept the "ppd" object as input, but those could be redefined just as methods for matrices without the special class. 

As long as removing the "ppd" class doesn't break any packages that use rstanarm (or at least any CRAN ones that we can do reverse dependency checks on) I'd be happy to get rid of it.

**Comment by davidkane9** [comment]
That would be great! Objects of class ppd are only confusing to students and require some tricky-for-students code to get rid of.
