### ISSUE TITLE
stan_biglm errors after switch to biglm::coef

### ISSUE THREAD

**Issue by jgabry** [stan-dev/rstanarm#498]
@bgoodri Commit e3f45fac8d1b79b0c4a8734f04c80aee4322469d causes `stan_bigm` to error and r cmd check to complain (because there's no `coef` exported from biglm).

**Comment by jgabry** [comment]
@bgoodri Just a reminder that stan_biglm is still broken because `biglm::coef()` doesn't exist. 

```r
biglm <- biglm(mpg ~ wt + qsec + am, data = mtcars)
xbar <- colMeans(mtcars[,c("wt", "qsec", "am")])
y <- mtcars$mpg
ybar <- mean(y)
s_y <- sd(y)
post <- stan_biglm(biglm, xbar, ybar, s_y)
```
```
Error: 'coef' is not an exported object from 'namespace:biglm'
```

This is causing a warning in R cmd check on R-devel (seems to just be note on R-release) but more importantly the function doesn't run.

**Comment by bgoodri** [comment]
Yeah, we need to copy the biglm:::coef.biglm method
