### ISSUE TITLE
Missing images in cran vignettes

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#50]
See, for example,
https://cran.rstudio.com/web/packages/rstanarm/vignettes/binomial.html
I can't see any images (just the broken image link symbols)

I just noticed that this was mentioned in the release announcement, but I'll leave this issue here for those who don't read release notes...

**Comment by jgabry** [comment]
Yeah, thanks for opening an issue. We're not sure yet why the images in vignettes hosted online aren't rendering, but we can leave this issue open until that's sorted out. 

Thankfully, if you install the package from CRAN then all the images should be there when you open the vignettes on your own computer.

**Comment by yihui** [comment]
I have fixed it in #53.
