### ISSUE TITLE
Documentation of prior for covariance of group-specific terms

### ISSUE THREAD

**Issue by fweber144** [stan-dev/rstanarm#502]
#### Summary:
There might be a typo in the documentation concerning the parameterization of the prior for the covariance of group-specific terms.

#### Description:
[The documentation](https://mc-stan.org/rstanarm/articles/glmer.html) says:

> In the case where 𝚺 is 1×1, this shape parameter is the cross-group standard deviation in the parameters and its square is the variance.

Shouldn't this read something like

> In the case where 𝚺 is 1×1, 𝜏 is the cross-group standard deviation in the parameters and its square is the variance (so the Gamma prior with its shape and scale directly applies to the cross-group standard deviation in the parameters).

?

#### Reproducible Steps:
Not applicable.

#### RStanARM Version:
2.21.1

#### R Version:
Not applicable.

#### Operating System:
Not applicable.

**Comment by jgabry** [comment]
Just noticed nobody responded to this, sorry! I think you're correct that this is a typo and it should be referring to tau (whereas now it reads as if it's referring to the shape parameter of the gamma). @bgoodri Do you agree?

**Comment by bgoodri** [comment]
Yes

**Comment by jgabry** [comment]
Ok this is fixed on the master branch and on the website now. Thanks @fweber144!
