### ISSUE TITLE
Installation fails on R-4.0.4 Ubuntu 20.04

### ISSUE THREAD

**Issue by maxbiostat** [stan-dev/rstanarm#507]
#### Summary:
Cannot install with either `install.packages()` or `remotes::install_github()`

#### Description:
Installation fails, presumably because of something to do with the survival models

#### Reproducible Steps:
```
> install.packages("rstanarm")
...
/home/max/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp:22:56:   required from ‘double stan::mcmc::dense_e_metric<Model, BaseRNG>::T(stan::mcmc::dense_e_point&) [with Model = model_jm_namespace::model_jm; BaseRNG = boost::random::additive_combine_engine<boost::random::linear_congruential_engine<unsigned int, 40014, 0, 2147483563>, boost::random::linear_congruential_engine<unsigned int, 40692, 0, 2147483399> >]’
/home/max/R/x86_64-pc-linux-gnu-library/4.0/StanHeaders/include/src/stan/mcmc/hmc/hamiltonians/dense_e_metric.hpp:21:10:   required from here
/home/max/R/x86_64-pc-linux-gnu-library/4.0/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type’ {aka ‘__vector(2) double’} [-Wignored-attributes]
make: *** [/usr/local/lib/R/etc/Makeconf:179: stan_files/jm.o] Error 1
rm stan_files/jm.cc
ERROR: compilation failed for package ‘rstanarm’
* removing ‘/home/max/R/x86_64-pc-linux-gnu-library/4.0/rstanarm’
```

#### R Version:
```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C          
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.4 tools_4.0.4    tcltk_4.0.4   
```

#### Operating System:

Ubuntu 20.04.2 LTS

[errorFile.txt](https://github.com/stan-dev/rstanarm/files/6221639/errorFile.txt)

**Comment by sfd99** [comment]
**rstanarm pkg - Installation fails in latest Rstudio/Ubuntu 20.04**

**Same problem as Max had, here.**
Installation in Rstudio goes on for hours,
then _fails_.

What's missing / wrong with this?
Author? ...
Anyone's guess / opinion / pointer ?...

**sfd99
San Francisco
Ubuntu 20.04.2 LTS, latest R and Rstudio.**

**Comment by maxbiostat** [comment]
![image](https://user-images.githubusercontent.com/2875083/114445678-bb0d0080-9ba6-11eb-85e6-28a5439cc113.png)

**Comment by sfd99** [comment]
**_Hi Max,_**

I deleted my post,
(which you show displayed above),
because **rstanarm** pkg
took a very long time,
but it finally installed and works 100% OK.
_Without any problems._

Hope the author
can help you, 
when he sees your post.

**SFd99**

**Comment by maxbiostat** [comment]
I'm going to close this ticket because I no longer have access to the machine where this problem was observed. And I managed to install cleanly (if slowly) in a nearly identical system. I guess it had something to do with my other Stan-related libraries.
