### ISSUE TITLE
Conflict in R2 function with package 'caret'

### ISSUE THREAD

**Issue by waynefoltaERI** [stan-dev/rstanarm#51]
I realize that you can't avoid all possible conflicts, but just wanted to let you know that R package `caret` also defines a function `R2`, which causes really puzzling errors with `stan_lm`. I don't have a good alternative (you might want to rename `hs`, etc, as well).

**Comment by bgoodri** [comment]
I think we'll just have to live with the name conflicts for now. When we do rstan 3.0, we are going to break a lot of user-facing stuff, and if so, then we might rename somethings in rstanarm. But let's cross that bridge when we get there. Thanks for bringing this to our attention though.
