### ISSUE TITLE
Development version fails to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by tmalsburg** [stan-dev/rstanarm#512]
#### Summary:
Installing the development version fails on Ubuntu 20.04 with R 3.6.3.
  
#### Description:
The error message at the end of the trace is:
```
make: *** [/usr/lib/R/etc/Makeconf:175: stan_files/mvmer.o] Error 1
rm stan_files/jm.cc stan_files/binomial.cc stan_files/lm.cc stan_files/continuous.cc stan_files/bernoulli.cc stan_files/polr.cc stan_files/count.cc stan_files/mvmer.cc
ERROR: compilation failed for package ‘rstanarm’
* removing ‘/home/malsburg/R/x86_64-pc-linux-gnu-library/3.6/rstanarm’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpayiOLb/file270684ca80d23/rstanarm_2.21.2.tar.gz’ had non-zero exit status
```

I have no problems installing other R packages.

#### Reproducible Steps:
- Start new R shell.
- Then enter 
``` R
Sys.setenv(MAKEFLAGS = "-j4") # change 4 to however many cores you can/want to use to parallelize install 
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("stan-dev/rstanarm", INSTALL_opts = "--no-multiarch", force = TRUE)
```

#### RStanARM Version:
Current development version: dee0a2d45bf42b2df791072041151b753edd6af9

#### R Version:
3.6.3

#### Operating System:
Ubuntu 20.04.2 LTS

**Comment by andrjohns** [comment]
If you haven't already, can you complete the installation instructions for RStan first ([link to those here](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started)) and verify that you can install RStan without any issues?

If you've already completed those steps, can you post more of the error log? Theres not enough there to see what the issue was

**Comment by tmalsburg** [comment]
Sorry should have mentioned: Rstan (and brms and ulam) are working fine.

**Comment by tmalsburg** [comment]
Just to be save, I reinstalled RStan following the instructions and verified that it's working (it is).

**Comment by tmalsburg** [comment]
Error log:

[error.log](https://github.com/stan-dev/rstanarm/files/6435582/error.log)

Unfortunately not complete because my shell's buffer was too small.  Strangely I can't see any compiler errors, just warnings.

**Comment by tmalsburg** [comment]
After reinstalling RStan the situation is different.  The build process is now massively leaking memory and my 16GB RAM are used up after two minutes  or so after which the system crashes.

[error2.log](https://github.com/stan-dev/rstanarm/files/6435825/error2.log)

**Comment by andrjohns** [comment]
Can you try the install with only 1 core and log the output to a file:
```r
Sys.setenv(MAKEFLAGS="-j1")
sink(file="rstanarm.log")
Sys.setenv("R_REMOTES_NO_ERRORS_FROM_WARNINGS" = "true")
remotes::install_github("stan-dev/rstanarm", INSTALL_opts = "--no-multiarch", force = TRUE)
sink(file=NULL)
```

Then upload that log file if the installation fails?

**Comment by tmalsburg** [comment]
With just one core, it finishes successfully. Took 30min or so.  The culprit seems to be the C compiler which consumes up to 7GB RAM. Multiply this by 4 cores and 16GB RAM are quickly maxed out.

**Comment by tmalsburg** [comment]
I suppose this issue can be closed then.  But I'm left wondering how people with less RAM manage to work with rstanarm.  Most of the new M1 Macs have just 8GB.  On those machines compilation could be challenging even with just one core.

**Comment by andrjohns** [comment]
This isn't unexpected. When installing the `rstanarm` package from source, each of the base Stan models has to be compiled. Compiling models can easily hit 4+gb of ram usage, depending on the model. This is a area where installing the `rstanarm` binaries is an attractive alternative, as all models are pre-compiled and ready to use right away

**Comment by tmalsburg** [comment]
Thanks for the response.  It's interesting that I can easily compile the Linux kernel and other heavy-weight software, but rstanarm, a relatively simple software, is so much more demanding. Assuming that rstanarm will become more complex over time, we might soon reach a point where the majority of users can't compile it.  At some point the project team will have to think about remedies for this enormous RAM consumption.

**Comment by andrjohns** [comment]
I should have been more specific. It's not `rstanarm` that is taking up RAM while compiling, it's the stan models that `rstanarm` uses (i.e., `stan_glm`). Stan models (in general) require a decent amount of RAM to compile, because they are a single large, complex, program. The linux kernel on the other hand is comprised of many smaller objects that are built independently. This is why you can compile the linux kernel with 64+ threads, but you can only compile a Stan model with 1 thread. It's not really an apples-to-apples comparison

**Comment by tmalsburg** [comment]
That's approximately what I expected to be the cause of the issue. But apples aside, if compilation is expected to be problematic with more than one thread, it's at least slightly unfortunate to provide installation instructions that default to 4 cores (see [here](https://github.com/stan-dev/rstanarm#development-version)). Why provide instructions that will crash most users' machines?  I've heard from a bunch of other users who had the same experience. 🤷

**Comment by andrjohns** [comment]
Good point! I'll get that changed now
