### ISSUE TITLE
stan_clogit: allow outcome to be factor

### ISSUE THREAD

**Issue by nlpaces** [stan-dev/rstanarm#519]
#### Summary:
Change acceptable class response variable

#### Description:
I had assumed that the class of response variable used in the standard clogistic regression function would be accepted in stan_clogit function. clogistic accepts factors. stan_clogit doesn’t. Once I had reformated to numeric, stan_clogit ran without difficulty.

#### Reproducible Steps:
Message from Jonah:
Good catch! If you want to open an issue at the rstanarm GitHub repo we’ll definitely consider adding support for factors. I think it makes sense to allow them.

#### RStanARM Version:
2.21.1

#### R Version:
3.6.3

#### Operating System:
Ubuntu 18.04.4 LTS

**Comment by jgabry** [comment]
Thanks for opening the issue. We'll look into allowing the response
variable to be a factor.
