### ISSUE TITLE
Separation of tensors and interactions in GAMM models

### ISSUE THREAD

**Issue by noamross** [stan-dev/rstanarm#52]
The gamm4 models use `t2()` in place of `te()` for tensor splines, but have to equivalent for `ti()`.  This means one can't separate the interactions from the main effects, as in this example: http://stats.stackexchange.com/a/189437/28370

It would be great if `stan_gamm4()` could support `ti()` terms or something similar.

Related to #46

**Comment by bgoodri** [comment]
At the moment, `stan_gamm4()` calls `gamm4::gamm4()` to parse the formulas (which has the unfortunate side effect of estimating the model with `lme4` before reestimating it with Stan). So, we currently can support anything iff `gamm4::gamm4()` supports it. I have yet not reached out to Simon Wood about a few things that would make things easier for `stan_gamm4()` but when I do, I could raise the `ti()` thing.

**Comment by noamross** [comment]
Thanks. Does this mean I should be able to use gamm4's "lpmatrix" output
from a predict() call to the same model fitted with gamm4 but multiply it
with coefficients from the stan_gamm4 posterior?

**Comment by bgoodri** [comment]
Yes and no, which was the conflict we are facing with https://github.com/stan-dev/rstanarm/issues/46 . You should be able to call `predict.gam()` with `type = "lpmatrix"` on the `$gam` element of the stanreg list returned by `stan_gamm4()`. However, that does not account for any group-specific parameters originally specified in the `random` argument to `[stan_]gamm4()`. We have some code to do that in the `predict()` method for objects created by `stan_glmer()`, but we didn't have time to work everything out before the first release of rstanarm. In-sample posterior prediction works currently after `stan_gamm4()`.

**Comment by jgabry** [comment]
@bgoodri is this resolved by #131? or is separate from just getting `posterior_predict` functioning?

**Comment by bgoodri** [comment]
I think I accidentally implemented support for `ti()`

**Comment by noamross** [comment]
Yes, it looks like you did - since you are now using `gamm` instead of `gamm4` the `ti()` terms in the model are usable and converted properly.
