### ISSUE TITLE
warnings about VarCorr

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#56]
Email from Martin Maechler:

Yesterday, a new version of  'nlme'  was released on CRAN,
for which the  VarCorr()  S3 generic has a new '...' argument
--- so that others can write methods with extra arguments,
something really desirable.

However, this lead to the following WARNINGS for your packages,
which we'd ask you to fix.

I strongly recommend you to do what I (as co-author) did for the
lme4 package:

1) in your DESCRIPTION, depend on the very latest nlme,
   i.e., put
              nlme (>= 3.1-123)
   in your 'Imports:'  or  'Depends:' in your DESCRIPTION file

2) add  ', ...' at the end of the argument list of your VarCorr.<cls>
   function definition,
   both in R/*.R and man/*.Rd

https://github.com/lme4/lme4/commit/61de24187b0b9b672bc8e9749160919f79e6c139

**Comment by bgoodri** [comment]
Upon further review, the `rdig` argument to `VarCorr` is being eliminated as well.

**Comment by jgabry** [comment]
Right now we're only "importing" nlme indirectly via having lme4 in
Imports. So do we need to wait to change VarCorr until the version of lme4
with lme4/lme4@61de241
<https://github.com/lme4/lme4/commit/61de24187b0b9b672bc8e9749160919f79e6c139>
is
released on CRAN?

**Comment by bgoodri** [comment]
I think so.
