### ISSUE TITLE
Problem updating rstanarm on Ubuntu 20.04 LTS 

### ISSUE THREAD

**Issue by paulauvirage** [stan-dev/rstanarm#565]
#### Summary:
When updating the package, I get the error ` make: *** [/usr/lib/R/etc/Makeconf:175: stan_files/bernoulli.o] Error 1
   rm stan_files/bernoulli.cc
   ERROR: compilation failed for package ‘rstanarm’`

I get the same error message when trying to: (1) install from Cran; and (2) installation of the development version following the standard instructions (https://github.com/stan-dev/rstanarm#development-version) and tyring both `MAKEFLAGS = "-j2"` and `MAKEFLAGS = "-j1"`

I am running R 4.1.3 and already have installled rstan 2.26.10 and rstanarm 2.21.1

**Comment by jgabry** [comment]
Sorry for the slow reply. I don't know much about installing on Ubuntu but I'm tagging @bgoodri who knows a lot more about Linux than I do.

**Comment by bgoodri** [comment]
My guess is that you ran out of RAM. If you are in the sudoers group, then you can also `sudo apt install r-cran-rstanarm`.

**Comment by mikegilchrist** [comment]
This is the same error message discussed in  `Install issue - splitting "Application Support" path to RcppParallel ` #579
