### ISSUE TITLE
make sure all tests pass a seed argument

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#57]
We now have a non-reproducible failure on r-devel for Windows
https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/rstanarm-00check.html

**Comment by jgabry** [comment]
You think it's just a PRNG issue? I don't think we changed anything that
would cause any other kind of sudden error.

**Comment by bgoodri** [comment]
It worked the first time and then the nlme update triggered a recheck. The
master branch just passed r-devel on win-builder, so I am guessing
something is non-deterministic.

**Comment by jgabry** [comment]
It's not particularly encouraging that some of these tests are so sensitive
to the seed. And I think it mostly happens for advi.
