### ISSUE TITLE
Current CRAN failures and potential removal

### ISSUE THREAD

**Issue by topepo** [stan-dev/rstanarm#586]
We've received: 

> Dear maintainers,
> 
> This concerns the CRAN packages
> 
>   BayesPostEst IRexamples bayesrules brada eefAnalytics evidence fbst
>   rstanarm tidyposterior webSDM
> 
> maintained by one of you:

 `<snip>`

> We have asked for an update fixing the check problems shown at
>   <https://www.google.com/url?q=https://cran.r-project.org/web/checks/check_results_rstanarm.html&source=gmail-imap&ust=1680500146000000&usg=AOvVaw1WRndPgFrCGTiD6V54PtpY>
> with no update from the maintainer thus far.
> 
> Thus, package rstanarm is now scheduled for archival on 2023-04-10, and
> archiving this will necessitate also archiving its CRAN strong reverse
> dependencies.
> 
> Please negotiate the necessary actions.
> 
> The CRAN Team

Is there anything that we can do? It looks like the issue list isn't terrible (and some are ignorable).

It would be good to know if fixes are in progress.

**Comment by andrjohns** [comment]
Aside from the `NOTE`s, there's a `donttest` examples failure: https://www.stats.ox.ac.uk/pub/bdr/donttest/rstanarm.out

I fixed that particular issue as part of #574. I'll extract the change to a standalone PR and address the other `NOTE`s as well

**Comment by andrjohns** [comment]
Just double-checking compatibility against 2.26 and 2.31 as well, might as well add the minimum updates needed for that too

**Comment by andrjohns** [comment]
@jgabry are we able to submit updates to CRAN if we can't get in touch with Ben before the archival deadline on the 10th?

**Comment by jgabry** [comment]
I actually talked to him yesterday. He’s aware of the situation and will
merge your PRs and submit the release in time.

Thanks for your help with this!

**Comment by andrjohns** [comment]
Oh brilliant, thanks for checking!

**Comment by andrjohns** [comment]
Updated rstanarm is now on CRAN
