### ISSUE TITLE
`posterior_linpred()` for `stan_gamm4()` errors with 'Matrix' v1.6-4

### ISSUE THREAD

**Issue by fweber144** [stan-dev/rstanarm#610]
#### Summary:
Calling `posterior_linpred()` on a `stan_gamm4()` fit errors if version 1.6-4 of the [Matrix](https://CRAN.R-project.org/package=Matrix) package is installed.

#### Description:
See "Summary" above.

#### Reproducible Steps:
```r
# Based on the example section of `?rstanarm::stan_gamm4`.
library(rstanarm)
nobs <- 400
ngrp <- 20
dat <- mgcv::gamSim(1, n = nobs, scale = 2)
dat$fac <- as.factor(sample.int(ngrp, size = nobs, replace = TRUE))
dat$y <- dat$y + model.matrix(~ fac - 1, data = dat) %*% rnorm(ngrp) * 0.5
rfit <- stan_gamm4(y ~ s(x0) + x1 + s(x2), data = dat, random = ~ (1 | fac),
                   chains = 1, iter = 500, seed = 198, refresh = 0)
pl <- posterior_linpred(rfit)

```
The last line succeeds with 'Matrix' v1.6-3, but errors with 'Matrix' v1.6-4:
```
Error in initializePtr() :
  function 'chm_factor_ldetL2' not provided by package 'Matrix'
```

#### RStanARM Version:
2.26.1 (from CRAN)

#### R Version:
4.3.2

#### Operating System:
Ubuntu 22.04.3 LTS

**Comment by avehtari** [comment]
Here's the reproducible example without `rstanarm`
```
library(gamm4)
nobs <- 400
ngrp <- 20
dat <- mgcv::gamSim(1, n = nobs, scale = 2)
dat$fac <- as.factor(sample.int(ngrp, size = nobs, replace = TRUE))
dat$y <- dat$y + model.matrix(~ fac - 1, data = dat) %*% rnorm(ngrp) * 0.5
rfit <- stan_gamm4(y ~ s(x0) + x1 + s(x2), data = dat, random = ~ (1 | fac))
```

**Comment by jgabry** [comment]
Thanks, I guess I'll send Simon an email.

**Comment by jgabry** [comment]
Thanks, just sent Simon Wood an email using the email address on the CRAN page for gamm4

**Comment by jgabry** [comment]
I corresponded with Simon and it seems like an issue with incompatible versions of lme4 and Matrix (for some reason there isn't backwards compatibility and both need to updated to the latest versions). If you update lme4 does this error go away? That got it working for me.

**Comment by fweber144** [comment]
Hm, that's strange. At the time of my initial comment, my lme4 version was already at 1.1-35.1 (the current [CRAN](https://cran.r-project.org/package=lme4) version) and it still is. Do you refer to the most recent GitHub version of lme4?

To be safe, I have now updated all my R packages (except for [tikzDevice](https://cran.r-project.org/package=tikzDevice), but that shouldn't matter here) to their most recent CRAN versions (and StanHeaders to its most recent https://mc-stan.org/r-packages/ version, but again, that shouldn't matter here), but the issue still occurs.

**Comment by jgabry** [comment]
Hmm, very strange. I wasn't referring to the GitHub version of lme4, just the latest CRAN version. According to Simon Wood gamm4 should work with any pair of lme4 and Matrix that are compatible with each other, but that seems not to be the case for you (although it works for me now). Not sure what's going on, but I definitely think it's related to lme4/Matrix/gamm4 and not anything specific to rstanarm.

**Comment by fweber144** [comment]
Yes, seems to be unrelated to rstanarm. If you want, you can close this issue here.

**Comment by fweber144** [comment]
> In case someone gets hits by this and finds this issue, it's about binary incompatibility, and installing `lme4` and `Matrix` from source solves this (+ restart R session). See https://stackoverflow.com/questions/77481539/error-in-initializeptr-function-cholmod-factor-ldeta-not-provided-by-pack

Thanks, works indeed.
