### ISSUE TITLE
Excessive demo output scrolls past line limit

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstanarm#64]
I find that I can't get much from the ARM_Ch04 demo

    demo(ARM_Ch04, package='rstanarm')

because there is such a large amount of output from the MCMC estimation that I can only see the final results from the last estimation run -- everything else gets scrolled past the console line limit on RStudio.

The demo could avoid this problem by incorporating more stopping points that require the user to hit a key to continue.

**Comment by jgabry** [comment]
Thanks for letting us know. This might be a problem with some of the other demos too. I think we should reduce the amount of MCMC output by setting the `refresh` argument. I'll also look into adding more stopping points if shortening the MCMC isn't enough.
