### ISSUE TITLE
Vignettes do not display

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstanarm#68]
In RStudio, doing help(package=rstanarm), clicking on "User guides, package vignettes and other documentation", and then clicking on any of the listed vignettes (by name, or using the "HTML" link) gives a blank window. The "source" and "R code" links work just fine.

**Comment by ksvanhorn** [comment]
Additional info: Package version rstanarm 2.9.0-1. RStudio version is 0.99.486. Running on Windows 7.

**Comment by jgabry** [comment]
Thanks Kevin. I think this might be related to issue #50, which has been
resolved but not released yet. It will be in the next CRAN release which
we're planning to do very soon.

**Comment by jgabry** [comment]
I'm going to close this because I think it's solved by #50, but if it's still a problem after the next release we will reopen.
