### ISSUE TITLE
stan_survreg

### ISSUE THREAD

**Issue by avehtari** [stan-dev/rstanarm#69]
A wishlist item: Make stan_survreg similar to survreg in survival package.

**Comment by jgabry** [comment]
Yes I agree. I think we definitely should add the survival models, and it
shouldn't be difficult. Unfortunately I very much dislike the way models
are specified using the survival package, so I'm not sure if we should use
their syntax for consistently or try to come up with something better.

**Comment by bgoodri** [comment]
I have always found the `Surv()` syntax to be a bit confusing as well, but if that is what R users have internalized, then I think we would need a strong reason to invent a new syntax that is at least as general as that in the survival package.

**Comment by bgoodri** [comment]
In other words, it seems in my experience the reason why packages like survival have what appears to me to be an odd syntax is that the syntax is needed to express odd models that I am not so familiar with. 

If you look at `survival::survreg`, it is 175 lines of data parsing logic with some unexposed functions before it calls `survival::survreg.fit` with a `y` and a `X`. Whereas for `rstanarm:::stan_survreg` we just need to call `survival::survreg` with `model = TRUE`, `y = TRUE`, x = `TRUE` and `control = survreg.control(maxiter = 0, outer.max = 0)` and we are pretty much ready to call `rstanarm::stan_survreg.fit`. So, I would be hard pressed to think of a reason why we would spend months to develop and implement a new syntax that does everything the survival syntax can do, taking it on faith that it would end up being so much clearer that it would justify initially confusing everyone who is using `survreg` now.

**Comment by jgabry** [comment]
I agree with all of that. My main concern is that if the survival package
is confusing for us then it will certainly be confusing to anyone who
hasn't already used that package. And we don't necessarily need to
implement all of the functionality (some of it we probably don't want
and/or don't understand) and we might end up wanting to add functionality
beyond what survival can do. Does survival allow glmer-style formulas?

But I agree that currently doing it via survreg seems like the most viable
option.

**Comment by bgoodri** [comment]
I suppose there might be a bunch of SAS people who want to use Stan to estimate survival models but not enough to learn the survival syntax. But my guess is that such people object to learning R generally rather than learning the survival package specifically.

The formula for survreg supports frailty() calls, which is similar but not identical to what lme4 does.
