### ISSUE TITLE
try to avoid filling in the Zt Matrix with zeros

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#71]
Currently, it is possible to hit a size limit in the C code of the Matrix package, whereas `lme4::glmer` avoids this by keeping Zt in sparse form the whole time
```
Error in asMethod(object) :
 Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
10: asMethod(object)
9: as(x, "matrix")
8: as.matrix.Matrix(group$Zt)
7: as.matrix(group$Zt)
6: t(as.matrix(group$Zt))
5: stan_glm.fit(x = X, y = y, weights = weights, offset = offset, 
```

**Comment by bgoodri** [comment]
@jgabry Did I miss any instances where we could run into matrix vs. Matrix problems?

**Comment by jgabry** [comment]
I think there are some transpositions of Zt done in the loo and
posterior_predict/pp_data files.

**Comment by jgabry** [comment]
If the sparse representation of Z doesn't take up much memory then we could
just always store a copy of Z instead of having to transpose Zt every time
we use it. Although if t() is pretty fast with the sparse matrices I guess
it won't matter much.

**Comment by bgoodri** [comment]
t() is fast. I'll look at how Zt is handled in loo and posterior_predict.

**Comment by jgabry** [comment]
Out of curiosity, what was the model/grouping structure that reached the
size limit?

**Comment by bgoodri** [comment]
Like 300,000 rows and thousands of columns

**Comment by jgabry** [comment]
On Sunday, February 7, 2016, bgoodri <notifications@github.com> wrote:

> t() is fast. I'll look at how Zt is handled in loo and posterior_predict.


Should just be a few times and the same as the others.

>

**Comment by jgabry** [comment]
On Sunday, February 7, 2016, bgoodri <notifications@github.com> wrote:

> Like 300,000 rows and thousands of columns


Big but not outrageous. Hopefully it was just the sparse matrix stuff that
was the bottleneck.

>

**Comment by jgabry** [comment]
Does that model that was too big work after the sparse matrix changes?

**Comment by bgoodri** [comment]
My understanding is that it is running and could be that way for a while.
