### ISSUE TITLE
sparse X matrices

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#76]
We should have a flag to indicate whether `X` should be considered dense or sparse and in the case of the latter pass the data in like we do for `Z`. We'll have to figure out how sparse `X` needs to be in order for sparse matrix multiplication to be as fast as dense matrix multiplication, but I doubt it takes that much.

**Comment by jgabry** [comment]
I like it

**Comment by sakrejda** [comment]
Let me know if the speed test should be broader than currently stated in the [issue](https://github.com/stan-dev/math/issues/new).
