### ISSUE TITLE
Help with stan_lmer output

### ISSUE THREAD

**Issue by muthca** [stan-dev/rstanarm#77]
I’m conducting a large simulation study using the rstanarm package and need some help extracting output. I’m having trouble extracting the random effects, or 'Error terms’ that appear in the print(modelx) output. e.g.:

`BEmodels[[1]]
stan_glmer(formula = yti ~ poly(time, 2, raw = TRUE) + (poly(time, 
                                                             2, raw = TRUE) | id), data = DATAL[[x]])

Estimates:
  Median MAD_SD
(Intercept)                 5.2    0.3  
poly(time, 2, raw = TRUE)1 -2.0    0.4  
poly(time, 2, raw = TRUE)2  0.9    0.1  
sigma                       1.1    0.1  

Error terms:
  Groups   Name                       Std.Dev. Corr       
id       (Intercept)                0.49                
poly(time, 2, raw = TRUE)1 0.28      0.04      
poly(time, 2, raw = TRUE)2 0.17      0.50 -0.34
Residual                            1.14                
Num. levels: id 20 

Sample avg. posterior predictive 
distribution of y (X = xbar):
  Median MAD_SD
mean_PPD 5.4    0.2 `

I’ve been able to extract the fix estimate values from the summary(modelx) function, but this summary does not include ‘Error terms’. I’m looking for a simple subsetting solution that will allow me to extract the ‘Error terms’ with a loop function, in the way I’ve subset the fixed estimates, e.g.:

`be_mod = lapply(1:length(DATAL), function(x) {try(stan_lmer(yti ~ poly(time, 2, raw = TRUE)  +  (poly(time, 2, raw = TRUE) | id),  data=DATAL[[x]]))}) #simulation model, for X number of simulated datasets in DATAL

Remodels = lapply(1:length(be_mod), function(x) {summary(be_mod[[x]])}) #summary values

BE_slope1M_mean  = as.numeric(sapply(1:length(BEmodels), function(i) BEmodels[[i]][1,2])) # extracting point estimate of slope1 (varying parameter)`

**Comment by jgabry** [comment]
Hi Chelsea,

Are you trying to get point estimates for the error terms or the full
posterior distribution (i.e. all of the MCMC draws)? If the former then I
think that's what's returned by the VarCorr function. Let me know if I've
misunderstood and that's not what you're looking for.

On another note, there's an update available for rstanarm that fixes a few
important things, so if you haven't updated to version 2.9.0-3 yet I highly
recommend it.

Jonah

**Comment by muthca** [comment]
Hi Jonah,

Thanks so much for your help - I’ve updated my version of rstanarm. I
initially tried the VarCorr function, since I saw it in the documentation
on github, but I’m unsure how to get this function to work for my rstanarm
objects. For instance, when I try the function on the correlation matrix
from just one model in my list, I get this error:

> VarCorr(BEmodels2[[1]][7]) # model 1, correlation matrix
Error in UseMethod("VarCorr") :
  no applicable method for 'VarCorr' applied to an object of class "list"
> VarCorr(unlist(BEmodels2[[1]][7]))
Error in UseMethod("VarCorr") :
  no applicable method for 'VarCorr' applied to an object of class
"c('double', 'numeric')"

Do you have any suggestions?

Thanks much,
Chelsea

Chelsea Muth <http://www.muthca.com>
State College, PA

**Comment by jgabry** [comment]
I think this might just be an indexing thing. You seem to be passing it a
list instead of a stanreg object, but you you might just need an extra set
of brackets around the 7. What happens if you try
VarCorr(BEmodels2[[1]][[7]]?

**Comment by muthca** [comment]
I was hoping it was an indexing issue I could work out, but I'm still
hitting errors:

> VarCorr(BEmodels2[[1]][[7]])
Error in UseMethod("VarCorr") :
  no applicable method for 'VarCorr' applied to an object of class
"c('matrix', 'double', 'numeric')"

Here is the structure of the first items in the model:

> str(BEmodels2[[1]], max.level=1)
List of 25
 $ coefficients     : Named num [1:66] 4.9664 -1.7363 0.922 0.4991 0.0906
...
  ..- attr(*, "names")= chr [1:66] "(Intercept)" "poly(time, 2, raw =
TRUE)1" "poly(time, 2, raw = TRUE)2" "b[(Intercept) id:1]" ...
 $ ses              : Named num [1:66] 0.295 0.353 0.12 0.591 0.31 ...
  ..- attr(*, "names")= chr [1:66] "(Intercept)" "poly(time, 2, raw =
TRUE)1" "poly(time, 2, raw = TRUE)2" "b[(Intercept) id:1]" ...
 $ fitted.values    : num [1:80] 5.47 4.76 5.93 8.97 4.25 ...
 $ linear.predictors: num [1:80] 5.47 4.76 5.93 8.97 4.25 ...
 $ residuals        : num [1:80] 0.4414 0.30962 0.37753 -0.00436 -0.53548
...
 $ df.residual      : int NA
 $ covmat           : num [1:66, 1:66] 0.09285 -0.053335 0.010782 -0.045817
0.000255

...


Chelsea Muth <http://www.muthca.com>
State College, PA

**Comment by paul-buerkner** [comment]
It appears that `BEmodels2[[1]]` is your fitted model. If so, have you tried `VarCorr(BEmodels2[[1]])`?

**Comment by jgabry** [comment]
It kind of looks like somewhere in the process the class of the rstanarm
model, which should be "stanreg", is getting removed. Can you try manually
setting the class to "stanreg" (e.g., class(x) <- c("stanreg", class(x))
and then trying VarCorr?

**Comment by muthca** [comment]
Thank you both so much. The VarCorr(BEmodels2[[1]]) solution worked:

> str(VarCorr(BEmodels2[[1]]))
List of 1
 $ id: num [1:3, 1:3] 0.80994 -0.00441 -0.02776 -0.00441 0.21828 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:3] "(Intercept)" "poly(time, 2, raw = TRUE)1" "poly(time,
2, raw = TRUE)2"
  .. ..$ : chr [1:3] "(Intercept)" "poly(time, 2, raw = TRUE)1" "poly(time,
2, raw = TRUE)2"
  ..- attr(*, "stddev")= Named num [1:3] 0.9 0.467 0.181
  .. ..- attr(*, "names")= chr [1:3] "(Intercept)" "poly(time, 2, raw =
TRUE)1" "poly(time, 2, raw = TRUE)2"
  ..- attr(*, "correlation")= num [1:3, 1:3] 1 -0.0105 -0.17 -0.0105 1 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:3] "(Intercept)" "poly(time, 2, raw = TRUE)1"
"poly(time, 2, raw = TRUE)2"
  .. .. ..$ : chr [1:3] "(Intercept)" "poly(time, 2, raw = TRUE)1"
"poly(time, 2, raw = TRUE)2"
 - attr(*, "sc")= num 0.992
 - attr(*, "useSc")= logi TRUE
 - attr(*, "class")= chr "VarCorr.merMod"

I also tried changing the class of the model back to "stanreg", but that
still gave me the same error.

> class(BEmodels2) <- c("stanreg", class(BEmodels2))
> VarCorr(BEmodels2[[1]][[7]])
Error in UseMethod("VarCorr") :
  no applicable method for 'VarCorr' applied to an object of class
"c('matrix', 'double', 'numeric')"

At this point, I should be able to get the point estimates I need. Thank
you again.

Chelsea Muth <http://www.muthca.com>
State College, PA

**Comment by jgabry** [comment]
@paul-buerkner thanks for catching that. I misunderstood how they were being indexed. @muthca if the fitted model object is just `BEmodels2[[1]]`, then changing the class of `BEmodels2[[1]][[7]]` to "stanreg" wouldn't make sense, so you can just use `VarCorr(BEmodels2[[1]])` as Paul suggested. `BEmodels2[[1]]` should have class "stanreg" though, but I assume it does since the VarCorr method seems to be working now.

Also, just in case they were affected by the issues that were fixed in the recent update, if you haven't done so already I recommend refitting the models using the updated version of rstanarm.
