### ISSUE TITLE
stan_polr hangs when prior_PD=TRUE

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstanarm#80]
In order to understand the prior stan_polr uses, I am trying to call it with prior_PD=TRUE so that it will sample from the prior predictive distribution. What I'm finding is that stan_polr quickly goes through the warmup iterations, and then stops progressing (albeit using using full CPU.)

Specifically, trying 4 predictors, 10 observations, and 3 possible outcome levels, with 4000 iterations, I found that after quickly (a few seconds) running through the 2000 warmup iterations on all 4 chains, it then took 2 minutes before it progressed to iteration 2400 on chain 3, and after 47 minutes there was no further progress beyond that (none of the other chains made it to iteration 2400) and I killed it.

I retried the experiment with 100 observations instead of 10, using 2000 iterations, and got similar behavior:  all chains quickly went through the 1000 warmup iterations; one chain got to iteration 1200 after a few minutes; and no progress was seen beyond that. I continued for a total of 30 minutes before giving up.

**Comment by ksvanhorn** [comment]
BTW, this is on Mac OS X El Capitan, and R 3.2.1.

**Comment by bgoodri** [comment]
Yeah, that is a bug. The polr.stan file does rejection sampling to obtain latent residuals, but this does not make sense to do when just drawing from the prior. The most recent commit to the master branch on GitHub should prevent this.

**Comment by jgabry** [comment]
Pretty sure this is fixed now, so I'm going to close this issue. Of course it can be reopened if necessary.
