### ISSUE TITLE
rstanarm glmer models fail to launch in shinystan

### ISSUE THREAD

**Issue by tomwallis** [stan-dev/rstanarm#82]
#### Summary:
GLMMs fit using rstanarm do not produce any output for `launch_shinystan`, despite the model `print`ing fine.

#### Description:
I have models with a few fixed effects and one or two random effects. Even for simple models, `launch_shinystan(fit)` produces no output after a long time waiting. The function works fine for `lm` or `glm` models.

Is it the case that Shinystan doesn't support mixed effects models yet? I couldn't see this in the docs. Also, wasn't sure whether to post this issue into rstanarm or shinystan; sorry.

#### Reproducible Steps:
`demo("ARM_Ch14")`
once `M1` is fit, try calling `launch_shinystan(M1)`. This produces no output for me. Other models (e.g. `launch_shinystan_demo()` work fine.

#### RStanARM Version:
2.9.0.3

#### R Version:
The version of R you are running (e.g., from `getRversion()`)
3.2.3

#### Operating System:
OS X 10.11.3

**Comment by jgabry** [comment]
Thanks for reporting this. It should work with any rstanarm model, so I'll
look into this and move the issue to the shinystan repo if it turns out to
be a shinystan issue and not an rstanarm issue.

Can you check if launch_shinystan(example_model) works for you? The
rstanarm example_model was fit using stan_glmer.

>

**Comment by tomwallis** [comment]
Ok, so one possible reason for this is a misspecified dependency. When I ran `launch_shinystan(example_model)` I got the error:

```r
Error: This plot requires the 'arm' package (install.packages('arm'))
```

After installing `arm` that example model opens fine in shinystan (and I get some actual output when launching shinystan, such as "Loading... Note: for large models ShinyStan may take a few moments to launch.". I had no output before). However, when I now try to open my own model, I get the following error: 

```r
Error in `colnames<-`(`*tmp*`, value = c("xbar", "ybar", "se2")) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

The model I tried to view is fitting only an intercept term (i.e. `y ~ 1`), using the "meanfield" algorithm. Perhaps the lack of other predictors is why the object has fewer than two dimensions?

I tried another model that includes the intercept and a random effect term (`y ~ 1 + (1 | re_1)`; this has the same problem. However, if I add a fixed effect to the model (`y ~ 1 + (1 | re_1) + x1`) the model can be opened by shinystan.

So it seems that shinystan can't open a model with no fixed effects terms other than the intercept?

**Comment by jgabry** [comment]
On Fri, Mar 11, 2016 at 7:19 AM, Tom Wallis <notifications@github.com>
wrote:

> The model I tried to view is fitting only an intercept term (i.e. y ~ 1),
> using the "meanfield" algorithm. Perhaps the lack of other predictors is
> why the object has fewer than two dimensions?
>
> I tried another model that includes the intercept and a random effect term
> (y ~ 1 + (1 | re_1); this has the same problem. However, if I add a fixed
> effect to the model (y ~ 1 + (1 | re_1) + x1) the model can be opened by
> shinystan.
>
> So it seems that shinystan can't open a model with no fixed effects terms
> other than the intercept?
>
>
Thanks for the details. I've noticed a few potential issues here, but I'm
not seeing the exact behavior you're describing. If it's not too much
trouble, could you share a reproducible example?

**Comment by tomwallis** [comment]
Sorry for the delay. Here's a reproducible example:

```r
library(rstanarm)
dat <- mtcars

prior <- student_t(df = 3, location = 0, scale = 2.5)

fit1 <- stan_glm(am ~ 1, data = dat,
                 family = binomial(link="logit"),
                 prior_intercept = prior)

launch_shinystan(fit1)  

fit2 <- stan_glm(am ~ mpg, data = dat,
                 family = binomial(link="logit"),
                 prior_intercept = prior)

launch_shinystan(fit2)

```

`fit1` fails to launch ShinyStan with the following output:

```r
Loading... 
Note: for large models ShinyStan may take a few moments to launch.
Error in `colnames<-`(`*tmp*`, value = c("xbar", "ybar", "se2")) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

`fit2` launches fine.

**Comment by jgabry** [comment]
Thanks, that's helpful. It turns out the problem is actually with `rstanarm::pp_check`, which gets called by ShinyStan. And I think it's only an issue for binomial models. I will be pushing a fix to github for this shortly.

**Comment by jgabry** [comment]
The binned residual plot in the graphical posterior predictive checks was the issue. Its content isn't really useful for intercept only models, but now it should at least not throw that error.
