### ISSUE TITLE
stan_glmer with family="Gamma" not sampling

### ISSUE THREAD

**Issue by Athanasiamo** [stan-dev/rstanarm#83]
**#### Summary:**
stan_glmer with family="Gamma" has difficulties running iterations after the first iteration. Parallel processing on 4 cores, have all 4 chains start with 1st iteration, then three chains complete while the fourth does never move beyond iteration 1. Running it serially, the first chain never goes past 1st iteration.

**#### Description:**
I have reaction time data from two groups of people that I want to estimate with stan_(g)lmer. I've 
run through with stan_lmer, which samples slowly but steadily. But, I get only very few effective samples out (below 200 for default 2000 iterations with 1000 warm-ups). So I've been wanting to test running it with a Gamma distribution instead.

However, when I try this (on a multicore system), and all 4 chains are allocated to each their core with pids for me to track, only 3 of the chains actually sample. I end up idly waiting for the last chain to sample (never moves beyond 1/2000), while the other three have finished. This has happened every time I've tried. When I try running it serially, I never get the first chain sampling beyond the initial 1 iteration.

I get to errors. Anyone know what is going on? Am I specifying this incorrectly?
I do the same analysis with a binomial distribution for trial by trial accuracy, where I do not encounter these problems.

stan_glmer(RT~Group+(1|ID), data=datadf, family="Gamma")    --- stalls on one chain
stan_glmer(Acc~Group+(1|ID), data=datadf, family="binomial")  ---  works fine

**#### Reproducible Steps:**
testdf = matrix(NA, ncol=3)
for(i in 1:20){
   if(i < 11){ G = "Patients" ; m = 1200; std=300
   }else{      G = "Controls" ; m = 1000; std=300}

 testdf = rbind(testdf,cbind(rgamma(300, shape=(m^2)/(std^2), rate=m/std^2),G,paste("ID",i,sep="")))
}

testdf = as.data.frame(testdf)
names(testdf)  = c("RT","Group","ID")
testdf$RT = as.numeric(as.character(testdf$RT))

RTtest = stan_glmer(RT~Group+(1|ID),data=testdf, family="Gamma")

**#### RStanARM Version:**  2.9.0.3
**#### R Version:**  3.2.3
**#### Operating System: **OS X 10.10.5

**### Session Info:**
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
doParallel_1.0.10 iterators_1.0.8   foreach_1.4.3     HDInterval_0.1.1  rstanarm_2.9.0-3  Rcpp_0.12.3       rstan_2.9.0-3  ggplot2_2.0.0     plyr_1.8.3       

loaded via a namespace (and not attached):
compiler_3.2.3     nloptr_1.0.4       shinyjs_0.4.0      base64enc_0.1-3    tools_3.2.3        xts_0.9-7          lme4_1.1-11      digest_0.6.9       nlme_3.1-125       gtable_0.2.0       lattice_0.20-33    Matrix_1.2-3       shiny_0.13.1       shinystan_2.1.0    loo_0.1.5          gridExtra_2.2.1    stringr_1.0.0      gtools_3.5.0       dygraphs_0.7       htmlwidgets_0.6    stats4_3.2.3   grid_3.2.3         DT_0.1             inline_0.3.14      R6_2.1.2           minqa_1.2.4        reshape2_1.4.1     magrittr_1.5   codetools_0.2-14   shinythemes_1.0.1  scales_0.4.0       threejs_0.2.1      matrixStats_0.50.1 htmltools_0.3      MASS_7.3-45    splines_3.2.3      mime_0.4           colorspace_1.2-6   xtable_1.8-2       httpuv_1.3.3       stringi_1.0-1      munsell_0.4.3    markdown_0.7.7     zoo_1.7-12

**Comment by jgabry** [comment]
Thanks for reporting. I haven't had time yet to go through this in detail, but if you run this with lme4's glmer instead of stan_glmer do you get the results you expect or does it also run into problems? If the latter, then it might indicate issues with the specification of the model that don't have to do with stan_glmer.

**Comment by Athanasiamo** [comment]
I did try in lme4, but that did not work. I obviously googled it, and found that lme4 does not support gamma distributions. 
https://stat.ethz.ch/pipermail/r-sig-mixed-models/2011q1/015422.html

This seemed rather specific for lme4, and I understand that this is a "harder" model to fit, but I assumed this would be working with rstanarm. I might, of course, be wrong. It wouldn't be the first (or last) time.

**Comment by jgabry** [comment]
I didn't realize lme4 didn't support Gamma models, but I guess that's not too surprising. 

I just had a few minutes to play around with your data/model. I took a random sample of the observations (just to reduce the size of the dataset while debugging), rescaled `RT` by dividing by 1000, and specified the optional `init_r` argument (which is passed to `rstan::sampling` and controls the interval for generating random inits). If you try this
```{r}
testdf2 <- testdf[sample(1:nrow(tested), size = 1000), ]
testdf2$RT <- testdf2$RT/1000
RTtest = stan_glmer(RT~Group+(1|ID), data=testdf2, family=Gamma(link="log"), iter = 300, init_r = 0.1)
```
does it work better for you?

**Comment by Athanasiamo** [comment]
ah! Like a little piece of programming magic. It's slow, but it completes all chains. I've tried both the small and large simulated data. I'll start a model on the actual data, and let you know how it goes.

**Comment by jgabry** [comment]
Great, glad that helped! It's really nice to see an example where rstanarm let's you fit a model that's hard to fit without it. I'm going to close this issue for now, but we can definitely reopen it if you run into further difficulties with the Gamma model. And yeah, please do let us know how it goes with the real data.

**Comment by Athanasiamo** [comment]
Hope this doesn't open the ticket again. But thought I'd let you know that it worked well on the real data too. It did, unfortunately, not help with my problem. But that has to do with my data, not with the program. Thanks for this awesome tool, and your help in fixing my issue!

**Comment by jgabry** [comment]
(You can keep commenting without reopening it.) I'm glad you like rstanarm. I hope it continues to be useful and let us know if you have any suggestions as we continue to work on the package. It's very helpful to get feedback from users.

**Comment by Athanasiamo** [comment]
On a related note: I'm running a rather complex model, and I obviously expect it to need more time between each iteration given the complexity. But, I was wondering if you would have any rule-of-thumb or so to how long one would expect each step to take?  Or rather, after how much time would you abort sampling if it still had not started sampling?

like, given the time the model needs to run with lme4, what is a (un)reasonable time between iterations in stan? I understand this is a rather difficult question to answer, as it would also obviously depend on CPU and RAM power on the locale where the function is being run. But it might help in determining when to abort og whether to let the model run for a really long time to complete.

**Comment by jgabry** [comment]
Unfortunately I don't have a great rule of thumb. But if you have a model that you know will take a long time I would start by running it for only a few hundred iterations rather than a few thousand and seeing how things look. Often that's enough either for the model to converge or for it to be clear that there are problems that won't be resolved by running it longer. Of course there are cases where you wouldn't be able to tell either of those things from a few hundred iterations, but that tends to be the case for the families of models that can be fit using rstanarm.
