### ISSUE TITLE
stan_lm only produces positive regression coefficients with univariate regression

### ISSUE THREAD

**Issue by ksvanhorn** [stan-dev/rstanarm#91]
#### Summary:
stan_lm(y ~ x, ...) produces only positive regression coefficients for x even when x and y clearly have negative correlation.

#### Description:
When I do a univariate linear regression with stan_lm, it does not seem to be possible to get a negative regression coefficient. Using data where y is clearly negatively correlated with x, I get a posterior distribution for the regression coefficient that cuts off sharply at 0.

#### Reproducible Steps:
    x <- c(1.03, 0.97, 1.21, 1.21, 1.01, 1, 1.26, 1.32, 0.99, 0.85, 1.16, 1.19, 1.07, 0.95, 1.1, 1.2, 0.8, 0.91, 1.11)
    y <- c(-0.81, -0.84, -1.03, -0.95, -0.93, -0.79, -0.92, -1.1, -0.79, -0.77, -0.76, -0.88, -0.84, -0.99, -0.93, -1.13, -0.72, -0.81, -1.03)
    plot(x, y, pch=19) # visually verify negative correlation
    lm(y ~ x) # gives a regression coefficient of about -0.56
    fit <- rstanarm::stan_lm(y ~ x, prior = rstanarm::R2(location = 0.5, what='mean'))
    print(fit, digits=4) # posterior mean of about 0.04 for x coefficient
    stan_hist(fit, pars='x')  # distribution cuts off sharply near zero
    df <- as.data.frame(fit)
    min(df$x)  # a positive value

#### RStanARM Version:
2.9.0.3

#### R Version:
3.2.4

#### Operating System:
Windows 7

**Comment by ksvanhorn** [comment]
I also tried

    x <- rnorm(19)
    y <- -3 * x + rnorm(19)

and ran stan_lm on this data, with the same result: the posterior distribution rises to a peak near zero and then cuts off sharply, with no posterior draw being negative.

**Comment by jgabry** [comment]
Ok yeah it was just an issue with a single x variable. Fixed in commit a211322. Thanks again for the report.
