### ISSUE TITLE
refit model leaving out some observations

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/rstanarm#94]
#### Summary:
With rstanarm, it should be possible to calculate the LOO criterion using a mix of the approximation (for observations with a small pareto parameter) and actually leaving some observation(s) out and predicting them

#### Description:
When some of the pareto parameters are not OK, rstanarm users don't really know what to do. We should have a `loo()` that takes a continuous threshold for the pareto parameter or a integer vector of observations to actually exclude when calculating the overall LOO.

#### Reproducible Steps:
Do a model where some pareto parameters are > 0.5

#### RStanARM Version:
2.9.0-3

#### R Version:
3.3.0

#### Operating System:
Debian

**Comment by jgabry** [comment]
Agreed. At least for models that run quickly this would be great to have.
