### ISSUE TITLE
Multivariate Cox regression in rstanarm

### ISSUE THREAD

**Issue by lixiangchun** [stan-dev/rstanarm#95]
#### Description:
Will the stan development team consider to add multivariate Cox regression in rstanarm in the future release?

**Comment by avehtari** [comment]
Yes. This is related to the issue #69
There is no plan when this might happen.

**Comment by bgoodri** [comment]
Also nothing definitive as to whether it would be part of rstanarm or another package like rstansurvival.

**Comment by bgoodri** [comment]
There's lots to discuss, but let's keep it on #69
