### ISSUE TITLE
Many fitting functions can't be launched without attaching the package

### ISSUE THREAD

**Issue by lionel-** [stan-dev/rstanarm#97]
Expressions evaluated in the calling environment (typically the GlobalEnv or the execution env of some function) should have namespaced function names. For instance in `stan_lmer()`:

```{r}
mc[[1L]] <- quote(stan_glmer)
```

should be

```{r}
mc[[1L]] <- quote(rstanarm::stan_glmer)
```

Otherwise rstanarm needs to be attached to the search path or fully imported in a package namespace to work properly.

You can use this kind of test for this issue:

```{r}
test_that("stan_lmer can be called without attaching the package", {
  fit <- function(seed) {
    rstanarm::stan_lmer(disp ~ drat + (1 | cyl), data = mtcars,
                        chains = 1, iter = 1, seed = seed)
  }
  environment(fit) <- baseenv()

  expect_silent(expect_stanreg(fit(SEED)))
})
```

I'd send a PR but for some reason devtools or roxygen is failing and I don't have time to figure out why.

**Comment by jgabry** [comment]
Thanks a lot for the tip, we'll look into that.

As for devtools failing, if you're trying devtools::document() or
devtools::load_all() then those aren't going to work with rstanarm
currently. roxygen2::roxygenize() should work though.

**Comment by jgabry** [comment]
Actually I spoke too soon. @bgoodri has a fix for at least
one devtools-related problem.

**Comment by lionel-** [comment]
great! And thanks for the quick fixes :)

**Comment by bgoodri** [comment]
fixed by ff2da71

**Comment by jgabry** [comment]
@bgoodri Does this fix just the devtools thing or also the original issue about running the functions without attaching the package? Also, I don't see a commit ff2da71.

**Comment by bgoodri** [comment]
It works for me, although the commit got rehashed to 38441f6.

**Comment by lionel-** [comment]
@jgabry it seems your fix branch with the qualified symbols still needs to be merged in.

**Comment by jgabry** [comment]
Hmm, that branch is failing on travis: https://travis-ci.org/stan-dev/rstanarm/builds/136234267. It doesn't seem to like the proposed test 

```r
test_that("stan_lmer works without attaching package", {
  fit <- function(seed) {
    rstanarm::stan_lmer(disp ~ drat + (1 | cyl), data = datasets::mtcars,
                        chains = 1, iter = 2, seed = seed)
  }
  environment(fit) <- baseenv()
  expect_stanreg(fit(SEED))
})
```
although that test doesn't fail locally for me.

**Comment by lionel-** [comment]
I know the feeling, I'm also dealing with a weird Travis failure right now.
