### ISSUE TITLE
predict() method fails with varying coefs

### ISSUE THREAD

**Issue by lionel-** [stan-dev/rstanarm#98]
The following produces an error:

```r
library(rstanarm)
fit <- stan_glmer(disp ~ (1 | cyl), mtcars)
predict(fit, newdata = data.frame(cyl = c("4", "6", "8")))
```

`posterior_predict()` works fine. Tested on master.

**Comment by jgabry** [comment]
I just noticed I missed this in my inbox. Thanks for reporting the error. I
thought we had a test for that but I guess not. We'll look into it.
Thankfully it's not posterior_predict, which is the more important
function.

**Comment by jgabry** [comment]
It now throws an error with an informative message saying that `posterior_predict` should be used instead of `predict` for models fit using `stan_glmer`
